/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useMemo, useContext, createContext } from "react";
import { useGLTF, Merged } from "@react-three/drei";

const context = createContext();
export function Instances({ children, ...props }) {
  const { nodes } = useGLTF("/detmay-t.glb");
  const instances = useMemo(
    () => ({
      LDecorStructure: nodes._l2_Decor_Structure,
      LBackdropbox: nodes._l0_Backdrop_box,
      LFloor: nodes._l0_Floor,
      LMainBackdrop: nodes._l0_Main_Backdrop,
      Mesh: nodes.mesh_4,
      Mesh1: nodes.mesh_4_1,
      Mesh2: nodes.mesh_4_2,
      LBPBannerleft: nodes._l1_BP_Banner_left_1,
      LBPVisualBannerleft: nodes._l1_BP_Visual_Banner_left_1,
      LBPVisualBannerleft1: nodes._l1_BP_Visual_Banner_left_2,
      Mesh3: nodes.mesh_8,
      Mesh4: nodes.mesh_8_1,
      LMenmannequin: nodes._l3_Men_mannequin,
      LMenmannequin1: nodes._l3_Men_mannequin001,
      LMenmannequin2: nodes._l3_Men_mannequin002,
      LMenmannequin3: nodes._l3_Men_mannequin003,
      LMenmannequin4: nodes._l3_Men_mannequin004,
      LMenmannequin5: nodes._l3_Men_mannequin005,
      LShoesbox: nodes._l3_Shoes_box,
      Mesh5: nodes.mesh_16,
      Mesh6: nodes.mesh_16_1,
      Mesh7: nodes.mesh_16_2,
      Mesh8: nodes.mesh_17,
      Mesh9: nodes.mesh_17_1,
      Mesh10: nodes.mesh_18,
      Mesh11: nodes.mesh_18_1,
      LWomenmannequinbox: nodes._l3_Women_mannequin_box,
      LWomenmannequinbox1: nodes._l3_Women_mannequin_box001,
      LWomenmannequinbox2: nodes._l3_Women_mannequin_box002,
      Mesh12: nodes.mesh_22,
      Mesh13: nodes.mesh_22_1,
      Mesh14: nodes.mesh_22_2,
    }),
    [nodes]
  );
  return (
    <Merged meshes={instances} {...props}>
      {(instances) => (
        <context.Provider value={instances} children={children} />
      )}
    </Merged>
  );
}

export function Model(props) {
  const instances = useContext(context);
  return (
    <group {...props} dispose={null}>
      <instances.LDecorStructure
        name="_l2_Decor_Structure"
        position={[-5.4, 1.7, -1.1]}
        rotation={[0, 1.6, 0]}
      />
      <instances.LBackdropbox
        name="_l0_Backdrop_box"
        position={[-0.3, 6.1, -5.4]}
        scale={[1.4, 1.3, 0.4]}
      />
      <instances.LFloor name="_l0_Floor" rotation={[0, -1.6, 0]} />
      <instances.LMainBackdrop
        name="_l0_Main_Backdrop"
        position={[-0.4, 5.2, -5]}
        scale={[0.7, 0.6, 0.3]}
      />
      <group
        name="_l2_Materials_shelf"
        position={[-0.2, 1.2, -3]}
        scale={[3.4, 1.3, 0]}
      >
        <instances.Mesh name="mesh_4" />
        <instances.Mesh1 name="mesh_4_1" />
        <instances.Mesh2 name="mesh_4_2" />
      </group>
      <instances.LBPBannerleft
        name="_l1_BP_Banner_left_1"
        position={[-5.1, 1, 0.2]}
        rotation={[0, 0.2, 0]}
        scale={[1.1, 1.1, 0.9]}
      />
      <instances.LBPBannerleft
        name="_l1_BP_Banner_left_2"
        position={[4.6, 1, 0.2]}
        rotation={[0, -0.2, 0]}
        scale={[1.1, 1.1, 0.9]}
      />
      <instances.LBPVisualBannerleft
        name="_l1_BP_Visual_Banner_left_1"
        position={[-5.1, 1, 0.2]}
        rotation={[0, 0.2, 0]}
        scale={[1.1, 1.1, 0.9]}
      />
      <instances.LBPVisualBannerleft1
        name="_l1_BP_Visual_Banner_left_2"
        position={[4.6, 1, 0.2]}
        rotation={[0, -0.2, 0]}
        scale={[1.1, 1.1, 0.9]}
      />
      <group
        name="_l3_bagest"
        position={[-4.8, 1.6, 2.1]}
        rotation={[-Math.PI / 2, 0, 1.8]}
        scale={0}
      >
        <instances.Mesh3 name="mesh_8" />
        <instances.Mesh4 name="mesh_8_1" />
      </group>
      <instances.LMenmannequin
        name="_l3_Men_mannequin"
        position={[2.2, 0, 1.2]}
        rotation={[Math.PI, -1, Math.PI]}
        scale={0.2}
      />
      <instances.LMenmannequin1
        name="_l3_Men_mannequin001"
        position={[2.2, 0, 1.2]}
        rotation={[Math.PI, -1, Math.PI]}
        scale={0.2}
      />
      <instances.LMenmannequin2
        name="_l3_Men_mannequin002"
        position={[2.2, 0, 1.2]}
        rotation={[Math.PI, -1, Math.PI]}
        scale={0.2}
      />
      <instances.LMenmannequin3
        name="_l3_Men_mannequin003"
        position={[2.2, 0, 1.2]}
        rotation={[Math.PI, -1, Math.PI]}
        scale={0.2}
      />
      <instances.LMenmannequin4
        name="_l3_Men_mannequin004"
        position={[2.2, 0, 1.2]}
        rotation={[Math.PI, -1, Math.PI]}
        scale={0.2}
      />
      <instances.LMenmannequin5
        name="_l3_Men_mannequin005"
        position={[2.6, 2.1, 1.5]}
        rotation={[Math.PI, -1, Math.PI]}
        scale={0.2}
      />
      <instances.LShoesbox
        name="_l3_Shoes_box"
        position={[-5.8, 0.6, 2.4]}
        rotation={[-Math.PI / 2, 0, 0.2]}
        scale={0}
      />
      <group
        name="_l3_Shose"
        position={[-6.1, 0.2, 3.5]}
        rotation={[-1.4, 0, -1.1]}
        scale={[0, 0, 0.1]}
      >
        <instances.Mesh5 name="mesh_16" />
        <instances.Mesh6 name="mesh_16_1" />
        <instances.Mesh7 name="mesh_16_2" />
      </group>
      <group
        name="_l3_Women_mannequin"
        position={[-3.5, 2.1, 0.8]}
        rotation={[-Math.PI / 2, 0, 1.9]}
        scale={0}
      >
        <instances.Mesh8 name="mesh_17" />
        <instances.Mesh9 name="mesh_17_1" />
      </group>
      <group
        name="_l3_Women_mannequin001"
        position={[-3.7, 1.1, 2.2]}
        rotation={[-Math.PI / 2, 0, 0.7]}
        scale={0}
      >
        <instances.Mesh10 name="mesh_18" />
        <instances.Mesh11 name="mesh_18_1" />
      </group>
      <instances.LWomenmannequinbox
        name="_l3_Women_mannequin_box"
        position={[-3.5, 0.2, 0.9]}
        rotation={[-Math.PI / 2, 0, 0.3]}
        scale={0}
      />
      <instances.LWomenmannequinbox1
        name="_l3_Women_mannequin_box001"
        position={[-4.8, 0.7, 2.2]}
        rotation={[-Math.PI / 2, 0, 1.8]}
        scale={0}
      />
      <instances.LWomenmannequinbox2
        name="_l3_Women_mannequin_box002"
        position={[-3.7, 0.3, 1.8]}
        rotation={[-Math.PI / 2, 0, -0.3]}
        scale={0}
      />
      <group
        name="_l0_Sign_Box_001"
        position={[5.9, 0, 3.8]}
        scale={[1, 2, 0.2]}
      >
        <instances.Mesh12 name="mesh_22" />
        <instances.Mesh13 name="mesh_22_1" />
        <instances.Mesh14 name="mesh_22_2" />
      </group>
    </group>
  );
}

useGLTF.preload("/detmay-t.glb");
