/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { JSX, useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    _l3_Meat_shelf_background: THREE.Mesh;
    mesh_1_instance_0: THREE.Mesh;
    _l3_Meat_shelf_background001: THREE.Mesh;
    mesh_2_instance_0: THREE.Mesh;
    mesh_3: THREE.Mesh;
    mesh_3_1: THREE.Mesh;
    _l3_Meat_shelf_background003: THREE.Mesh;
    mesh_2_instance_1: THREE.Mesh;
    mesh_4: THREE.Mesh;
    mesh_4_1: THREE.Mesh;
    mesh_4_2: THREE.Mesh;
    mesh_4_3: THREE.Mesh;
    _l3_Veges_Details002: THREE.Mesh;
    _l3_Veges_shelf_background: THREE.Mesh;
    mesh_7: THREE.Mesh;
    _l3_Veges_shelf_background001: THREE.Mesh;
    mesh_8_instance_0: THREE.Mesh;
    _l3_Veges_shelf_background002: THREE.Mesh;
    mesh_8_instance_1: THREE.Mesh;
    _l3_Veges_shelf_background003: THREE.Mesh;
    mesh_8_instance_2: THREE.Mesh;
    mesh_9: THREE.Mesh;
    mesh_9_1: THREE.Mesh;
    mesh_9_2: THREE.Mesh;
    mesh_9_3: THREE.Mesh;
    mesh_9_4: THREE.Mesh;
    mesh_9_5: THREE.Mesh;
    mesh_9_6: THREE.Mesh;
    mesh_10: THREE.Mesh;
    mesh_10_1: THREE.Mesh;
    mesh_10_2: THREE.Mesh;
    mesh_10_3: THREE.Mesh;
    mesh_10_4: THREE.Mesh;
    mesh_10_5: THREE.Mesh;
    mesh_10_6: THREE.Mesh;
    mesh_11: THREE.Mesh;
    mesh_11_1: THREE.Mesh;
    mesh_11_2: THREE.Mesh;
    mesh_11_3: THREE.Mesh;
    mesh_11_4: THREE.Mesh;
    mesh_11_5: THREE.Mesh;
    mesh_11_6: THREE.Mesh;
    mesh_11_7: THREE.Mesh;
    mesh_12: THREE.Mesh;
    mesh_12_1: THREE.Mesh;
    mesh_12_2: THREE.Mesh;
    mesh_12_3: THREE.Mesh;
    mesh_12_4: THREE.Mesh;
    mesh_12_5: THREE.Mesh;
    mesh_12_6: THREE.Mesh;
    _l4_Veges_Shelf_Details: THREE.Mesh;
    _l4_Veges_Shelf_Details001: THREE.Mesh;
    _l4_Veges_Shelf_Details002: THREE.Mesh;
    _l4_Veges_Shelf_Details003: THREE.Mesh;
    _l4_Veges_Shelf_Details004: THREE.Mesh;
    _l4_Veges_Shelf_Details005: THREE.Mesh;
    _l4_Veges_Shelf_Details006: THREE.Mesh;
    _l4_Veges_Shelf_Details007: THREE.Mesh;
    _l4_Veges_Shelf_Details008: THREE.Mesh;
    _l4_Veges_Shelf_Details009: THREE.Mesh;
    _l4_Veges_Shelf_Details010: THREE.Mesh;
    _l4_Veges_Shelf_Details011: THREE.Mesh;
    _l1_Backdrop_box: THREE.Mesh;
    _l1_Floor: THREE.Mesh;
    _l1_Main_Backdrop: THREE.Mesh;
    _l2_bamboo: THREE.Mesh;
    _l2_Circle_Banners: THREE.Mesh;
    mesh_30: THREE.Mesh;
    mesh_30_1: THREE.Mesh;
    mesh_30_2: THREE.Mesh;
    mesh_31: THREE.Mesh;
    mesh_31_1: THREE.Mesh;
    mesh_31_2: THREE.Mesh;
    mesh_32: THREE.Mesh;
    mesh_32_1: THREE.Mesh;
    mesh_32_2: THREE.Mesh;
  };
  materials: {
    ["Material.006"]: THREE.MeshStandardMaterial;
    ["Material.007"]: THREE.MeshStandardMaterial;
    Plywood_C_50cm: THREE.MeshStandardMaterial;
    ["Material.002"]: THREE.MeshStandardMaterial;
    Iron_Blurry_5cm: THREE.MeshStandardMaterial;
    ["MIROR 2"]: THREE.MeshStandardMaterial;
    ["storage basket"]: THREE.MeshStandardMaterial;
    ["Material.026"]: THREE.MeshStandardMaterial;
    ["Material.029"]: THREE.MeshStandardMaterial;
    ["Material.038"]: THREE.MeshStandardMaterial;
    ["Black Steel.002"]: THREE.MeshPhysicalMaterial;
    ["wood.002"]: THREE.MeshPhysicalMaterial;
    ["Grey.002"]: THREE.MeshPhysicalMaterial;
    ["Black.002"]: THREE.MeshPhysicalMaterial;
    ["Price09.001"]: THREE.MeshPhysicalMaterial;
    ["black_plastic.002"]: THREE.MeshStandardMaterial;
    green_plastic: THREE.MeshStandardMaterial;
    Price03: THREE.MeshPhysicalMaterial;
    ["Mis-vf_black"]: THREE.MeshPhysicalMaterial;
    glass: THREE.MeshPhysicalMaterial;
    wood_light: THREE.MeshPhysicalMaterial;
    Chrome: THREE.MeshPhysicalMaterial;
    ["Mis-vf_black-2"]: THREE.MeshPhysicalMaterial;
    ["Material.037"]: THREE.MeshStandardMaterial;
    ["Material.034"]: THREE.MeshStandardMaterial;
    ["photo corn bits"]: THREE.MeshStandardMaterial;
    ["pexels-photo-1313267"]: THREE.MeshStandardMaterial;
    ee14c22e9800997a474536eadc93a1a8: THREE.MeshStandardMaterial;
    ["cabbage-soup-diet-1"]: THREE.MeshStandardMaterial;
    ["photo tomato skin"]: THREE.MeshStandardMaterial;
    ["photo {3d75f229-7087-b44d-b407-5d2c7250592e}"]: THREE.MeshStandardMaterial;
    ["storage dark green"]: THREE.MeshStandardMaterial;
    ["storage dark red"]: THREE.MeshStandardMaterial;
    ["[Color_L22]1"]: THREE.MeshStandardMaterial;
    ["storage red"]: THREE.MeshStandardMaterial;
    ["storage orange"]: THREE.MeshStandardMaterial;
    ["LCD06.002"]: THREE.MeshStandardMaterial;
    ["Material.041"]: THREE.MeshStandardMaterial;
    ["Ash Wood"]: THREE.MeshPhysicalMaterial;
    bamboo: THREE.MeshStandardMaterial;
    S1: THREE.MeshStandardMaterial;
    ["Material.043"]: THREE.MeshStandardMaterial;
    ["Bamboo.002"]: THREE.MeshStandardMaterial;
    ["white.001"]: THREE.MeshStandardMaterial;
    white: THREE.MeshStandardMaterial;
    ["Material.042"]: THREE.MeshStandardMaterial;
    ["Material.001"]: THREE.MeshStandardMaterial;
    ["Material.010"]: THREE.MeshStandardMaterial;
    ["material0.001"]: THREE.MeshPhysicalMaterial;
  };
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/V4/food-t.glb"
  ) as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      {/* Level 1 Components */}
      <mesh
        name="_l1_Backdrop_box"
        castShadow
        receiveShadow
        geometry={nodes._l1_Backdrop_box.geometry}
        material={materials["LCD06.002"]}
        position={[-0.3623, 4.9304, -7.4652]}
        scale={[0.7375, 0.5994, 0.3217]}
      />
      <mesh
        name="_l1_Floor"
        castShadow
        receiveShadow
        geometry={nodes._l1_Floor.geometry}
        material={materials["Material.041"]}
        position={[-0.1309, 0.1472, 0.0286]}
        rotation={[0, -1.5705, 0]}
        scale={[0.9318, 0.9259, 1]}
      />
      <mesh
        name="_l1_Main_Backdrop"
        castShadow
        receiveShadow
        geometry={nodes._l1_Main_Backdrop.geometry}
        material={materials["Ash Wood"]}
        position={[-0.1039, 5.8921, -7.8459]}
        scale={[2, 1.3453, 0.4136]}
      />
      <group
        name="_l1_Sign_Box002"
        position={[8.7077, 2.0037, 5.8354]}
        rotation={[0, 0.6109, 0]}
        scale={[1.0047, 2.0054, 0.1907]}
      >
        <mesh
          name="mesh_32"
          castShadow
          receiveShadow
          geometry={nodes.mesh_32.geometry}
          material={materials["Material.001"]}
        />
        <mesh
          name="mesh_32_1"
          castShadow
          receiveShadow
          geometry={nodes.mesh_32_1.geometry}
          material={materials["Material.010"]}
        />
        <mesh
          name="mesh_32_2"
          castShadow
          receiveShadow
          geometry={nodes.mesh_32_2.geometry}
          material={materials["material0.001"]}
        />
      </group>

      {/* Level 2 Components */}
      <mesh
        name="_l2_bamboo"
        castShadow
        receiveShadow
        geometry={nodes._l2_bamboo.geometry}
        material={materials.bamboo}
        position={[-0.1309, -0.3185, 0.0286]}
        rotation={[0, -1.5705, 0]}
        scale={[1, 1.1942, 1]}
      />
      <mesh
        name="_l2_Circle_Banners"
        castShadow
        receiveShadow
        geometry={nodes._l2_Circle_Banners.geometry}
        material={materials.S1}
        position={[-0.1309, 9.5476, 0.0286]}
        rotation={[0, -1.5705, 0]}
        scale={[6.431, 7.6957, 6.431]}
      />
      <group
        name="_l2_Visual_led_left"
        position={[-6.6669, 2.1871, -4.7376]}
        rotation={[Math.PI / 2, 0, -0.4429]}
        scale={[3.4594, 0.9778, 2.2147]}
      >
        <mesh
          name="mesh_30"
          castShadow
          receiveShadow
          geometry={nodes.mesh_30.geometry}
          material={materials["Material.043"]}
        />
        <mesh
          name="mesh_30_1"
          castShadow
          receiveShadow
          geometry={nodes.mesh_30_1.geometry}
          material={materials["Bamboo.002"]}
        />
        <mesh
          name="mesh_30_2"
          castShadow
          receiveShadow
          geometry={nodes.mesh_30_2.geometry}
          material={materials["white.001"]}
        />
      </group>
      <group
        name="_l2_Visual_led_right"
        position={[6.2494, 3.6972, -4.8094]}
        rotation={[0, -0.4216, 0]}
        scale={0.8252}
      >
        <mesh
          name="mesh_31"
          castShadow
          receiveShadow
          geometry={nodes.mesh_31.geometry}
          material={materials["Bamboo.002"]}
        />
        <mesh
          name="mesh_31_1"
          castShadow
          receiveShadow
          geometry={nodes.mesh_31_1.geometry}
          material={materials.white}
        />
        <mesh
          name="mesh_31_2"
          castShadow
          receiveShadow
          geometry={nodes.mesh_31_2.geometry}
          material={materials["Material.042"]}
        />
      </group>

      {/* Level 3 Components */}
      <mesh
        name="_l3_Meat_shelf_background"
        castShadow
        receiveShadow
        geometry={nodes._l3_Meat_shelf_background.geometry}
        material={materials["Material.006"]}
        position={[-1.8966, 1.2978, -3.9237]}
        scale={[0.805, 1.2911, 0.003]}
      >
        <mesh
          name="mesh_1_instance_0"
          castShadow
          receiveShadow
          geometry={nodes.mesh_1_instance_0.geometry}
          material={materials["Material.007"]}
        />
      </mesh>
      <mesh
        name="_l3_Meat_shelf_background001"
        castShadow
        receiveShadow
        geometry={nodes._l3_Meat_shelf_background001.geometry}
        material={materials["Material.007"]}
        position={[-3.6836, 1.2978, -3.9237]}
        scale={[0.805, 1.2911, 0.003]}
      >
        <mesh
          name="mesh_2_instance_0"
          castShadow
          receiveShadow
          geometry={nodes.mesh_2_instance_0.geometry}
          material={materials["Material.006"]}
        />
      </mesh>
      <group
        name="_l3_Meat_shelf_background002"
        position={[-1.9146, 1.2978, -2.1553]}
        scale={[0.805, 1.2911, 0.003]}
      >
        <mesh
          name="mesh_3"
          castShadow
          receiveShadow
          geometry={nodes.mesh_3.geometry}
          material={materials["Material.006"]}
        />
        <mesh
          name="mesh_3_1"
          castShadow
          receiveShadow
          geometry={nodes.mesh_3_1.geometry}
          material={materials["Material.007"]}
        />
      </group>
      <mesh
        name="_l3_Meat_shelf_background003"
        castShadow
        receiveShadow
        geometry={nodes._l3_Meat_shelf_background003.geometry}
        material={materials["Material.007"]}
        position={[-3.6876, 1.2978, -1.9551]}
        scale={[0.805, 1.2911, 0.003]}
      >
        <mesh
          name="mesh_2_instance_1"
          castShadow
          receiveShadow
          geometry={nodes.mesh_2_instance_1.geometry}
          material={materials["Material.006"]}
        />
      </mesh>
      <group
        name="_l3_Veges_Details"
        position={[-3.3111, 0.0011, 4.0088]}
        rotation={[0, -1.5705, 0]}
        scale={1.1248}
      >
        <mesh
          name="mesh_4"
          castShadow
          receiveShadow
          geometry={nodes.mesh_4.geometry}
          material={materials.Plywood_C_50cm}
        />
        <mesh
          name="mesh_4_1"
          castShadow
          receiveShadow
          geometry={nodes.mesh_4_1.geometry}
          material={materials["Material.002"]}
        />
        <mesh
          name="mesh_4_2"
          castShadow
          receiveShadow
          geometry={nodes.mesh_4_2.geometry}
          material={materials.Iron_Blurry_5cm}
        />
        <mesh
          name="mesh_4_3"
          castShadow
          receiveShadow
          geometry={nodes.mesh_4_3.geometry}
          material={materials["MIROR 2"]}
        />
      </group>
      <mesh
        name="_l3_Veges_Details002"
        castShadow
        receiveShadow
        geometry={nodes._l3_Veges_Details002.geometry}
        material={materials["storage basket"]}
        position={[-3.3111, 0.0011, 4.0088]}
        rotation={[0, -1.5705, 0]}
        scale={1.1248}
      />
      <mesh
        name="_l3_Veges_shelf_background"
        castShadow
        receiveShadow
        geometry={nodes._l3_Veges_shelf_background.geometry}
        material={materials["Material.007"]}
        position={[1.9861, 1.2978, -2.1553]}
        scale={[1.0693, 1.2911, 0.003]}
      >
        <mesh
          name="mesh_7"
          castShadow
          receiveShadow
          geometry={nodes.mesh_7.geometry}
          material={materials["Material.026"]}
        />
      </mesh>
      <mesh
        name="_l3_Veges_shelf_background001"
        castShadow
        receiveShadow
        geometry={nodes._l3_Veges_shelf_background001.geometry}
        material={materials["Material.007"]}
        position={[4.273, 1.2978, -2.1553]}
        scale={[1.0693, 1.2911, 0.003]}
      >
        <mesh
          name="mesh_8_instance_0"
          castShadow
          receiveShadow
          geometry={nodes.mesh_8_instance_0.geometry}
          material={materials["Material.029"]}
        />
      </mesh>
      <mesh
        name="_l3_Veges_shelf_background002"
        castShadow
        receiveShadow
        geometry={nodes._l3_Veges_shelf_background002.geometry}
        material={materials["Material.007"]}
        position={[4.273, 1.2978, -4.0969]}
        scale={[1.0693, 1.2911, 0.003]}
      >
        <mesh
          name="mesh_8_instance_1"
          castShadow
          receiveShadow
          geometry={nodes.mesh_8_instance_1.geometry}
          material={materials["Material.029"]}
        />
      </mesh>
      <mesh
        name="_l3_Veges_shelf_background003"
        castShadow
        receiveShadow
        geometry={nodes._l3_Veges_shelf_background003.geometry}
        material={materials["Material.007"]}
        position={[1.9861, 1.2978, -4.0969]}
        scale={[1.0693, 1.2911, 0.003]}
      >
        <mesh
          name="mesh_8_instance_2"
          castShadow
          receiveShadow
          geometry={nodes.mesh_8_instance_2.geometry}
          material={materials["Material.029"]}
        />
      </mesh>
      <group
        name="_l3_Vegestable_shelf_1"
        position={[5.6435, 1.6622, 0.4124]}
        rotation={[0.6812, 0, 0]}
        scale={[0.4508, 1.0502, 0.307]}
      >
        <mesh
          name="mesh_9"
          castShadow
          receiveShadow
          geometry={nodes.mesh_9.geometry}
          material={materials["Material.038"]}
        />
        <mesh
          name="mesh_9_1"
          castShadow
          receiveShadow
          geometry={nodes.mesh_9_1.geometry}
          material={materials["Black Steel.002"]}
        />
        <mesh
          name="mesh_9_2"
          castShadow
          receiveShadow
          geometry={nodes.mesh_9_2.geometry}
          material={materials["wood.002"]}
        />
        <mesh
          name="mesh_9_3"
          castShadow
          receiveShadow
          geometry={nodes.mesh_9_3.geometry}
          material={materials["Grey.002"]}
        />
        <mesh
          name="mesh_9_4"
          castShadow
          receiveShadow
          geometry={nodes.mesh_9_4.geometry}
          material={materials["Black.002"]}
        />
        <mesh
          name="mesh_9_5"
          castShadow
          receiveShadow
          geometry={nodes.mesh_9_5.geometry}
          material={materials["Price09.001"]}
        />
        <mesh
          name="mesh_9_6"
          castShadow
          receiveShadow
          geometry={nodes.mesh_9_6.geometry}
          material={materials["black_plastic.002"]}
        />
      </group>
      <group
        name="_l3_Vegestable_shelf_2"
        position={[4.5157, 1.6622, 0.4124]}
        rotation={[0.6812, 0, 0]}
        scale={[0.4508, 1.0502, 0.307]}
      >
        <mesh
          name="mesh_10"
          castShadow
          receiveShadow
          geometry={nodes.mesh_10.geometry}
          material={materials["Material.038"]}
        />
        <mesh
          name="mesh_10_1"
          castShadow
          receiveShadow
          geometry={nodes.mesh_10_1.geometry}
          material={materials["Black Steel.002"]}
        />
        <mesh
          name="mesh_10_2"
          castShadow
          receiveShadow
          geometry={nodes.mesh_10_2.geometry}
          material={materials["wood.002"]}
        />
        <mesh
          name="mesh_10_3"
          castShadow
          receiveShadow
          geometry={nodes.mesh_10_3.geometry}
          material={materials["Grey.002"]}
        />
        <mesh
          name="mesh_10_4"
          castShadow
          receiveShadow
          geometry={nodes.mesh_10_4.geometry}
          material={materials["Black.002"]}
        />
        <mesh
          name="mesh_10_5"
          castShadow
          receiveShadow
          geometry={nodes.mesh_10_5.geometry}
          material={materials["Price09.001"]}
        />
        <mesh
          name="mesh_10_6"
          castShadow
          receiveShadow
          geometry={nodes.mesh_10_6.geometry}
          material={materials["black_plastic.002"]}
        />
      </group>
      <group
        name="_l3_Vegestable_shelf_3_&_4"
        position={[3.2695, 1.2411, 0.9028]}
        rotation={[0.6812, 0, 0]}
        scale={[0.4592, 1.0696, 0.3126]}
      >
        <mesh
          name="mesh_11"
          castShadow
          receiveShadow
          geometry={nodes.mesh_11.geometry}
          material={materials["Material.038"]}
        />
        <mesh
          name="mesh_11_1"
          castShadow
          receiveShadow
          geometry={nodes.mesh_11_1.geometry}
          material={materials["Black Steel.002"]}
        />
        <mesh
          name="mesh_11_2"
          castShadow
          receiveShadow
          geometry={nodes.mesh_11_2.geometry}
          material={materials["wood.002"]}
        />
        <mesh
          name="mesh_11_3"
          castShadow
          receiveShadow
          geometry={nodes.mesh_11_3.geometry}
          material={materials["Grey.002"]}
        />
        <mesh
          name="mesh_11_4"
          castShadow
          receiveShadow
          geometry={nodes.mesh_11_4.geometry}
          material={materials["Black.002"]}
        />
        <mesh
          name="mesh_11_5"
          castShadow
          receiveShadow
          geometry={nodes.mesh_11_5.geometry}
          material={materials.green_plastic}
        />
        <mesh
          name="mesh_11_6"
          castShadow
          receiveShadow
          geometry={nodes.mesh_11_6.geometry}
          material={materials["Price09.001"]}
        />
        <mesh
          name="mesh_11_7"
          castShadow
          receiveShadow
          geometry={nodes.mesh_11_7.geometry}
          material={materials.Price03}
        />
      </group>
      <group name="_l3_Vegestable_shelf_5&6" position={[-5.27, 0, 4.518]}>
        <mesh
          name="mesh_12"
          castShadow
          receiveShadow
          geometry={nodes.mesh_12.geometry}
          material={materials["Mis-vf_black"]}
        />
        <mesh
          name="mesh_12_1"
          castShadow
          receiveShadow
          geometry={nodes.mesh_12_1.geometry}
          material={materials.glass}
        />
        <mesh
          name="mesh_12_2"
          castShadow
          receiveShadow
          geometry={nodes.mesh_12_2.geometry}
          material={materials.wood_light}
        />
        <mesh
          name="mesh_12_3"
          castShadow
          receiveShadow
          geometry={nodes.mesh_12_3.geometry}
          material={materials.Chrome}
        />
        <mesh
          name="mesh_12_4"
          castShadow
          receiveShadow
          geometry={nodes.mesh_12_4.geometry}
          material={materials["Mis-vf_black-2"]}
        />
        <mesh
          name="mesh_12_5"
          castShadow
          receiveShadow
          geometry={nodes.mesh_12_5.geometry}
          material={materials["Material.037"]}
        />
        <mesh
          name="mesh_12_6"
          castShadow
          receiveShadow
          geometry={nodes.mesh_12_6.geometry}
          material={materials["Material.034"]}
        />
      </group>

      {/* Level 4 Components */}
      <mesh
        name="_l4_Veges_Shelf_Details"
        castShadow
        receiveShadow
        geometry={nodes._l4_Veges_Shelf_Details.geometry}
        material={materials["photo corn bits"]}
        position={[-3.3111, 0.0011, 4.0088]}
        rotation={[0, -1.5705, 0]}
        scale={1.1248}
      />
      <mesh
        name="_l4_Veges_Shelf_Details001"
        castShadow
        receiveShadow
        geometry={nodes._l4_Veges_Shelf_Details001.geometry}
        material={materials["pexels-photo-1313267"]}
        position={[-3.3111, 0.0011, 4.0088]}
        rotation={[0, -1.5705, 0]}
        scale={1.1248}
      />
      <mesh
        name="_l4_Veges_Shelf_Details002"
        castShadow
        receiveShadow
        geometry={nodes._l4_Veges_Shelf_Details002.geometry}
        material={materials.ee14c22e9800997a474536eadc93a1a8}
        position={[-3.3111, 0.0011, 4.0088]}
        rotation={[0, -1.5705, 0]}
        scale={1.1248}
      />
      <mesh
        name="_l4_Veges_Shelf_Details003"
        castShadow
        receiveShadow
        geometry={nodes._l4_Veges_Shelf_Details003.geometry}
        material={materials["cabbage-soup-diet-1"]}
        position={[-3.3111, 0.0011, 4.0088]}
        rotation={[0, -1.5705, 0]}
        scale={1.1248}
      />
      <mesh
        name="_l4_Veges_Shelf_Details004"
        castShadow
        receiveShadow
        geometry={nodes._l4_Veges_Shelf_Details004.geometry}
        material={materials["photo tomato skin"]}
        position={[-3.3111, 0.0011, 4.0088]}
        rotation={[0, -1.5705, 0]}
        scale={1.1248}
      />
      <mesh
        name="_l4_Veges_Shelf_Details005"
        castShadow
        receiveShadow
        geometry={nodes._l4_Veges_Shelf_Details005.geometry}
        material={materials["photo {3d75f229-7087-b44d-b407-5d2c7250592e}"]}
        position={[-3.3111, 0.0011, 4.0088]}
        rotation={[0, -1.5705, 0]}
        scale={1.1248}
      />
      <mesh
        name="_l4_Veges_Shelf_Details006"
        castShadow
        receiveShadow
        geometry={nodes._l4_Veges_Shelf_Details006.geometry}
        material={materials["storage dark green"]}
        position={[-3.3111, 0.0011, 4.0088]}
        rotation={[0, -1.5705, 0]}
        scale={1.1248}
      />
      <mesh
        name="_l4_Veges_Shelf_Details007"
        castShadow
        receiveShadow
        geometry={nodes._l4_Veges_Shelf_Details007.geometry}
        material={materials["storage dark red"]}
        position={[-3.3111, 0.0011, 4.0088]}
        rotation={[0, -1.5705, 0]}
        scale={1.1248}
      />
      <mesh
        name="_l4_Veges_Shelf_Details008"
        castShadow
        receiveShadow
        geometry={nodes._l4_Veges_Shelf_Details008.geometry}
        material={materials["[Color_L22]1"]}
        position={[-3.3111, 0.0011, 4.0088]}
        rotation={[0, -1.5705, 0]}
        scale={1.1248}
      />
      <mesh
        name="_l4_Veges_Shelf_Details009"
        castShadow
        receiveShadow
        geometry={nodes._l4_Veges_Shelf_Details009.geometry}
        material={materials["storage red"]}
        position={[-3.3111, 0.0011, 4.0088]}
        rotation={[0, -1.5705, 0]}
        scale={1.1248}
      />
      <mesh
        name="_l4_Veges_Shelf_Details010"
        castShadow
        receiveShadow
        geometry={nodes._l4_Veges_Shelf_Details010.geometry}
        material={materials["storage orange"]}
        position={[-3.3111, 0.0011, 4.0088]}
        rotation={[0, -1.5705, 0]}
        scale={1.1248}
      />
      <mesh
        name="_l4_Veges_Shelf_Details011"
        castShadow
        receiveShadow
        geometry={nodes._l4_Veges_Shelf_Details011.geometry}
        material={materials["cabbage-soup-diet-1"]}
        position={[-3.3111, 0.0011, 4.0088]}
        rotation={[0, -1.5705, 0]}
        scale={1.1248}
      />
    </group>
  );
}
