/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useMemo, useContext, createContext } from "react";
import { useGLTF, Merged } from "@react-three/drei";
import * as THREE from "three";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    [key: string]: THREE.Object3D;
  };
  materials: {
    [key: string]: THREE.Material;
  };
};

type InstanceProps = {
  name?: string;
  position?: [number, number, number];
  rotation?: [number, number, number];
  scale?: number | [number, number, number];
  children?: React.ReactNode;
};

type ContextType = {
  [key: string]: React.FC<InstanceProps>;
};

const context = createContext<ContextType | null>(null);

export function Instances({
  children,
  ...props
}: { children: React.ReactNode } & React.ComponentPropsWithoutRef<"group">) {
  const { nodes } = useGLTF("/tech-t.glb") as GLTFResult;
  const instances = useMemo(
    () => ({
      Mesh: nodes.mesh_0,
      Mesh1: nodes.mesh_0_1,
      Ldecor: nodes._l2_decor,
      Mesh2: nodes.mesh_2,
      Mesh3: nodes.mesh_2_1,
      Mesh4: nodes.mesh_3,
      Mesh5: nodes.mesh_3_1,
      Mesh6: nodes.mesh_4,
      Mesh7: nodes.mesh_4_1,
      Ltext: nodes._l2_text,
      Ltext1: nodes._l2_text001,
      Mesh8: nodes.mesh_7,
      Mesh9: nodes.mesh_7_1,
      Mesh10: nodes.mesh_7_2,
      Mesh11: nodes.mesh_7_3,
      Mesh12: nodes.mesh_7_4,
      Mesh13: nodes.mesh_7_5,
      Mesh14: nodes.mesh_7_6,
      Mesh15: nodes.mesh_8,
      Mesh16: nodes.mesh_8_1,
      Mesh17: nodes.mesh_9,
      Mesh18: nodes.mesh_9_1,
      Llaptop: nodes._l3_laptop001,
      Mesh19: nodes.mesh_11,
      Mesh20: nodes.mesh_11_1,
      Mesh21: nodes.mesh_11_2,
      Mesh22: nodes.mesh_11_3,
      Mesh23: nodes.mesh_11_4,
      Mesh24: nodes.mesh_11_5,
      Mesh25: nodes.mesh_11_6,
      Mesh26: nodes.mesh_11_7,
      Mesh27: nodes.mesh_11_8,
      Mesh28: nodes.mesh_11_9,
      Mesh29: nodes.mesh_11_10,
      Mesh30: nodes.mesh_11_11,
      Mesh31: nodes.mesh_12,
      Mesh32: nodes.mesh_12_1,
      Mesh33: nodes.mesh_13,
      Mesh34: nodes.mesh_13_1,
      Mesh35: nodes.mesh_14,
      Mesh36: nodes.mesh_14_1,
      Mesh37: nodes.mesh_14_2,
      Mesh38: nodes.mesh_14_3,
      Mesh39: nodes.mesh_14_4,
      Mesh40: nodes.mesh_14_5,
      Mesh41: nodes.mesh_14_6,
      Mesh42: nodes.mesh_14_7,
      Mesh43: nodes.mesh_14_8,
      Lbox: nodes._l3_box002,
      Lbox1: nodes._l3_box003,
      Lbox2: nodes._l3_box004,
      Lbox3: nodes._l3_box005,
      Lbox4: nodes._l3_box006,
      Lbox5: nodes._l3_box007,
      Mesh44: nodes.mesh_21,
      Mesh45: nodes.mesh_21_1,
      Mesh46: nodes.mesh_21_2,
      Mesh47: nodes.mesh_22,
      Mesh48: nodes.mesh_22_1,
      Mesh49: nodes.mesh_22_2,
      Mesh50: nodes.mesh_22_3,
      Mesh51: nodes.mesh_23,
      Mesh52: nodes.mesh_23_1,
      Mesh53: nodes.mesh_23_2,
      Lbox6: nodes._l3_box008,
      Lbox7: nodes._l3_box009,
      Lbox8: nodes._l3_box010,
      Mesh54: nodes.mesh_27,
      Mesh55: nodes.mesh_27_1,
      Mesh56: nodes.mesh_27_2,
      Mesh57: nodes.mesh_27_3,
      Mesh58: nodes.mesh_27_4,
      Lroomba: nodes._l4_roomba,
      Lfloor: nodes._l1_floor,
      Ltext2: nodes._l2_text002,
      Mesh59: nodes.mesh_31,
      Mesh60: nodes.mesh_31_1,
      Mesh61: nodes.mesh_31_2,
      Mesh62: nodes.mesh_32,
      Mesh63: nodes.mesh_32_1,
      Mesh64: nodes.mesh_32_2,
      Mesh65: nodes.mesh_32_3,
      Mesh66: nodes.mesh_32_4,
      Ldecor1: nodes._l2_decor001,
      Ldecor2: nodes._l2_decor002,
      Mesh67: nodes.mesh_35,
      Mesh68: nodes.mesh_35_1,
      Mesh69: nodes.mesh_35_2,
      Mesh70: nodes.mesh_35_3,
      Mesh71: nodes.mesh_35_4,
      Mesh72: nodes.mesh_36,
      Mesh73: nodes.mesh_36_1,
      LSpeaker: nodes._l3_Speaker,
    }),
    [nodes]
  );
  return (
    <Merged meshes={instances} {...props}>
      {(instances) => (
        <context.Provider value={instances} children={children} />
      )}
    </Merged>
  );
}

export function Model(props: React.ComponentPropsWithoutRef<"group">) {
  const instances = useContext(context);
  if (!instances) return null;

  return (
    <group {...props} dispose={null}>
      <group name="_l2_panel" position={[6.3, 0.4, 0.4]}>
        <instances.Mesh name="mesh_0" />
        <instances.Mesh1 name="mesh_0_1" />
      </group>
      <instances.Ldecor name="_l2_decor" position={[9.2, 2.1, -0.2]} />
      <group name="_l2_booth" position={[10.3, 0, -0.9]}>
        <instances.Mesh2 name="mesh_2" />
        <instances.Mesh3 name="mesh_2_1" />
      </group>
      <group name="_l2_panel001" position={[-0.8, 2.8, -2.3]}>
        <instances.Mesh4 name="mesh_3" />
        <instances.Mesh5 name="mesh_3_1" />
      </group>
      <group name="_l1_panel" position={[0, 8.4, -6.5]} scale={1.4}>
        <instances.Mesh6 name="mesh_4" />
        <instances.Mesh7 name="mesh_4_1" />
      </group>
      <instances.Ltext
        name="_l2_text"
        position={[-7, 4.3, -1.4]}
        rotation={[Math.PI / 2, 0, 0.1]}
        scale={0.7}
      />
      <instances.Ltext1
        name="_l2_text001"
        position={[-0.5, 4.5, -1.9]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.9}
      />
      <group name="_l3_tv" position={[-1.1, 1, 2.6]} rotation={[0, 1.2, 0]}>
        <instances.Mesh8 name="mesh_7" />
        <instances.Mesh9 name="mesh_7_1" />
        <instances.Mesh10 name="mesh_7_2" />
        <instances.Mesh11 name="mesh_7_3" />
        <instances.Mesh12 name="mesh_7_4" />
        <instances.Mesh13 name="mesh_7_5" />
        <instances.Mesh14 name="mesh_7_6" />
      </group>
      <group name="_l3_box" position={[-0.2, 0.5, 2.6]} rotation={[0, -1.6, 0]}>
        <instances.Mesh15 name="mesh_8" />
        <instances.Mesh16 name="mesh_8_1" />
      </group>
      <group
        name="_l3_box001"
        position={[-0.2, 0.7, 1.6]}
        rotation={[0, -1.6, 0]}
      >
        <instances.Mesh17 name="mesh_9" />
        <instances.Mesh18 name="mesh_9_1" />
      </group>
      <instances.Llaptop name="_l3_laptop001" position={[0.8, 1.3, 1.5]} />
      <group name="_l4_wm" position={[-1.3, 1.8, 0.6]} rotation={[0, -1.6, 0]}>
        <instances.Mesh19 name="mesh_11" />
        <instances.Mesh20 name="mesh_11_1" />
        <instances.Mesh21 name="mesh_11_2" />
        <instances.Mesh22 name="mesh_11_3" />
        <instances.Mesh23 name="mesh_11_4" />
        <instances.Mesh24 name="mesh_11_5" />
        <instances.Mesh25 name="mesh_11_6" />
        <instances.Mesh26 name="mesh_11_7" />
        <instances.Mesh27 name="mesh_11_8" />
        <instances.Mesh28 name="mesh_11_9" />
        <instances.Mesh29 name="mesh_11_10" />
        <instances.Mesh30 name="mesh_11_11" />
      </group>
      <group
        name="_l3_box014"
        position={[-1.3, 0.2, 0.5]}
        rotation={[0, 1.6, 0]}
      >
        <instances.Mesh31 name="mesh_12" />
        <instances.Mesh32 name="mesh_12_1" />
      </group>
      <group
        name="_l3_box015"
        position={[0.3, 0.2, 0.5]}
        rotation={[0, 1.6, 0]}
      >
        <instances.Mesh33 name="mesh_13" />
        <instances.Mesh34 name="mesh_13_1" />
      </group>
      <group name="_l4_fridge" position={[0.3, 1.1, 0.5]}>
        <instances.Mesh35 name="mesh_14" />
        <instances.Mesh36 name="mesh_14_1" />
        <instances.Mesh37 name="mesh_14_2" />
        <instances.Mesh38 name="mesh_14_3" />
        <instances.Mesh39 name="mesh_14_4" />
        <instances.Mesh40 name="mesh_14_5" />
        <instances.Mesh41 name="mesh_14_6" />
        <instances.Mesh42 name="mesh_14_7" />
        <instances.Mesh43 name="mesh_14_8" />
      </group>
      <instances.Lbox
        name="_l3_box002"
        position={[-4.6, 0.1, 2.5]}
        rotation={[0, 1.6, 0]}
      />
      <instances.Lbox1
        name="_l3_box003"
        position={[-6, 0.1, 2.5]}
        rotation={[0, 1.6, 0]}
      />
      <instances.Lbox2
        name="_l3_box004"
        position={[-4.6, 0.4, 2.5]}
        rotation={[0, 1.6, 0]}
      />
      <instances.Lbox3
        name="_l3_box005"
        position={[-6, 0.4, 2.5]}
        rotation={[0, 1.6, 0]}
      />
      <instances.Lbox4
        name="_l3_box006"
        position={[-7.3, 0.4, 2.5]}
        rotation={[0, 1.6, 0]}
      />
      <instances.Lbox5
        name="_l3_box007"
        position={[-7.3, 0.1, 2.5]}
        rotation={[0, 1.6, 0]}
      />
      <group
        name="_l3_electrolux"
        position={[-4.6, 1, 2.5]}
        rotation={[1, 0, 0]}
      >
        <instances.Mesh44 name="mesh_21" />
        <instances.Mesh45 name="mesh_21_1" />
        <instances.Mesh46 name="mesh_21_2" />
      </group>
      <group name="_l3_bep001" position={[-7.3, 1, 2.5]} rotation={[1, 0, 0]}>
        <instances.Mesh47 name="mesh_22" />
        <instances.Mesh48 name="mesh_22_1" />
        <instances.Mesh49 name="mesh_22_2" />
        <instances.Mesh50 name="mesh_22_3" />
      </group>
      <group name="_l3_bep" position={[-6, 1, 2.5]} rotation={[1, 0, 0]}>
        <instances.Mesh47 name="mesh_22" />
        <instances.Mesh48 name="mesh_22_1" />
        <instances.Mesh49 name="mesh_22_2" />
        <instances.Mesh50 name="mesh_22_3" />
      </group>
      <group name="_l4_rc" position={[-6, 1.4, 1.3]}>
        <instances.Mesh51 name="mesh_23" />
        <instances.Mesh52 name="mesh_23_1" />
        <instances.Mesh53 name="mesh_23_2" />
      </group>
      <instances.Lbox6
        name="_l3_box008"
        position={[-4.6, 0.8, 1.2]}
        rotation={[0, 1.6, 0]}
      />
      <instances.Lbox7
        name="_l3_box009"
        position={[-6, 0.8, 1.2]}
        rotation={[0, 1.6, 0]}
      />
      <instances.Lbox8
        name="_l3_box010"
        position={[-7.3, 0.8, 1.2]}
        rotation={[0, 1.6, 0]}
      />
      <group
        name="_l4_fryer"
        position={[-4.7, 1.6, 1.2]}
        rotation={[0, 0, Math.PI]}
      >
        <instances.Mesh54 name="mesh_27" />
        <instances.Mesh55 name="mesh_27_1" />
        <instances.Mesh56 name="mesh_27_2" />
        <instances.Mesh57 name="mesh_27_3" />
        <instances.Mesh58 name="mesh_27_4" />
      </group>
      <instances.Lroomba name="_l4_roomba" position={[-7.3, 1.5, 1.2]} />
      <instances.Lbox
        name="_l3_box011"
        position={[-4.6, 0.1, 1.2]}
        rotation={[0, 1.6, 0]}
      />
      <instances.Lbox1
        name="_l3_box012"
        position={[-6, 0.1, 1.2]}
        rotation={[0, 1.6, 0]}
      />
      <instances.Lbox5
        name="_l3_box013"
        position={[-7.3, 0.1, 1.2]}
        rotation={[0, 1.6, 0]}
      />
      <instances.Lfloor
        name="_l1_floor"
        position={[-0.5, 0, -0.2]}
        scale={[1, 1, 1.2]}
      />
      <instances.Ltext2
        name="_l2_text002"
        position={[6.4, 4.6, 4]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.7, 0.6, 0.7]}
      />
      <group
        name="_l1_Sign_Box002"
        position={[-8.1, 0.1, 4.8]}
        rotation={[0, -0.6, 0]}
        scale={1.1}
      >
        <instances.Mesh59 name="mesh_31" />
        <instances.Mesh60 name="mesh_31_1" />
        <instances.Mesh61 name="mesh_31_2" />
      </group>
      <group
        name="_l3_Headphone001"
        position={[7.5, 1.8, 2.9]}
        rotation={[-Math.PI / 2, Math.PI / 2, 0]}
        scale={0.2}
      >
        <instances.Mesh62 name="mesh_32" />
        <instances.Mesh63 name="mesh_32_1" />
        <instances.Mesh64 name="mesh_32_2" />
        <instances.Mesh65 name="mesh_32_3" />
        <instances.Mesh66 name="mesh_32_4" />
      </group>
      <instances.Lbox2
        name="_l3_box016"
        position={[7.5, 0.8, 2.7]}
        rotation={[0, 1.6, 0]}
        scale={[0.6, 2.4, 0.6]}
      />
      <instances.Lbox
        name="_l3_box017"
        position={[7.5, 0.1, 2.7]}
        rotation={[0, 1.6, 0]}
        scale={0.6}
      />
      <instances.Ldecor1 name="_l2_decor001" position={[-5.9, 3.5, -1.7]} />
      <instances.Ldecor2
        name="_l2_decor002"
        position={[2.8, 2.1, -1.7]}
        rotation={[0, -0.1, 0]}
      />
      <group
        name="_l4_Headphone"
        position={[7.5, 1.8, 2.6]}
        rotation={[-Math.PI / 2, Math.PI / 2, 0]}
        scale={0.2}
      >
        <instances.Mesh67 name="mesh_35" />
        <instances.Mesh68 name="mesh_35_1" />
        <instances.Mesh69 name="mesh_35_2" />
        <instances.Mesh70 name="mesh_35_3" />
        <instances.Mesh71 name="mesh_35_4" />
      </group>
      <instances.Lbox
        name="_l3_box018"
        position={[6.2, 0.1, 2.7]}
        rotation={[0, 1.6, 0]}
        scale={0.6}
      />
      <instances.Lbox2
        name="_l3_box019"
        position={[6.2, 0.8, 2.7]}
        rotation={[0, 1.6, 0]}
        scale={[0.6, 2.4, 0.6]}
      />
      <instances.Lbox2
        name="_l3_box020"
        position={[4.9, 0.8, 2.7]}
        rotation={[0, 1.6, 0]}
        scale={[0.6, 2.4, 0.6]}
      />
      <instances.Lbox
        name="_l3_box021"
        position={[4.9, 0.1, 2.7]}
        rotation={[0, 1.6, 0]}
        scale={0.6}
      />
      <group
        name="_l3_KeyboardBaru"
        position={[6.2, 1.5, 2.9]}
        rotation={[-2.4, 0, Math.PI]}
        scale={[0.3, 0, 0.1]}
      >
        <instances.Mesh72 name="mesh_36" />
        <instances.Mesh73 name="mesh_36_1" />
      </group>
      <group
        name="_l4_KeyboardBaru001"
        position={[6.2, 1.5, 2.6]}
        rotation={[-2.4, 0, Math.PI]}
        scale={[0.3, 0, 0.1]}
      >
        <instances.Mesh72 name="mesh_36" />
        <instances.Mesh73 name="mesh_36_1" />
      </group>
      <instances.LSpeaker
        name="_l3_Speaker"
        position={[4.8, 1.7, 2.7]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={0}
      />
    </group>
  );
}

useGLTF.preload("/tech-t.glb");
