/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useMemo, useContext, createContext } from "react";
import { useGLTF, Merged } from "@react-three/drei";
import * as THREE from "three";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    [key: string]: THREE.Object3D;
  };
  materials: {
    [key: string]: THREE.Material;
  };
};

type InstanceProps = {
  name?: string;
  position?: [number, number, number];
  rotation?: [number, number, number];
  scale?: number | [number, number, number];
};

type ContextType = {
  [key: string]: React.FC<InstanceProps>;
};

const context = createContext<ContextType | null>(null);

export function Instances({
  children,
  ...props
}: { children: React.ReactNode } & React.ComponentPropsWithoutRef<"group">) {
  const { nodes } = useGLTF("/wood-t.glb") as GLTFResult;
  const instances = useMemo(
    () => ({
      Mesh: nodes.mesh_0,
      Mesh1: nodes.mesh_0_1,
      Mesh2: nodes.mesh_0_2,
      Mesh3: nodes.mesh_0_3,
      Mesh4: nodes.mesh_0_4,
      Mesh5: nodes.mesh_0_5,
      Mesh6: nodes.mesh_0_6,
      Mesh7: nodes.mesh_0_7,
      Mesh8: nodes.mesh_0_8,
      Mesh9: nodes.mesh_0_9,
      Mesh10: nodes.mesh_0_10,
      Mesh11: nodes.mesh_0_11,
      Mesh12: nodes.mesh_1,
      Mesh13: nodes.mesh_1_1,
      Mesh14: nodes.mesh_1_2,
      Mesh15: nodes.mesh_2,
      Mesh16: nodes.mesh_2_1,
      Ltext: nodes._l3_text,
      Ltext1: nodes._l3_text001,
      Lvines: nodes._l2_vines,
      Mesh17: nodes.mesh_6,
      Mesh18: nodes.mesh_6_1,
      Lblock: nodes._l2_block,
      Mesh19: nodes.mesh_8,
      Mesh20: nodes.mesh_8_1,
      Mesh21: nodes.mesh_9,
      Mesh22: nodes.mesh_9_1,
      Mesh23: nodes.mesh_9_2,
      Mesh24: nodes.mesh_10,
      Mesh25: nodes.mesh_10_1,
      Mesh26: nodes.mesh_11,
      Mesh27: nodes.mesh_11_1,
      Mesh28: nodes.mesh_12,
      Mesh29: nodes.mesh_12_1,
      Mesh30: nodes.mesh_12_2,
      Mesh31: nodes.mesh_12_3,
      Mesh32: nodes.mesh_12_4,
      Mesh33: nodes.mesh_12_5,
      Mesh34: nodes.mesh_12_6,
      Mesh35: nodes.mesh_12_7,
      Mesh36: nodes.mesh_12_8,
      Ltable: nodes._l4_table,
      Mesh37: nodes.mesh_14,
      Mesh38: nodes.mesh_14_1,
      Ltable1: nodes._l4_table001,
      Mesh39: nodes.mesh_16,
      Mesh40: nodes.mesh_16_1,
      Mesh41: nodes.mesh_17,
      Mesh42: nodes.mesh_17_1,
      Mesh43: nodes.mesh_18,
      Mesh44: nodes.mesh_18_1,
      Ltext2: nodes._l3_text002,
    }),
    [nodes]
  );
  return (
    <Merged meshes={instances} {...props}>
      {(instances) => (
        <context.Provider value={instances} children={children} />
      )}
    </Merged>
  );
}

export function Model(props: React.ComponentPropsWithoutRef<"group">) {
  const instances = useContext(context);
  if (!instances) return null;

  return (
    <group {...props} dispose={null}>
      <group
        name="_l3_shelf003"
        position={[3.8, 0.2, -0.1]}
        rotation={[0, -1.6, 0]}
        scale={0.3}
      >
        <instances.Mesh name="mesh_0" />
        <instances.Mesh1 name="mesh_0_1" />
        <instances.Mesh2 name="mesh_0_2" />
        <instances.Mesh3 name="mesh_0_3" />
        <instances.Mesh4 name="mesh_0_4" />
        <instances.Mesh5 name="mesh_0_5" />
        <instances.Mesh6 name="mesh_0_6" />
        <instances.Mesh7 name="mesh_0_7" />
        <instances.Mesh8 name="mesh_0_8" />
        <instances.Mesh9 name="mesh_0_9" />
        <instances.Mesh10 name="mesh_0_10" />
        <instances.Mesh11 name="mesh_0_11" />
      </group>
      <group
        name="_l2_blocks"
        position={[-2.6, 4.7, -3.5]}
        rotation={[0, -1.6, 0]}
      >
        <instances.Mesh12 name="mesh_1" />
        <instances.Mesh13 name="mesh_1_1" />
        <instances.Mesh14 name="mesh_1_2" />
      </group>
      <group
        name="_l1_panel"
        position={[-2.7, 0.8, -5.4]}
        rotation={[-Math.PI, 0, -Math.PI]}
      >
        <instances.Mesh15 name="mesh_2" />
        <instances.Mesh16 name="mesh_2_1" />
      </group>
      <instances.Ltext
        name="_l3_text"
        position={[1.1, 3.6, -1.4]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.5}
      />
      <instances.Ltext1
        name="_l3_text001"
        position={[-5.9, 3.6, -1.5]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.5}
      />
      <instances.Lvines
        name="_l2_vines"
        position={[-2.8, 2.3, -2.2]}
        rotation={[Math.PI / 2, -Math.PI / 2, 0]}
      />
      <group
        name="_l1_floor001"
        position={[-2.7, 0.2, 1.5]}
        rotation={[0, -1.6, 0]}
      >
        <instances.Mesh17 name="mesh_6" />
        <instances.Mesh18 name="mesh_6_1" />
      </group>
      <instances.Lblock
        name="_l2_block"
        position={[-2.7, 0.2, 0.6]}
        rotation={[0, -1.6, 0]}
      />
      <group
        name="_l1_Sign_Box"
        position={[-8.4, 2.2, 5.5]}
        rotation={[0, -0.6, 0]}
        scale={[1, 2, 0.2]}
      >
        <instances.Mesh19 name="mesh_8" />
        <instances.Mesh20 name="mesh_8_1" />
      </group>
      <group
        name="_l3_shelf002"
        position={[1.4, 1.2, -1.3]}
        scale={[1.3, 1.1, 0]}
      >
        <instances.Mesh21 name="mesh_9" />
        <instances.Mesh22 name="mesh_9_1" />
        <instances.Mesh23 name="mesh_9_2" />
      </group>
      <group
        name="_l2_lights"
        position={[-2.9, 6.4, 2.4]}
        rotation={[0, -1.6, 0]}
        scale={1.1}
      >
        <instances.Mesh24 name="mesh_10" />
        <instances.Mesh25 name="mesh_10_1" />
      </group>
      <group
        name="_l4_shelf001"
        position={[-4.2, 0.2, 6.8]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
        scale={0}
      >
        <instances.Mesh26 name="mesh_11" />
        <instances.Mesh27 name="mesh_11_1" />
      </group>
      <group name="_l3_shelf" position={[-6.8, 0.2, -1.3]} scale={1.2}>
        <instances.Mesh28 name="mesh_12" />
        <instances.Mesh29 name="mesh_12_1" />
        <instances.Mesh30 name="mesh_12_2" />
        <instances.Mesh31 name="mesh_12_3" />
        <instances.Mesh32 name="mesh_12_4" />
        <instances.Mesh33 name="mesh_12_5" />
        <instances.Mesh34 name="mesh_12_6" />
        <instances.Mesh35 name="mesh_12_7" />
        <instances.Mesh36 name="mesh_12_8" />
      </group>
      <instances.Ltable name="_l4_table" position={[-5.1, 0.2, 3.8]} />
      <group name="_l4_sofa" position={[-3.1, 0.2, 3.7]}>
        <instances.Mesh37 name="mesh_14" />
        <instances.Mesh38 name="mesh_14_1" />
      </group>
      <instances.Ltable1 name="_l4_table001" position={[1, 0.2, 4.5]} />
      <group name="_l4_chair" position={[1, 0.2, 3.6]}>
        <instances.Mesh39 name="mesh_16" />
        <instances.Mesh40 name="mesh_16_1" />
      </group>
      <group
        name="_l4_chair001"
        position={[2.1, 0.2, 4.5]}
        rotation={[0, -Math.PI / 2, 0]}
      >
        <instances.Mesh39 name="mesh_16" />
        <instances.Mesh40 name="mesh_16_1" />
      </group>
      <group
        name="_l4_chair002"
        position={[-5.4, 0.2, 3.7]}
        rotation={[-Math.PI, 0.8, -Math.PI]}
      >
        <instances.Mesh41 name="mesh_17" />
        <instances.Mesh42 name="mesh_17_1" />
      </group>
      <group name="_l4_cabinet" position={[3.6, 0.2, 3]}>
        <instances.Mesh43 name="mesh_18" />
        <instances.Mesh44 name="mesh_18_1" />
      </group>
      <instances.Ltext2
        name="_l3_text002"
        position={[-2.6, 1.2, 6]}
        scale={[0.8, 1.6, 0.1]}
      />
      <group name="_l3_shelf004" position={[-6.8, 0.2, 0.3]} scale={1.2}>
        <instances.Mesh28 name="mesh_12" />
        <instances.Mesh29 name="mesh_12_1" />
        <instances.Mesh30 name="mesh_12_2" />
        <instances.Mesh31 name="mesh_12_3" />
        <instances.Mesh32 name="mesh_12_4" />
        <instances.Mesh33 name="mesh_12_5" />
        <instances.Mesh34 name="mesh_12_6" />
        <instances.Mesh35 name="mesh_12_7" />
        <instances.Mesh36 name="mesh_12_8" />
      </group>
      <instances.Lblock
        name="_l2_block001"
        position={[-16.8, 0.2, 0.6]}
        rotation={[0, -1.6, 0]}
      />
    </group>
  );
}

useGLTF.preload("/wood-t.glb");
