/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef } from 'react'
import { Detailed, useGLTF } from '@react-three/drei'
import { Mesh, Texture } from 'three'




const LOD1 = ({nodes, materials})=>{
  return (
    <group  >
      <mesh
        castShadow
        receiveShadow
        geometry={nodes._l1_Backdrop_box.geometry}
        material={materials['Material.012']}
        position={[-0.269, 6.143, -5.377]}
        scale={[1.429, 1.345, 0.414]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes._l1_Floor.geometry}
        material={materials['Material.008']}
        position={[-0.322, -0.034, 0]}
        rotation={[0, -1.571, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes._l1_Main_Backdrop.geometry}
        material={materials['LCD06.002']}
        position={[-0.362, 5.169, -4.971]}
        scale={[0.738, 0.599, 0.322]}
      />
      <group
        position={[-6.656, -0.009, 3.949]}
        rotation={[0, -0.611, 0]}
        scale={[1.003, 2.002, 0.19]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l1_Sign_Box_001_1.geometry}
          material={materials.Material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l1_Sign_Box_001_2.geometry}
          material={materials['material23.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l1_Sign_Box_001_3.geometry}
          material={materials['Material.010']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l1_Sign_Box_001_4.geometry}
          material={materials['material0.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l1_Sign_Box_001_5.geometry}
          material={materials['material1.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l1_Sign_Box_001_6.geometry}
          material={materials['material2.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l1_Sign_Box_001_7.geometry}
          material={materials['material3.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l1_Sign_Box_001_8.geometry}
          material={materials['material4.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l1_Sign_Box_001_9.geometry}
          material={materials['material5.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l1_Sign_Box_001_10.geometry}
          material={materials['material6.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l1_Sign_Box_001_11.geometry}
          material={materials['material7.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l1_Sign_Box_001_12.geometry}
          material={materials['material8.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l1_Sign_Box_001_13.geometry}
          material={materials['material9.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l1_Sign_Box_001_14.geometry}
          material={materials['material10.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l1_Sign_Box_001_15.geometry}
          material={materials['material11.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l1_Sign_Box_001_16.geometry}
          material={materials['material12.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l1_Sign_Box_001_17.geometry}
          material={materials['material13.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l1_Sign_Box_001_18.geometry}
          material={materials['material14.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l1_Sign_Box_001_19.geometry}
          material={materials['material15.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l1_Sign_Box_001_20.geometry}
          material={materials['material16.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l1_Sign_Box_001_21.geometry}
          material={materials['material17.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l1_Sign_Box_001_22.geometry}
          material={materials['material18.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l1_Sign_Box_001_23.geometry}
          material={materials['material19.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l1_Sign_Box_001_24.geometry}
          material={materials['material20.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l1_Sign_Box_001_25.geometry}
          material={materials['material21.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l1_Sign_Box_001_26.geometry}
          material={materials['material22.001']}
        />
      </group>
    </group>
  )
}

export function LOD2({materials,nodes}) {
  return (
    <group >
      <mesh
        castShadow
        receiveShadow
        geometry={nodes._l2_Decor_Structure.geometry}
        material={materials['Material.011']}
        position={[-5.429, 1.703, -1.07]}
        rotation={[0, 1.571, 0]}
      />
      <group position={[-0.204, 1.224, -2.958]} scale={[3.36, 1.255, 0.006]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l2_Materials_shelf_1.geometry}
          material={materials['Material.004']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l2_Materials_shelf_2.geometry}
          material={materials['Inst_Rack_01.002']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l2_Materials_shelf_3.geometry}
          material={materials.adskMatPhysicalMaterial_12}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes._l2_BP_Banner_left_1.geometry}
        material={materials['Inst_Rack_01.001']}
        position={[-5.118, 0.954, 0.214]}
        rotation={[0, 0.23, 0]}
        scale={[1.129, 1.067, 0.934]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes._l2_BP_Banner_left_2.geometry}
        material={materials['Inst_Rack_01.004']}
        position={[4.579, 0.954, 0.183]}
        rotation={[0, -0.238, 0]}
        scale={[1.129, 1.067, 0.934]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes._l2_BP_Visual_Banner_left_1.geometry}
        material={materials['Material.002']}
        position={[-5.118, 0.954, 0.214]}
        rotation={[0, 0.23, 0]}
        scale={[1.129, 1.067, 0.934]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes._l2_BP_Visual_Banner_left_2.geometry}
        material={materials['Material.001']}
        position={[4.579, 0.954, 0.183]}
        rotation={[0, -0.238, 0]}
        scale={[1.129, 1.067, 0.934]}
      />
    </group>
  )
}

function LOD3({nodes,materials}){
  return (
    <group >
      <group
        position={[-4.823, 1.601, 2.115]}
        rotation={[-Math.PI / 2, 0, 1.76]}
        scale={[0.002, 0.001, 0.001]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l3_bagest_1.geometry}
          material={materials['Green Lizerd']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l3_bagest_2.geometry}
          material={materials['Fast Gold']}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes._l3_Shoes_box.geometry}
        material={materials.adskMatPhysicalMaterial_1}
        position={[-5.819, 0.554, 2.436]}
        rotation={[-Math.PI / 2, 0, 0.171]}
        scale={[0.002, 0.001, 0.001]}
      />
      <group
        position={[-6.109, 0.248, 3.491]}
        rotation={[-1.383, 0.02, -1.118]}
        scale={[0.043, 0.043, 0.052]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l3_Shose_1.geometry}
          material={materials['adskMatPhysicalMaterial_10.002']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l3_Shose_2.geometry}
          material={materials['adskMatPhysicalMaterial_6.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l3_Shose_3.geometry}
          material={materials['adskMatPhysicalMaterial_9.001']}
        />
      </group>
      <group
        position={[-3.461, 2.081, 0.825]}
        rotation={[-Math.PI / 2, 0, 1.916]}
        scale={[0.002, 0.001, 0.001]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l3_Women_mannequin_1.geometry}
          material={materials.adskMatPhysicalMaterial_14}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l3_Women_mannequin_2.geometry}
          material={materials.adskMatPhysicalMaterial_12}
        />
      </group>
      <group
        position={[-3.681, 1.067, 2.179]}
        rotation={[-Math.PI / 2, 0, 0.688]}
        scale={[0.002, 0.001, 0.001]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l3_Women_mannequin001_1.geometry}
          material={materials.adskMatPhysicalMaterial_7}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l3_Women_mannequin001_2.geometry}
          material={materials['adskMatPhysicalMaterial_10.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l3_Women_mannequin001_3.geometry}
          material={materials.adskMatPhysicalMaterial_6}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes._l3_Women_mannequin_box.geometry}
        material={materials['adskMatPhysicalMaterial_1.001']}
        position={[-3.494, 0.169, 0.903]}
        rotation={[-Math.PI / 2, 0, 0.291]}
        scale={[0.002, 0.001, 0.001]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes._l3_Women_mannequin_box001.geometry}
        material={materials.adskMatPhysicalMaterial_1}
        position={[-4.771, 0.687, 2.214]}
        rotation={[-Math.PI / 2, 0, 1.76]}
        scale={[0.002, 0.001, 0.001]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes._l3_Women_mannequin_box002.geometry}
        material={materials.adskMatPhysicalMaterial_1}
        position={[-3.736, 0.28, 1.831]}
        rotation={[-Math.PI / 2, 0, -0.349]}
        scale={[0.002, 0.001, 0.001]}
      />
    </group>
  )
}

export default function DetmayModel(props) {
  const [level1,level2 , level3] = useGLTF(['/V7/DETMAY_LOD/detmay_L1.glb','/V7/DETMAY_LOD/detmay_L2.glb','/V7/DETMAY_LOD/detmay_L3.glb'])

  return <group {...props}>
    <Detailed
        distances={[10, 35, 40]}>
     <group>
          <LOD1 {...level1} />
          <LOD2 {...level2} />
          <LOD3 {...level3} />
          {/* <LOD4s {...level4} /> */}
        </group>
        <group>
          <LOD1 {...level1} />
          <LOD2 {...level2} />
          <LOD3 {...level3} />
        </group>
        <group>
          <LOD1 {...level1} />
          <LOD2 {...level2} />
        </group>
    </Detailed>
  </group>
}

useGLTF.preload('/V7/DETMAY_LOD/detmay_L1.glb ')
useGLTF.preload('/V7/DETMAY_LOD/detmay_L2.glb ')
useGLTF.preload('/V7/DETMAY_LOD/detmay_L3.glb ')

