/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef } from 'react'
import { Detailed, useGLTF } from '@react-three/drei'
import { Mesh, Texture } from 'three'




const LOD1 = ({nodes, materials})=>{
  return (
    <group  >
      <mesh
        castShadow
        receiveShadow
        geometry={nodes._l1_Backdrop_box.geometry}
        material={materials['Material.012']}
        position={[-0.269, 6.143, -5.377]}
        scale={[1.429, 1.345, 0.414]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes._l1_Floor.geometry}
        material={materials['Material.008']}
        position={[-0.322, -0.034, 0]}
        rotation={[0, -1.571, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes._l1_Main_Backdrop.geometry}
        material={materials['LCD06.002']}
        position={[-0.362, 5.169, -4.971]}
        scale={[0.738, 0.599, 0.322]}
      />
      <group
        position={[-6.656, -0.009, 3.949]}
        rotation={[0, -0.611, 0]}
        scale={[1.003, 2.002, 0.19]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l1_Sign_Box_001_1.geometry}
          material={materials.Material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l1_Sign_Box_001_2.geometry}
          material={materials['material23.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l1_Sign_Box_001_3.geometry}
          material={materials['Material.010']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l1_Sign_Box_001_4.geometry}
          material={materials['material0.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l1_Sign_Box_001_5.geometry}
          material={materials['material1.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l1_Sign_Box_001_6.geometry}
          material={materials['material2.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l1_Sign_Box_001_7.geometry}
          material={materials['material3.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l1_Sign_Box_001_8.geometry}
          material={materials['material4.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l1_Sign_Box_001_9.geometry}
          material={materials['material5.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l1_Sign_Box_001_10.geometry}
          material={materials['material6.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l1_Sign_Box_001_11.geometry}
          material={materials['material7.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l1_Sign_Box_001_12.geometry}
          material={materials['material8.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l1_Sign_Box_001_13.geometry}
          material={materials['material9.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l1_Sign_Box_001_14.geometry}
          material={materials['material10.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l1_Sign_Box_001_15.geometry}
          material={materials['material11.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l1_Sign_Box_001_16.geometry}
          material={materials['material12.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l1_Sign_Box_001_17.geometry}
          material={materials['material13.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l1_Sign_Box_001_18.geometry}
          material={materials['material14.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l1_Sign_Box_001_19.geometry}
          material={materials['material15.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l1_Sign_Box_001_20.geometry}
          material={materials['material16.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l1_Sign_Box_001_21.geometry}
          material={materials['material17.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l1_Sign_Box_001_22.geometry}
          material={materials['material18.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l1_Sign_Box_001_23.geometry}
          material={materials['material19.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l1_Sign_Box_001_24.geometry}
          material={materials['material20.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l1_Sign_Box_001_25.geometry}
          material={materials['material21.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l1_Sign_Box_001_26.geometry}
          material={materials['material22.001']}
        />
      </group>
    </group>
  )
}

export function LOD2({materials,nodes}) {
  return (
    <group >
      <mesh
        castShadow
        receiveShadow
        geometry={nodes._l2_Decor_Structure.geometry}
        material={materials['Material.011']}
        position={[-5.429, 1.703, -1.07]}
        rotation={[0, 1.571, 0]}
      />
      <group position={[-0.204, 1.224, -2.958]} scale={[3.36, 1.255, 0.006]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l2_Materials_shelf_1.geometry}
          material={materials['Material.004']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l2_Materials_shelf_2.geometry}
          material={materials['Inst_Rack_01.002']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l2_Materials_shelf_3.geometry}
          material={materials.adskMatPhysicalMaterial_12}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes._l2_BP_Banner_left_1.geometry}
        material={materials['Inst_Rack_01.001']}
        position={[-5.118, 0.954, 0.214]}
        rotation={[0, 0.23, 0]}
        scale={[1.129, 1.067, 0.934]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes._l2_BP_Banner_left_2.geometry}
        material={materials['Inst_Rack_01.004']}
        position={[4.579, 0.954, 0.183]}
        rotation={[0, -0.238, 0]}
        scale={[1.129, 1.067, 0.934]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes._l2_BP_Visual_Banner_left_1.geometry}
        material={materials['Material.002']}
        position={[-5.118, 0.954, 0.214]}
        rotation={[0, 0.23, 0]}
        scale={[1.129, 1.067, 0.934]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes._l2_BP_Visual_Banner_left_2.geometry}
        material={materials['Material.001']}
        position={[4.579, 0.954, 0.183]}
        rotation={[0, -0.238, 0]}
        scale={[1.129, 1.067, 0.934]}
      />
    </group>
  )
}

function LOD4({nodes,materials}){
  return (
    <group >
      <mesh
        castShadow
        receiveShadow
        geometry={nodes._l4_Man_mannequin002.geometry}
        material={materials.Aluminum}
        position={[3.256, -0.013, 1.808]}
        rotation={[-0.014, -1.321, 0.017]}
        scale={0.158}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes._l4_Man_mannequin001.geometry}
        material={materials.Plastic_black_matte123123123123}
        position={[3.256, -0.013, 1.808]}
        rotation={[-0.014, -1.321, 0.017]}
        scale={0.158}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes._l4_Man_mannequin.geometry}
        material={materials['Material.014']}
        position={[3.256, -0.013, 1.808]}
        rotation={[-0.014, -1.321, 0.017]}
        scale={0.158}
      />
    </group>
  )
}

export default function DetmayModel(props) {
  const [level1,level2 , level4] = useGLTF(['/V7/DETMAY_LOD/detmay_L1.glb','/V7/DETMAY_LOD/detmay_L2.glb','/V7/DETMAY_LOD/detmay_L4.glb'])

  return <group {...props}>
    <Detailed
         distances={[0, 11, 15, 25 ]}>
     <group>
          <LOD1 {...level1} />
          <LOD2 {...level2} />
          {/* <LOD3 {...level3} /> */}
          <LOD4 {...level4} />
        </group>
        <group>
          <LOD1 {...level1} />
          <LOD2 {...level2} />
          {/* <LOD3 {...level3} /> */}
        </group>
        <group>
          <LOD1 {...level1} />
          <LOD2 {...level2} />
        </group>
        <LOD1 {...level1} />
        {/* <group></group> */}
    </Detailed>
  </group>
}

// useGLTF.preload('/V7/DETMAY_LOD/detmay_L1.glb ')
