/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\food.gltf --shadows --types 
*/

import * as THREE from "three";
import React, { JSX } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    _l3_Meat_shelf_background_1: THREE.Mesh;
    _l3_Meat_shelf_background_2: THREE.Mesh;
    _l3_Meat_shelf_background001_1: THREE.Mesh;
    _l3_Meat_shelf_background001_2: THREE.Mesh;
    _l3_Meat_shelf_background002_1: THREE.Mesh;
    _l3_Meat_shelf_background002_2: THREE.Mesh;
    _l3_Meat_shelf_background003_1: THREE.Mesh;
    _l3_Meat_shelf_background003_2: THREE.Mesh;
    _l3_Veges_Details_1: THREE.Mesh;
    _l3_Veges_Details_2: THREE.Mesh;
    _l3_Veges_Details_3: THREE.Mesh;
    _l3_Veges_Details_4: THREE.Mesh;
    _l3_Veges_Details002: THREE.Mesh;
    _l3_Veges_shelf_background_1: THREE.Mesh;
    _l3_Veges_shelf_background_2: THREE.Mesh;
    _l3_Veges_shelf_background001_1: THREE.Mesh;
    _l3_Veges_shelf_background001_2: THREE.Mesh;
    _l3_Veges_shelf_background002_1: THREE.Mesh;
    _l3_Veges_shelf_background002_2: THREE.Mesh;
    _l3_Veges_shelf_background003_1: THREE.Mesh;
    _l3_Veges_shelf_background003_2: THREE.Mesh;
    _l3_Vegestable_shelf_1_1: THREE.Mesh;
    _l3_Vegestable_shelf_1_2: THREE.Mesh;
    _l3_Vegestable_shelf_1_3: THREE.Mesh;
    _l3_Vegestable_shelf_1_4: THREE.Mesh;
    _l3_Vegestable_shelf_1_5: THREE.Mesh;
    _l3_Vegestable_shelf_1_6: THREE.Mesh;
    _l3_Vegestable_shelf_1_7: THREE.Mesh;
    _l3_Vegestable_shelf_1_8: THREE.Mesh;
    _l3_Vegestable_shelf_1_9: THREE.Mesh;
    _l3_Vegestable_shelf_1_10: THREE.Mesh;
    _l3_Vegestable_shelf_1_11: THREE.Mesh;
    _l3_Vegestable_shelf_2_1: THREE.Mesh;
    _l3_Vegestable_shelf_2_2: THREE.Mesh;
    _l3_Vegestable_shelf_2_3: THREE.Mesh;
    _l3_Vegestable_shelf_2_4: THREE.Mesh;
    _l3_Vegestable_shelf_2_5: THREE.Mesh;
    _l3_Vegestable_shelf_2_6: THREE.Mesh;
    _l3_Vegestable_shelf_2_7: THREE.Mesh;
    _l3_Vegestable_shelf_2_8: THREE.Mesh;
    _l3_Vegestable_shelf_2_9: THREE.Mesh;
    _l3_Vegestable_shelf_2_10: THREE.Mesh;
    _l3_Vegestable_shelf_2_11: THREE.Mesh;
    ["_l3_Vegestable_shelf_3_&_4_1"]: THREE.Mesh;
    ["_l3_Vegestable_shelf_3_&_4_2"]: THREE.Mesh;
    ["_l3_Vegestable_shelf_3_&_4_3"]: THREE.Mesh;
    ["_l3_Vegestable_shelf_3_&_4_4"]: THREE.Mesh;
    ["_l3_Vegestable_shelf_3_&_4_5"]: THREE.Mesh;
    ["_l3_Vegestable_shelf_3_&_4_6"]: THREE.Mesh;
    ["_l3_Vegestable_shelf_3_&_4_7"]: THREE.Mesh;
    ["_l3_Vegestable_shelf_3_&_4_8"]: THREE.Mesh;
    ["_l3_Vegestable_shelf_3_&_4_9"]: THREE.Mesh;
    ["_l3_Vegestable_shelf_3_&_4_10"]: THREE.Mesh;
    ["_l3_Vegestable_shelf_3_&_4_11"]: THREE.Mesh;
    ["_l3_Vegestable_shelf_3_&_4_12"]: THREE.Mesh;
    ["_l3_Vegestable_shelf_3_&_4_13"]: THREE.Mesh;
    ["_l3_Vegestable_shelf_3_&_4_14"]: THREE.Mesh;
    ["_l3_Vegestable_shelf_3_&_4_15"]: THREE.Mesh;
    ["_l3_Vegestable_shelf_3_&_4_16"]: THREE.Mesh;
    ["_l3_Vegestable_shelf_3_&_4_17"]: THREE.Mesh;
    ["_l3_Vegestable_shelf_5&6_1"]: THREE.Mesh;
    ["_l3_Vegestable_shelf_5&6_2"]: THREE.Mesh;
    ["_l3_Vegestable_shelf_5&6_3"]: THREE.Mesh;
    ["_l3_Vegestable_shelf_5&6_4"]: THREE.Mesh;
    ["_l3_Vegestable_shelf_5&6_5"]: THREE.Mesh;
    ["_l3_Vegestable_shelf_5&6_6"]: THREE.Mesh;
    ["_l3_Vegestable_shelf_5&6_7"]: THREE.Mesh;
    _l4_Veges_Shelf_Details: THREE.Mesh;
    _l4_Veges_Shelf_Details001: THREE.Mesh;
    _l4_Veges_Shelf_Details002: THREE.Mesh;
    _l4_Veges_Shelf_Details003: THREE.Mesh;
    _l4_Veges_Shelf_Details004: THREE.Mesh;
    _l4_Veges_Shelf_Details005: THREE.Mesh;
    _l4_Veges_Shelf_Details006: THREE.Mesh;
    _l4_Veges_Shelf_Details007: THREE.Mesh;
    _l4_Veges_Shelf_Details008: THREE.Mesh;
    _l4_Veges_Shelf_Details009: THREE.Mesh;
    _l4_Veges_Shelf_Details010: THREE.Mesh;
    _l4_Veges_Shelf_Details011: THREE.Mesh;
    _l1_Backdrop_box: THREE.Mesh;
    _l1_Floor: THREE.Mesh;
    _l1_Main_Backdrop: THREE.Mesh;
    _l2_bamboo: THREE.Mesh;
    _l2_Circle_Banners: THREE.Mesh;
    _l2_Visual_led_left_1: THREE.Mesh;
    _l2_Visual_led_left_2: THREE.Mesh;
    _l2_Visual_led_left_3: THREE.Mesh;
    _l2_Visual_led_right_1: THREE.Mesh;
    _l2_Visual_led_right_2: THREE.Mesh;
    _l2_Visual_led_right_3: THREE.Mesh;
    _l1_Sign_Box002_1: THREE.Mesh;
    _l1_Sign_Box002_2: THREE.Mesh;
    _l1_Sign_Box002_3: THREE.Mesh;
    _l1_Sign_Box002_4: THREE.Mesh;
    _l1_Sign_Box002_5: THREE.Mesh;
    _l1_Sign_Box002_6: THREE.Mesh;
    _l1_Sign_Box002_7: THREE.Mesh;
    _l1_Sign_Box002_8: THREE.Mesh;
    _l1_Sign_Box002_9: THREE.Mesh;
    _l1_Sign_Box002_10: THREE.Mesh;
    _l1_Sign_Box002_11: THREE.Mesh;
    _l1_Sign_Box002_12: THREE.Mesh;
    _l1_Sign_Box002_13: THREE.Mesh;
    _l1_Sign_Box002_14: THREE.Mesh;
    _l1_Sign_Box002_15: THREE.Mesh;
    _l1_Sign_Box002_16: THREE.Mesh;
    _l1_Sign_Box002_17: THREE.Mesh;
    _l1_Sign_Box002_18: THREE.Mesh;
    _l1_Sign_Box002_19: THREE.Mesh;
    _l1_Sign_Box002_20: THREE.Mesh;
    _l1_Sign_Box002_21: THREE.Mesh;
    _l1_Sign_Box002_22: THREE.Mesh;
    _l1_Sign_Box002_23: THREE.Mesh;
    _l1_Sign_Box002_24: THREE.Mesh;
    _l1_Sign_Box002_25: THREE.Mesh;
    _l1_Sign_Box002_26: THREE.Mesh;
    _l1_Sign_Box002_27: THREE.Mesh;
    _l1_Sign_Box002_28: THREE.Mesh;
    _l1_Sign_Box002_29: THREE.Mesh;
  };
  materials: {
    ["Material.006"]: THREE.MeshStandardMaterial;
    ["Material.007"]: THREE.MeshStandardMaterial;
    ["Material.005"]: THREE.MeshStandardMaterial;
    Material: THREE.MeshStandardMaterial;
    ["Material.013"]: THREE.MeshStandardMaterial;
    ["Material.014"]: THREE.MeshStandardMaterial;
    ["Material.015"]: THREE.MeshStandardMaterial;
    ["Material.016"]: THREE.MeshStandardMaterial;
    Plywood_C_50cm: THREE.MeshStandardMaterial;
    ["Material.002"]: THREE.MeshStandardMaterial;
    Iron_Blurry_5cm: THREE.MeshStandardMaterial;
    ["MIROR 2"]: THREE.MeshStandardMaterial;
    ["storage basket"]: THREE.MeshStandardMaterial;
    ["Material.027"]: THREE.MeshStandardMaterial;
    ["Material.026"]: THREE.MeshStandardMaterial;
    ["Material.028"]: THREE.MeshStandardMaterial;
    ["Material.029"]: THREE.MeshStandardMaterial;
    ["Material.030"]: THREE.MeshStandardMaterial;
    ["Material.031"]: THREE.MeshStandardMaterial;
    ["Material.032"]: THREE.MeshStandardMaterial;
    ["Material.033"]: THREE.MeshStandardMaterial;
    ["Material.038"]: THREE.MeshStandardMaterial;
    ["Black Steel.002"]: THREE.MeshStandardMaterial;
    ["wood.002"]: THREE.MeshStandardMaterial;
    ["Grey.002"]: THREE.MeshStandardMaterial;
    ["Black.002"]: THREE.MeshStandardMaterial;
    ["Material.039"]: THREE.MeshStandardMaterial;
    ["Material.040"]: THREE.MeshStandardMaterial;
    ["Price09.001"]: THREE.MeshStandardMaterial;
    ["Price07.001"]: THREE.MeshStandardMaterial;
    ["Price08.001"]: THREE.MeshStandardMaterial;
    ["black_plastic.002"]: THREE.MeshStandardMaterial;
    ["Material.025"]: THREE.MeshStandardMaterial;
    ["Black Steel"]: THREE.MeshStandardMaterial;
    wood: THREE.MeshStandardMaterial;
    Grey: THREE.MeshStandardMaterial;
    Black: THREE.MeshStandardMaterial;
    ["Material.023"]: THREE.MeshStandardMaterial;
    ["Material.024"]: THREE.MeshStandardMaterial;
    Price09: THREE.MeshStandardMaterial;
    Price07: THREE.MeshStandardMaterial;
    Price08: THREE.MeshStandardMaterial;
    black_plastic: THREE.MeshStandardMaterial;
    ["Material.020"]: THREE.MeshStandardMaterial;
    green_plastic: THREE.MeshStandardMaterial;
    Price06: THREE.MeshStandardMaterial;
    ["Material.017"]: THREE.MeshStandardMaterial;
    ["Material.018"]: THREE.MeshStandardMaterial;
    ["Material.019"]: THREE.MeshStandardMaterial;
    ["Material.021"]: THREE.MeshStandardMaterial;
    ["Material.022"]: THREE.MeshStandardMaterial;
    Price05: THREE.MeshStandardMaterial;
    Price01: THREE.MeshStandardMaterial;
    Price02: THREE.MeshStandardMaterial;
    Price04: THREE.MeshStandardMaterial;
    Price03: THREE.MeshStandardMaterial;
    ["Mis-vf_black"]: THREE.MeshStandardMaterial;
    glass: THREE.MeshStandardMaterial;
    wood_light: THREE.MeshStandardMaterial;
    Chrome: THREE.MeshStandardMaterial;
    ["Mis-vf_black-2"]: THREE.MeshStandardMaterial;
    ["Material.037"]: THREE.MeshStandardMaterial;
    ["Material.034"]: THREE.MeshStandardMaterial;
    ["photo corn bits"]: THREE.MeshStandardMaterial;
    ["pexels-photo-1313267"]: THREE.MeshStandardMaterial;
    ee14c22e9800997a474536eadc93a1a8: THREE.MeshStandardMaterial;
    ["cabbage-soup-diet-1"]: THREE.MeshStandardMaterial;
    ["photo tomato skin"]: THREE.MeshStandardMaterial;
    ["photo {3d75f229-7087-b44d-b407-5d2c7250592e}"]: THREE.MeshStandardMaterial;
    ["storage dark green"]: THREE.MeshStandardMaterial;
    ["storage dark red"]: THREE.MeshStandardMaterial;
    ["[Color_L22]1"]: THREE.MeshStandardMaterial;
    ["storage red"]: THREE.MeshStandardMaterial;
    ["storage orange"]: THREE.MeshStandardMaterial;
    ["cabbage-soup-diet-1.001"]: THREE.MeshStandardMaterial;
    ["LCD06.002"]: THREE.MeshStandardMaterial;
    ["Material.041"]: THREE.MeshStandardMaterial;
    ["Ash Wood"]: THREE.MeshStandardMaterial;
    bamboo: THREE.MeshStandardMaterial;
    S1: THREE.MeshStandardMaterial;
    ["Material.043"]: THREE.MeshStandardMaterial;
    ["Bamboo.002"]: THREE.MeshStandardMaterial;
    ["white.001"]: THREE.MeshStandardMaterial;
    Bamboo: THREE.MeshStandardMaterial;
    white: THREE.MeshStandardMaterial;
    ["Material.042"]: THREE.MeshStandardMaterial;
    ["Material.001"]: THREE.MeshStandardMaterial;
    ["Material.010"]: THREE.MeshStandardMaterial;
    ["material0.001"]: THREE.MeshStandardMaterial;
    ["material1.001"]: THREE.MeshStandardMaterial;
    ["material2.001"]: THREE.MeshStandardMaterial;
    ["material3.001"]: THREE.MeshStandardMaterial;
    ["material4.001"]: THREE.MeshStandardMaterial;
    ["material5.001"]: THREE.MeshStandardMaterial;
    ["material6.001"]: THREE.MeshStandardMaterial;
    ["material7.001"]: THREE.MeshStandardMaterial;
    ["material8.001"]: THREE.MeshStandardMaterial;
    ["material9.001"]: THREE.MeshStandardMaterial;
    ["material10.001"]: THREE.MeshStandardMaterial;
    ["material11.001"]: THREE.MeshStandardMaterial;
    ["material12.001"]: THREE.MeshStandardMaterial;
    ["material13.001"]: THREE.MeshStandardMaterial;
    ["material14.001"]: THREE.MeshStandardMaterial;
    ["material15.001"]: THREE.MeshStandardMaterial;
    ["material16.001"]: THREE.MeshStandardMaterial;
    ["material17.001"]: THREE.MeshStandardMaterial;
    ["material18.001"]: THREE.MeshStandardMaterial;
    ["material19.001"]: THREE.MeshStandardMaterial;
    ["material20.001"]: THREE.MeshStandardMaterial;
    ["material21.001"]: THREE.MeshStandardMaterial;
    ["material22.001"]: THREE.MeshStandardMaterial;
    ["material23.001"]: THREE.MeshStandardMaterial;
    ["material24.001"]: THREE.MeshStandardMaterial;
    ["material25.001"]: THREE.MeshStandardMaterial;
    ["material26.001"]: THREE.MeshStandardMaterial;
  };
};

export function FoodModel(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/V4/FOOD_LOD/food.gltf"
  ) as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group position={[-1.897, 1.298, -3.924]} scale={[0.805, 1.291, 0.003]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l3_Meat_shelf_background_1.geometry}
          material={materials["Material.006"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l3_Meat_shelf_background_2.geometry}
          material={materials["Material.007"]}
        />
      </group>
      <group position={[-3.684, 1.298, -3.924]} scale={[0.805, 1.291, 0.003]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l3_Meat_shelf_background001_1.geometry}
          material={materials["Material.005"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l3_Meat_shelf_background001_2.geometry}
          material={materials.Material}
        />
      </group>
      <group position={[-1.915, 1.298, -2.155]} scale={[0.805, 1.291, 0.003]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l3_Meat_shelf_background002_1.geometry}
          material={materials["Material.013"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l3_Meat_shelf_background002_2.geometry}
          material={materials["Material.014"]}
        />
      </group>
      <group position={[-3.688, 1.298, -1.955]} scale={[0.805, 1.291, 0.003]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l3_Meat_shelf_background003_1.geometry}
          material={materials["Material.015"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l3_Meat_shelf_background003_2.geometry}
          material={materials["Material.016"]}
        />
      </group>
      <group
        position={[-3.311, 0.001, 4.009]}
        rotation={[0, -1.571, 0]}
        scale={1.125}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l3_Veges_Details_1.geometry}
          material={materials.Plywood_C_50cm}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l3_Veges_Details_2.geometry}
          material={materials["Material.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l3_Veges_Details_3.geometry}
          material={materials.Iron_Blurry_5cm}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l3_Veges_Details_4.geometry}
          material={materials["MIROR 2"]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes._l3_Veges_Details002.geometry}
        material={materials["storage basket"]}
        position={[-3.311, 0.001, 4.009]}
        rotation={[0, -1.571, 0]}
        scale={1.125}
      />
      <group position={[1.986, 1.298, -2.155]} scale={[1.069, 1.291, 0.003]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l3_Veges_shelf_background_1.geometry}
          material={materials["Material.027"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l3_Veges_shelf_background_2.geometry}
          material={materials["Material.026"]}
        />
      </group>
      <group position={[4.273, 1.298, -2.155]} scale={[1.069, 1.291, 0.003]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l3_Veges_shelf_background001_1.geometry}
          material={materials["Material.028"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l3_Veges_shelf_background001_2.geometry}
          material={materials["Material.029"]}
        />
      </group>
      <group position={[4.273, 1.298, -4.097]} scale={[1.069, 1.291, 0.003]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l3_Veges_shelf_background002_1.geometry}
          material={materials["Material.030"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l3_Veges_shelf_background002_2.geometry}
          material={materials["Material.031"]}
        />
      </group>
      <group position={[1.986, 1.298, -4.097]} scale={[1.069, 1.291, 0.003]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l3_Veges_shelf_background003_1.geometry}
          material={materials["Material.032"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l3_Veges_shelf_background003_2.geometry}
          material={materials["Material.033"]}
        />
      </group>
      <group
        position={[5.643, 1.662, 0.412]}
        rotation={[0.681, 0, 0]}
        scale={[0.451, 1.05, 0.307]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l3_Vegestable_shelf_1_1.geometry}
          material={materials["Material.038"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l3_Vegestable_shelf_1_2.geometry}
          material={materials["Black Steel.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l3_Vegestable_shelf_1_3.geometry}
          material={materials["wood.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l3_Vegestable_shelf_1_4.geometry}
          material={materials["Grey.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l3_Vegestable_shelf_1_5.geometry}
          material={materials["Black.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l3_Vegestable_shelf_1_6.geometry}
          material={materials["Material.039"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l3_Vegestable_shelf_1_7.geometry}
          material={materials["Material.040"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l3_Vegestable_shelf_1_8.geometry}
          material={materials["Price09.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l3_Vegestable_shelf_1_9.geometry}
          material={materials["Price07.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l3_Vegestable_shelf_1_10.geometry}
          material={materials["Price08.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l3_Vegestable_shelf_1_11.geometry}
          material={materials["black_plastic.002"]}
        />
      </group>
      <group
        position={[4.516, 1.662, 0.412]}
        rotation={[0.681, 0, 0]}
        scale={[0.451, 1.05, 0.307]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l3_Vegestable_shelf_2_1.geometry}
          material={materials["Material.025"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l3_Vegestable_shelf_2_2.geometry}
          material={materials["Black Steel"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l3_Vegestable_shelf_2_3.geometry}
          material={materials.wood}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l3_Vegestable_shelf_2_4.geometry}
          material={materials.Grey}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l3_Vegestable_shelf_2_5.geometry}
          material={materials.Black}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l3_Vegestable_shelf_2_6.geometry}
          material={materials["Material.023"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l3_Vegestable_shelf_2_7.geometry}
          material={materials["Material.024"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l3_Vegestable_shelf_2_8.geometry}
          material={materials.Price09}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l3_Vegestable_shelf_2_9.geometry}
          material={materials.Price07}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l3_Vegestable_shelf_2_10.geometry}
          material={materials.Price08}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l3_Vegestable_shelf_2_11.geometry}
          material={materials.black_plastic}
        />
      </group>
      <group
        position={[3.269, 1.241, 0.903]}
        rotation={[0.681, 0, 0]}
        scale={[0.459, 1.07, 0.313]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["_l3_Vegestable_shelf_3_&_4_1"].geometry}
          material={materials["Material.020"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["_l3_Vegestable_shelf_3_&_4_2"].geometry}
          material={materials["Black Steel"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["_l3_Vegestable_shelf_3_&_4_3"].geometry}
          material={materials.wood}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["_l3_Vegestable_shelf_3_&_4_4"].geometry}
          material={materials.Grey}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["_l3_Vegestable_shelf_3_&_4_5"].geometry}
          material={materials.Black}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["_l3_Vegestable_shelf_3_&_4_6"].geometry}
          material={materials.green_plastic}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["_l3_Vegestable_shelf_3_&_4_7"].geometry}
          material={materials.Price06}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["_l3_Vegestable_shelf_3_&_4_8"].geometry}
          material={materials["Material.017"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["_l3_Vegestable_shelf_3_&_4_9"].geometry}
          material={materials["Material.018"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["_l3_Vegestable_shelf_3_&_4_10"].geometry}
          material={materials["Material.019"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["_l3_Vegestable_shelf_3_&_4_11"].geometry}
          material={materials["Material.021"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["_l3_Vegestable_shelf_3_&_4_12"].geometry}
          material={materials["Material.022"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["_l3_Vegestable_shelf_3_&_4_13"].geometry}
          material={materials.Price05}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["_l3_Vegestable_shelf_3_&_4_14"].geometry}
          material={materials.Price01}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["_l3_Vegestable_shelf_3_&_4_15"].geometry}
          material={materials.Price02}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["_l3_Vegestable_shelf_3_&_4_16"].geometry}
          material={materials.Price04}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["_l3_Vegestable_shelf_3_&_4_17"].geometry}
          material={materials.Price03}
        />
      </group>
      <group position={[-5.27, 0, 4.518]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["_l3_Vegestable_shelf_5&6_1"].geometry}
          material={materials["Mis-vf_black"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["_l3_Vegestable_shelf_5&6_2"].geometry}
          material={materials.glass}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["_l3_Vegestable_shelf_5&6_3"].geometry}
          material={materials.wood_light}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["_l3_Vegestable_shelf_5&6_4"].geometry}
          material={materials.Chrome}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["_l3_Vegestable_shelf_5&6_5"].geometry}
          material={materials["Mis-vf_black-2"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["_l3_Vegestable_shelf_5&6_6"].geometry}
          material={materials["Material.037"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["_l3_Vegestable_shelf_5&6_7"].geometry}
          material={materials["Material.034"]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes._l4_Veges_Shelf_Details.geometry}
        material={materials["photo corn bits"]}
        position={[-3.311, 0.001, 4.009]}
        rotation={[0, -1.571, 0]}
        scale={1.125}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes._l4_Veges_Shelf_Details001.geometry}
        material={materials["pexels-photo-1313267"]}
        position={[-3.311, 0.001, 4.009]}
        rotation={[0, -1.571, 0]}
        scale={1.125}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes._l4_Veges_Shelf_Details002.geometry}
        material={materials.ee14c22e9800997a474536eadc93a1a8}
        position={[-3.311, 0.001, 4.009]}
        rotation={[0, -1.571, 0]}
        scale={1.125}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes._l4_Veges_Shelf_Details003.geometry}
        material={materials["cabbage-soup-diet-1"]}
        position={[-3.311, 0.001, 4.009]}
        rotation={[0, -1.571, 0]}
        scale={1.125}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes._l4_Veges_Shelf_Details004.geometry}
        material={materials["photo tomato skin"]}
        position={[-3.311, 0.001, 4.009]}
        rotation={[0, -1.571, 0]}
        scale={1.125}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes._l4_Veges_Shelf_Details005.geometry}
        material={materials["photo {3d75f229-7087-b44d-b407-5d2c7250592e}"]}
        position={[-3.311, 0.001, 4.009]}
        rotation={[0, -1.571, 0]}
        scale={1.125}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes._l4_Veges_Shelf_Details006.geometry}
        material={materials["storage dark green"]}
        position={[-3.311, 0.001, 4.009]}
        rotation={[0, -1.571, 0]}
        scale={1.125}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes._l4_Veges_Shelf_Details007.geometry}
        material={materials["storage dark red"]}
        position={[-3.311, 0.001, 4.009]}
        rotation={[0, -1.571, 0]}
        scale={1.125}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes._l4_Veges_Shelf_Details008.geometry}
        material={materials["[Color_L22]1"]}
        position={[-3.311, 0.001, 4.009]}
        rotation={[0, -1.571, 0]}
        scale={1.125}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes._l4_Veges_Shelf_Details009.geometry}
        material={materials["storage red"]}
        position={[-3.311, 0.001, 4.009]}
        rotation={[0, -1.571, 0]}
        scale={1.125}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes._l4_Veges_Shelf_Details010.geometry}
        material={materials["storage orange"]}
        position={[-3.311, 0.001, 4.009]}
        rotation={[0, -1.571, 0]}
        scale={1.125}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes._l4_Veges_Shelf_Details011.geometry}
        material={materials["cabbage-soup-diet-1.001"]}
        position={[-3.311, 0.001, 4.009]}
        rotation={[0, -1.571, 0]}
        scale={1.125}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes._l1_Backdrop_box.geometry}
        material={materials["LCD06.002"]}
        position={[-0.362, 4.93, -7.465]}
        scale={[0.738, 0.599, 0.322]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes._l1_Floor.geometry}
        material={materials["Material.041"]}
        position={[-0.131, 0.147, 0.029]}
        rotation={[0, -1.571, 0]}
        scale={[0.932, 0.926, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes._l1_Main_Backdrop.geometry}
        material={materials["Ash Wood"]}
        position={[-0.104, 5.892, -7.846]}
        scale={[2, 1.345, 0.414]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes._l2_bamboo.geometry}
        material={materials.bamboo}
        position={[-0.131, -0.318, 0.029]}
        rotation={[0, -1.571, 0]}
        scale={[1, 1.194, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes._l2_Circle_Banners.geometry}
        material={materials.S1}
        position={[-0.131, 9.548, 0.029]}
        rotation={[0, -1.571, 0]}
        scale={[6.431, 7.696, 6.431]}
      />
      <group
        position={[-6.667, 2.187, -4.738]}
        rotation={[Math.PI / 2, 0, -0.443]}
        scale={[3.459, 0.978, 2.215]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l2_Visual_led_left_1.geometry}
          material={materials["Material.043"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l2_Visual_led_left_2.geometry}
          material={materials["Bamboo.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l2_Visual_led_left_3.geometry}
          material={materials["white.001"]}
        />
      </group>
      <group
        position={[6.249, 3.697, -4.809]}
        rotation={[0, -0.422, 0]}
        scale={0.825}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l2_Visual_led_right_1.geometry}
          material={materials.Bamboo}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l2_Visual_led_right_2.geometry}
          material={materials.white}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l2_Visual_led_right_3.geometry}
          material={materials["Material.042"]}
        />
      </group>
      <group
        position={[8.708, 2.004, 5.835]}
        rotation={[0, 0.611, 0]}
        scale={[1.005, 2.005, 0.191]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l1_Sign_Box002_1.geometry}
          material={materials["Material.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l1_Sign_Box002_2.geometry}
          material={materials["Material.010"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l1_Sign_Box002_3.geometry}
          material={materials["material0.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l1_Sign_Box002_4.geometry}
          material={materials["material1.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l1_Sign_Box002_5.geometry}
          material={materials["material2.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l1_Sign_Box002_6.geometry}
          material={materials["material3.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l1_Sign_Box002_7.geometry}
          material={materials["material4.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l1_Sign_Box002_8.geometry}
          material={materials["material5.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l1_Sign_Box002_9.geometry}
          material={materials["material6.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l1_Sign_Box002_10.geometry}
          material={materials["material7.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l1_Sign_Box002_11.geometry}
          material={materials["material8.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l1_Sign_Box002_12.geometry}
          material={materials["material9.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l1_Sign_Box002_13.geometry}
          material={materials["material10.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l1_Sign_Box002_14.geometry}
          material={materials["material11.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l1_Sign_Box002_15.geometry}
          material={materials["material12.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l1_Sign_Box002_16.geometry}
          material={materials["material13.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l1_Sign_Box002_17.geometry}
          material={materials["material14.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l1_Sign_Box002_18.geometry}
          material={materials["material15.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l1_Sign_Box002_19.geometry}
          material={materials["material16.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l1_Sign_Box002_20.geometry}
          material={materials["material17.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l1_Sign_Box002_21.geometry}
          material={materials["material18.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l1_Sign_Box002_22.geometry}
          material={materials["material19.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l1_Sign_Box002_23.geometry}
          material={materials["material20.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l1_Sign_Box002_24.geometry}
          material={materials["material21.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l1_Sign_Box002_25.geometry}
          material={materials["material22.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l1_Sign_Box002_26.geometry}
          material={materials["material23.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l1_Sign_Box002_27.geometry}
          material={materials["material24.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l1_Sign_Box002_28.geometry}
          material={materials["material25.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l1_Sign_Box002_29.geometry}
          material={materials["material26.001"]}
        />
      </group>
    </group>
  );
}
