/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\wood.gltf --shadows --types 
*/

import * as THREE from "three";
import React, { JSX, useRef, useState } from "react";
import { Detailed, useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { useThree, useFrame, invalidate } from "@react-three/fiber";
import { useDispose } from "@/utils/useDispose";

type GLTFResult = GLTF & {
  nodes: {
    _l3_shelf003_1: THREE.Mesh;
    _l3_shelf003_2: THREE.Mesh;
    _l3_shelf003_3: THREE.Mesh;
    _l3_shelf003_4: THREE.Mesh;
    _l3_shelf003_5: THREE.Mesh;
    _l3_shelf003_6: THREE.Mesh;
    _l3_shelf003_7: THREE.Mesh;
    _l3_shelf003_8: THREE.Mesh;
    _l3_shelf003_9: THREE.Mesh;
    _l3_shelf003_10: THREE.Mesh;
    _l3_shelf003_11: THREE.Mesh;
    _l3_shelf003_12: THREE.Mesh;
    _l2_blocks_1: THREE.Mesh;
    _l2_blocks_2: THREE.Mesh;
    _l2_blocks_3: THREE.Mesh;
    _l1_panel_1: THREE.Mesh;
    _l1_panel_2: THREE.Mesh;
    _l3_text: THREE.Mesh;
    _l3_text001: THREE.Mesh;
    _l2_vines: THREE.Mesh;
    _l1_floor001_1: THREE.Mesh;
    _l1_floor001_2: THREE.Mesh;
    _l2_block: THREE.Mesh;
    _l1_Sign_Box_1: THREE.Mesh;
    _l1_Sign_Box_2: THREE.Mesh;
    _l3_shelf002_1: THREE.Mesh;
    _l3_shelf002_2: THREE.Mesh;
    _l3_shelf002_3: THREE.Mesh;
    _l3_shelf002_4: THREE.Mesh;
    _l3_shelf002_5: THREE.Mesh;
    _l3_shelf002_6: THREE.Mesh;
    _l2_lights_1: THREE.Mesh;
    _l2_lights_2: THREE.Mesh;
    _l4_shelf001_1: THREE.Mesh;
    _l4_shelf001_2: THREE.Mesh;
    _l4_shelf001_3: THREE.Mesh;
    _l3_shelf_1: THREE.Mesh;
    _l3_shelf_2: THREE.Mesh;
    _l3_shelf_3: THREE.Mesh;
    _l3_shelf_4: THREE.Mesh;
    _l3_shelf_5: THREE.Mesh;
    _l3_shelf_6: THREE.Mesh;
    _l3_shelf_7: THREE.Mesh;
    _l3_shelf_8: THREE.Mesh;
    _l3_shelf_9: THREE.Mesh;
    _l4_table: THREE.Mesh;
    _l4_sofa_1: THREE.Mesh;
    _l4_sofa_2: THREE.Mesh;
    _l4_table001: THREE.Mesh;
    _l4_chair_1: THREE.Mesh;
    _l4_chair_2: THREE.Mesh;
    _l4_chair001_1: THREE.Mesh;
    _l4_chair001_2: THREE.Mesh;
    _l4_chair002_1: THREE.Mesh;
    _l4_chair002_2: THREE.Mesh;
    _l4_cabinet_1: THREE.Mesh;
    _l4_cabinet_2: THREE.Mesh;
    _l3_text002: THREE.Mesh;
    _l3_shelf004_1: THREE.Mesh;
    _l3_shelf004_2: THREE.Mesh;
    _l3_shelf004_3: THREE.Mesh;
    _l3_shelf004_4: THREE.Mesh;
    _l3_shelf004_5: THREE.Mesh;
    _l3_shelf004_6: THREE.Mesh;
    _l3_shelf004_7: THREE.Mesh;
    _l3_shelf004_8: THREE.Mesh;
    _l3_shelf004_9: THREE.Mesh;
    _l2_block001: THREE.Mesh;
  };
  materials: {
    ["7ssssssssssssss"]: THREE.MeshStandardMaterial;
    山东色板展示03: THREE.MeshStandardMaterial;
    山东色板展示10: THREE.MeshStandardMaterial;
    山东色板展示02: THREE.MeshStandardMaterial;
    山东色板展示11: THREE.MeshStandardMaterial;
    山东色板展示01: THREE.MeshStandardMaterial;
    山东色板展示08: THREE.MeshStandardMaterial;
    山东色板展示05: THREE.MeshStandardMaterial;
    山东色板展示09: THREE.MeshStandardMaterial;
    山东色板展示06: THREE.MeshStandardMaterial;
    山东色板展示04: THREE.MeshStandardMaterial;
    山东色板展示07: THREE.MeshStandardMaterial;
    ["Material.004"]: THREE.MeshStandardMaterial;
    laminate_floor: THREE.MeshStandardMaterial;
    ["Material.002"]: THREE.MeshStandardMaterial;
    Display: THREE.MeshStandardMaterial;
    LCD05: THREE.MeshStandardMaterial;
    ["material0.001"]: THREE.MeshStandardMaterial;
    ["material0.002"]: THREE.MeshStandardMaterial;
    ["Material.005"]: THREE.MeshStandardMaterial;
    concrete_floor_worn_001: THREE.MeshStandardMaterial;
    wood_floor: THREE.MeshStandardMaterial;
    ["Material.001"]: THREE.MeshStandardMaterial;
    ["Material.003"]: THREE.MeshStandardMaterial;
    ["Material.012"]: THREE.MeshStandardMaterial;
    ["Material.013"]: THREE.MeshStandardMaterial;
    ["Material.008"]: THREE.MeshStandardMaterial;
    ["Material.006"]: THREE.MeshStandardMaterial;
    ["Material.009"]: THREE.MeshStandardMaterial;
    ["Material.010"]: THREE.MeshStandardMaterial;
    ["laminate_floor.001"]: THREE.MeshStandardMaterial;
    ["Material.014"]: THREE.MeshStandardMaterial;
    ["vray Material #136s"]: THREE.MeshStandardMaterial;
    ["vray Material #36"]: THREE.MeshStandardMaterial;
    ["vray Material #136"]: THREE.MeshStandardMaterial;
    ["PhysicalMaterial.001"]: THREE.MeshStandardMaterial;
    ["PhysicalMaterial.002"]: THREE.MeshStandardMaterial;
    ["PhysicalMaterial.003"]: THREE.MeshStandardMaterial;
    ["PhysicalMaterial.004"]: THREE.MeshStandardMaterial;
    ["PhysicalMaterial.005"]: THREE.MeshStandardMaterial;
    ["PhysicalMaterial.006"]: THREE.MeshStandardMaterial;
    ["PhysicalMaterial.007"]: THREE.MeshStandardMaterial;
    ["PhysicalMaterial.008"]: THREE.MeshStandardMaterial;
    ["PhysicalMaterial.009"]: THREE.MeshStandardMaterial;
    wire_000000000: THREE.MeshStandardMaterial;
    wire_145028177: THREE.MeshStandardMaterial;
    wire_134006006: THREE.MeshStandardMaterial;
    wire_214228153: THREE.MeshStandardMaterial;
    wire_087225087: THREE.MeshStandardMaterial;
    wire_088177027: THREE.MeshStandardMaterial;
    wire_087225143: THREE.MeshStandardMaterial;
    wire_061135006: THREE.MeshStandardMaterial;
    wire_028089177: THREE.MeshStandardMaterial;
    ["wire_028089177.001"]: THREE.MeshStandardMaterial;
    ["PhysicalMaterial.010"]: THREE.MeshStandardMaterial;
    ["PhysicalMaterial.011"]: THREE.MeshStandardMaterial;
    ["PhysicalMaterial.012"]: THREE.MeshStandardMaterial;
    ["PhysicalMaterial.013"]: THREE.MeshStandardMaterial;
    ["PhysicalMaterial.014"]: THREE.MeshStandardMaterial;
    ["PhysicalMaterial.015"]: THREE.MeshStandardMaterial;
    ["PhysicalMaterial.016"]: THREE.MeshStandardMaterial;
    ["PhysicalMaterial.017"]: THREE.MeshStandardMaterial;
    ["PhysicalMaterial.018"]: THREE.MeshStandardMaterial;
    ["concrete_floor_worn_001.001"]: THREE.MeshStandardMaterial;
  };
};

const LOD0 = ({ nodes, materials }: { nodes: any; materials: any }) => {
  const lodRef = useDispose();

  return (
    <group ref={lodRef}>
      <group
        position={[-2.688, 0.819, -5.365]}
        rotation={[-Math.PI, 0, -Math.PI]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l1_panel_1.geometry}
          material={materials.Display}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l1_panel_2.geometry}
          material={materials.LCD05}
        />
      </group>
      <group position={[-2.717, 0.2, 1.549]} rotation={[0, -1.571, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l1_floor001_1.geometry}
          material={materials.concrete_floor_worn_001}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l1_floor001_2.geometry}
          material={materials.wood_floor}
        />
      </group>
      <group
        position={[-8.45, 2.203, 5.523]}
        rotation={[0, -0.611, 0]}
        scale={[1.005, 2.005, 0.191]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l1_Sign_Box_1.geometry}
          material={materials["Material.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l1_Sign_Box_2.geometry}
          material={materials["Material.003"]}
        />
      </group>
    </group>
  );
};

const LOD1 = ({ nodes, materials }: { nodes: any; materials: any }) => {
  const lodRef = useDispose();

  return (
    <group ref={lodRef}>
      <group position={[-2.563, 4.717, -3.47]} rotation={[0, -1.571, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l2_blocks_1.geometry}
          material={materials["Material.004"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l2_blocks_2.geometry}
          material={materials.laminate_floor}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l2_blocks_3.geometry}
          material={materials["Material.002"]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes._l2_vines.geometry}
        material={materials["Material.005"]}
        position={[-2.775, 2.328, -2.156]}
        rotation={[Math.PI / 2, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes._l2_block.geometry}
        material={materials.concrete_floor_worn_001}
        position={[-2.717, 0.2, 0.572]}
        rotation={[0, -1.571, 0]}
      />
      <group
        position={[-2.861, 6.433, 2.425]}
        rotation={[0, -1.571, 0]}
        scale={1.14}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l2_lights_1.geometry}
          material={materials["laminate_floor.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l2_lights_2.geometry}
          material={materials["Material.014"]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes._l2_block001.geometry}
        material={materials["concrete_floor_worn_001.001"]}
        position={[-16.755, 0.2, 0.572]}
        rotation={[0, -1.571, 0]}
      />
    </group>
  );
};

const LOD2 = ({ nodes, materials }: { nodes: any; materials: any }) => {
  const lodRef = useDispose();

  return (
    <group ref={lodRef}>
      <group
        position={[3.758, 0.209, -0.08]}
        rotation={[0, -1.571, 0]}
        scale={0.263}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l3_shelf003_1.geometry}
          material={materials["7ssssssssssssss"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l3_shelf003_2.geometry}
          material={materials.山东色板展示03}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l3_shelf003_3.geometry}
          material={materials.山东色板展示10}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l3_shelf003_4.geometry}
          material={materials.山东色板展示02}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l3_shelf003_5.geometry}
          material={materials.山东色板展示11}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l3_shelf003_6.geometry}
          material={materials.山东色板展示01}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l3_shelf003_7.geometry}
          material={materials.山东色板展示08}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l3_shelf003_8.geometry}
          material={materials.山东色板展示05}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l3_shelf003_9.geometry}
          material={materials.山东色板展示09}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l3_shelf003_10.geometry}
          material={materials.山东色板展示06}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l3_shelf003_11.geometry}
          material={materials.山东色板展示04}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l3_shelf003_12.geometry}
          material={materials.山东色板展示07}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes._l3_text.geometry}
        material={materials["material0.001"]}
        position={[1.106, 3.568, -1.449]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.535}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes._l3_text001.geometry}
        material={materials["material0.002"]}
        position={[-5.936, 3.599, -1.458]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.535}
      />
      <group position={[1.383, 1.248, -1.34]} scale={[1.33, 1.052, 0.005]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l3_shelf002_1.geometry}
          material={materials["Material.012"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l3_shelf002_2.geometry}
          material={materials["Material.013"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l3_shelf002_3.geometry}
          material={materials["Material.008"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l3_shelf002_4.geometry}
          material={materials["Material.006"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l3_shelf002_5.geometry}
          material={materials["Material.009"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l3_shelf002_6.geometry}
          material={materials["Material.010"]}
        />
      </group>
      <group position={[-6.818, 0.172, -1.333]} scale={1.206}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l3_shelf_1.geometry}
          material={materials["PhysicalMaterial.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l3_shelf_2.geometry}
          material={materials["PhysicalMaterial.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l3_shelf_3.geometry}
          material={materials["PhysicalMaterial.003"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l3_shelf_4.geometry}
          material={materials["PhysicalMaterial.004"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l3_shelf_5.geometry}
          material={materials["PhysicalMaterial.005"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l3_shelf_6.geometry}
          material={materials["PhysicalMaterial.006"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l3_shelf_7.geometry}
          material={materials["PhysicalMaterial.007"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l3_shelf_8.geometry}
          material={materials["PhysicalMaterial.008"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l3_shelf_9.geometry}
          material={materials["PhysicalMaterial.009"]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes._l3_text002.geometry}
        material={materials["material0.002"]}
        position={[-2.645, 1.177, 5.979]}
        rotation={[0, -0.003, 0]}
        scale={[0.789, 1.574, 0.15]}
      />
      <group position={[-6.818, 0.172, 0.284]} scale={1.206}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l3_shelf004_1.geometry}
          material={materials["PhysicalMaterial.010"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l3_shelf004_2.geometry}
          material={materials["PhysicalMaterial.011"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l3_shelf004_3.geometry}
          material={materials["PhysicalMaterial.012"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l3_shelf004_4.geometry}
          material={materials["PhysicalMaterial.013"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l3_shelf004_5.geometry}
          material={materials["PhysicalMaterial.014"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l3_shelf004_6.geometry}
          material={materials["PhysicalMaterial.015"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l3_shelf004_7.geometry}
          material={materials["PhysicalMaterial.016"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l3_shelf004_8.geometry}
          material={materials["PhysicalMaterial.017"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l3_shelf004_9.geometry}
          material={materials["PhysicalMaterial.018"]}
        />
      </group>
    </group>
  );
};

const LOD3 = ({ nodes, materials }: { nodes: any; materials: any }) => {
  const lodRef = useDispose();

  return (
    <group ref={lodRef}>
      <group
        position={[-4.221, 0.182, 6.822]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
        scale={0.017}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l4_shelf001_1.geometry}
          material={materials["vray Material #136s"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l4_shelf001_2.geometry}
          material={materials["vray Material #36"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l4_shelf001_3.geometry}
          material={materials["vray Material #136"]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes._l4_table.geometry}
        material={materials.wire_000000000}
        position={[-5.08, 0.2, 3.804]}
      />
      <group position={[-3.14, 0.2, 3.697]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l4_sofa_1.geometry}
          material={materials.wire_145028177}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l4_sofa_2.geometry}
          material={materials.wire_134006006}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes._l4_table001.geometry}
        material={materials.wire_214228153}
        position={[0.964, 0.16, 4.501]}
      />
      <group position={[0.956, 0.199, 3.566]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l4_chair_1.geometry}
          material={materials.wire_087225087}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l4_chair_2.geometry}
          material={materials.wire_088177027}
        />
      </group>
      <group position={[2.138, 0.199, 4.528]} rotation={[0, -Math.PI / 2, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l4_chair001_1.geometry}
          material={materials.wire_087225087}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l4_chair001_2.geometry}
          material={materials.wire_088177027}
        />
      </group>
      <group
        position={[-5.372, 0.2, 3.726]}
        rotation={[-Math.PI, 0.824, -Math.PI]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l4_chair002_1.geometry}
          material={materials.wire_087225143}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l4_chair002_2.geometry}
          material={materials.wire_061135006}
        />
      </group>
      <group position={[3.611, 0.2, 2.956]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l4_cabinet_1.geometry}
          material={materials.wire_028089177}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._l4_cabinet_2.geometry}
          material={materials["wire_028089177.001"]}
        />
      </group>
    </group>
  );
};

export function WoodModel(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/V4/WOOD_LOD/Wood.gltf"
  ) as unknown as GLTFResult;

  return (
    <group {...props}>
      <Detailed
        onUpdate={() => {
          invalidate();
        }}
        distances={[0, 11, 15, 25, 30]}
      >
        <group>
          <LOD0 nodes={nodes} materials={materials} />
          <LOD1 nodes={nodes} materials={materials} />
          <LOD2 nodes={nodes} materials={materials} />
          <LOD3 nodes={nodes} materials={materials} />
        </group>
        <group>
          <LOD0 nodes={nodes} materials={materials} />
          <LOD1 nodes={nodes} materials={materials} />
          <LOD2 nodes={nodes} materials={materials} />
        </group>
        <group>
          <LOD0 nodes={nodes} materials={materials} />
          <LOD1 nodes={nodes} materials={materials} />
        </group>
        <LOD0 nodes={nodes} materials={materials} />
        <group></group>
      </Detailed>
    </group>
  );
}

useGLTF.preload("/V4/WOOD_LOD/Wood.gltf");
