/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\booth_thuysan_v2.gltf --transform --types 
Files: .\booth_thuysan_v2.gltf [503.33KB] > C:\Users\zatag\assets\booth_thuysan_v2-transformed.glb [3.21MB] (-538%)
*/

import * as THREE from 'three'
import React, { JSX } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Plane008: THREE.Mesh
    JianE_model_1728584281006: THREE.Mesh
    Plane: THREE.Mesh
    咖啡_袋装咖啡豆_食物饮料饮品_食品袋032: THREE.Mesh
    Object_111: THREE.Mesh
    Plane013: THREE.Mesh
    Plane013_1: THREE.Mesh
    Plane002: THREE.Mesh
    fish_239001: THREE.Mesh
    fish_239030: THREE.Mesh
    fish_239048: THREE.Mesh
    fish_239049: THREE.Mesh
    ['47245750063001']: THREE.Mesh
    ['47245750063004']: THREE.Mesh
    ['47245750063005']: THREE.Mesh
    ['47245750063023']: THREE.Mesh
    ['47245750063024']: THREE.Mesh
    ['47245750063025']: THREE.Mesh
    ['47245750063026']: THREE.Mesh
    ['47245750063027']: THREE.Mesh
    ch_110: THREE.Mesh
    ch_110003: THREE.Mesh
    ch_110004: THREE.Mesh
    ch_110005: THREE.Mesh
    ch_110006: THREE.Mesh
    ch_110007: THREE.Mesh
    ch_110008: THREE.Mesh
    ch_110010: THREE.Mesh
    Fridge1008: THREE.Mesh
    Fridge11128: THREE.Mesh
    Fridge1133: THREE.Mesh
    Fridge12312: THREE.Mesh
    Fridge12554: THREE.Mesh
    Mesh268: THREE.Mesh
    Mesh268_1: THREE.Mesh
    Mesh268_2: THREE.Mesh
    Mesh268_3: THREE.Mesh
    Fridge2008: THREE.Mesh
  }
  materials: {
    ['Material.001']: THREE.MeshStandardMaterial
    ['JianE_Mtl_202141520154576.007']: THREE.MeshStandardMaterial
    ['Material.002']: THREE.MeshStandardMaterial
    PaletteMaterial002: THREE.MeshStandardMaterial
    PRO: THREE.MeshStandardMaterial
    ['Material.003']: THREE.MeshStandardMaterial
    PaletteMaterial007: THREE.MeshStandardMaterial
    Material: THREE.MeshStandardMaterial
    ['M_Grocery2.001']: THREE.MeshStandardMaterial
    ['fis02.001']: THREE.MeshStandardMaterial
    PaletteMaterial001: THREE.MeshStandardMaterial
    ['M_Furniture1.001']: THREE.MeshStandardMaterial
    ['47245750046']: THREE.MeshStandardMaterial
    ['47245750056']: THREE.MeshStandardMaterial
    ['JianE_Mtl_202141520154577.001']: THREE.MeshStandardMaterial
    ['47245750051']: THREE.MeshStandardMaterial
    ['47245750052']: THREE.MeshStandardMaterial
    ['47245750053']: THREE.MeshStandardMaterial
    ['47245750054']: THREE.MeshStandardMaterial
    ['47245750055']: THREE.MeshStandardMaterial
    wi01: THREE.MeshStandardMaterial
    PaletteMaterial003: THREE.MeshStandardMaterial
    PaletteMaterial004: THREE.MeshStandardMaterial
    PaletteMaterial005: THREE.MeshStandardMaterial
    sal01: THREE.MeshStandardMaterial
    sal02: THREE.MeshStandardMaterial
    fis01: THREE.MeshStandardMaterial
    ['turk 01']: THREE.MeshStandardMaterial
    ['vray_Ref_Plane_Mat001.003']: THREE.MeshStandardMaterial
    ['vray_METAL::Smooth::Chrome Satin.001']: THREE.MeshStandardMaterial
    ['vray_Ref_Plane_Mat001.004']: THREE.MeshStandardMaterial
    ['vray_METAL::Smooth::Steel24.001']: THREE.MeshStandardMaterial
    ['vray_PVC Black Glossy.001']: THREE.MeshStandardMaterial
    ['vray_Material #384248859.001']: THREE.MeshStandardMaterial
    PaletteMaterial006: THREE.MeshStandardMaterial
    ['vray_PLASTIC::PVC::Opaque Gr24ey.001']: THREE.MeshStandardMaterial
    ['vray_METAL::Smooth::Steel.001']: THREE.MeshStandardMaterial
    ['vray_PLASTIC::PVC::Opaque G2747rey.001']: THREE.MeshStandardMaterial
  }
  animations: any[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/VR/booth_thuysan-transformed.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Plane008.geometry} material={materials['Material.001']} position={[4.516, -0.004, -3.542]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <mesh geometry={nodes.JianE_model_1728584281006.geometry} material={materials['JianE_Mtl_202141520154576.007']} position={[-233.368, -904.945, 2960.583]} rotation={[Math.PI, -1.08, Math.PI]} />
      <mesh geometry={nodes.Plane.geometry} material={materials['Material.002']} position={[0.048, 3.736, 4.173]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} />
      <mesh geometry={nodes.咖啡_袋装咖啡豆_食物饮料饮品_食品袋032.geometry} material={materials.PaletteMaterial002} position={[4.748, 1.619, -1.364]} rotation={[0, Math.PI / 2, 0]} />
      <mesh geometry={nodes.Object_111.geometry} material={materials.PRO} position={[-4.673, 0.961, 0.456]} rotation={[0.021, 0, 0]} />
      <group position={[0.052, 3.736, -0.122]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Plane013.geometry} material={materials['Material.003']} />
        <mesh geometry={nodes.Plane013_1.geometry} material={materials.PaletteMaterial007} />
      </group>
      <mesh geometry={nodes.Plane002.geometry} material={materials.Material} position={[0.309, 0.004, 0.301]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.fish_239001.geometry} material={materials['M_Grocery2.001']} position={[-6.296, 0.486, -0.838]} rotation={[-Math.PI, 0.493, -Math.PI]} />
      <mesh geometry={nodes.fish_239030.geometry} material={materials['fis02.001']} position={[-6.296, 0.486, -0.838]} rotation={[-Math.PI, 0.493, -Math.PI]} />
      <mesh geometry={nodes.fish_239048.geometry} material={materials.PaletteMaterial001} position={[-6.296, 0.486, -0.838]} rotation={[-Math.PI, 0.493, -Math.PI]} />
      <mesh geometry={nodes.fish_239049.geometry} material={materials['M_Furniture1.001']} position={[-6.296, 0.486, -0.838]} rotation={[-Math.PI, 0.493, -Math.PI]} />
      <mesh geometry={nodes['47245750063001'].geometry} material={materials['47245750046']} position={[2.274, 0.745, 0.822]} />
      <mesh geometry={nodes['47245750063004'].geometry} material={materials['47245750056']} position={[2.274, 0.745, 0.822]} />
      <mesh geometry={nodes['47245750063005'].geometry} material={materials['JianE_Mtl_202141520154577.001']} position={[2.274, 0.745, 0.822]} />
      <mesh geometry={nodes['47245750063023'].geometry} material={materials['47245750051']} position={[2.274, 0.745, 0.822]} />
      <mesh geometry={nodes['47245750063024'].geometry} material={materials['47245750052']} position={[2.274, 0.745, 0.822]} />
      <mesh geometry={nodes['47245750063025'].geometry} material={materials['47245750053']} position={[2.274, 0.745, 0.822]} />
      <mesh geometry={nodes['47245750063026'].geometry} material={materials['47245750054']} position={[2.274, 0.745, 0.822]} />
      <mesh geometry={nodes['47245750063027'].geometry} material={materials['47245750055']} position={[2.274, 0.745, 0.822]} />
      <mesh geometry={nodes.ch_110.geometry} material={materials.wi01} position={[-2.73, 0.391, 0.475]} rotation={[0, Math.PI / 2, 0]} />
      <mesh geometry={nodes.ch_110003.geometry} material={materials.PaletteMaterial003} position={[-2.73, 0.391, 0.475]} rotation={[0, Math.PI / 2, 0]} />
      <mesh geometry={nodes.ch_110004.geometry} material={materials.PaletteMaterial004} position={[-2.73, 0.391, 0.475]} rotation={[0, Math.PI / 2, 0]} />
      <mesh geometry={nodes.ch_110005.geometry} material={materials.PaletteMaterial005} position={[-2.73, 0.391, 0.475]} rotation={[0, Math.PI / 2, 0]} />
      <mesh geometry={nodes.ch_110006.geometry} material={materials.sal01} position={[-2.73, 0.391, 0.475]} rotation={[0, Math.PI / 2, 0]} />
      <mesh geometry={nodes.ch_110007.geometry} material={materials.sal02} position={[-2.73, 0.391, 0.475]} rotation={[0, Math.PI / 2, 0]} />
      <mesh geometry={nodes.ch_110008.geometry} material={materials.fis01} position={[-2.73, 0.391, 0.475]} rotation={[0, Math.PI / 2, 0]} />
      <mesh geometry={nodes.ch_110010.geometry} material={materials['turk 01']} position={[-2.73, 0.391, 0.475]} rotation={[0, Math.PI / 2, 0]} />
      <mesh geometry={nodes.Fridge1008.geometry} material={materials['vray_Ref_Plane_Mat001.003']} position={[-10.758, 1.034, -3.077]} rotation={[Math.PI / 2, 0, 0.005]} />
      <mesh geometry={nodes.Fridge11128.geometry} material={materials['vray_METAL::Smooth::Chrome Satin.001']} position={[-10.758, 1.034, -3.077]} rotation={[Math.PI / 2, 0, 0.005]} />
      <mesh geometry={nodes.Fridge1133.geometry} material={materials['vray_Ref_Plane_Mat001.004']} position={[-10.758, 1.034, -3.077]} rotation={[Math.PI / 2, 0, 0.005]} />
      <mesh geometry={nodes.Fridge12312.geometry} material={materials['vray_METAL::Smooth::Steel24.001']} position={[-10.758, 1.034, -3.077]} rotation={[Math.PI / 2, 0, 0.005]} />
      <mesh geometry={nodes.Fridge12554.geometry} material={materials['vray_PVC Black Glossy.001']} position={[-10.758, 1.034, -3.077]} rotation={[Math.PI / 2, 0, 0.005]} />
      <group position={[-7.606, 1.034, -3.077]} rotation={[Math.PI / 2, 0, 0.005]}>
        <mesh geometry={nodes.Mesh268.geometry} material={materials['vray_Material #384248859.001']} />
        <mesh geometry={nodes.Mesh268_1.geometry} material={materials.PaletteMaterial006} />
        <mesh geometry={nodes.Mesh268_2.geometry} material={materials['vray_PLASTIC::PVC::Opaque Gr24ey.001']} />
        <mesh geometry={nodes.Mesh268_3.geometry} material={materials['vray_METAL::Smooth::Steel.001']} />
      </group>
      <mesh geometry={nodes.Fridge2008.geometry} material={materials['vray_PLASTIC::PVC::Opaque G2747rey.001']} position={[-3.772, 0.764, -2.723]} rotation={[Math.PI / 2, 0, 0.005]} />
    </group>
  )
}

useGLTF.preload('/VR/booth_thuysan-transformed.glb')
