/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./booth_thuysan/booth_thuysan.gltf --transform --types 
Files: ./booth_thuysan/booth_thuysan.gltf [1.82MB] > C:\Users\zatag\3d-viewer\public\VR\booth_thuysan-transformed.glb [4.35MB] (-139%)
*/

import * as THREE from 'three'
import React, { JSX } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Object_111: THREE.Mesh
    Plane004_1: THREE.Mesh
    Plane004_2: THREE.Mesh
    Plane005: THREE.Mesh
    Plane008: THREE.Mesh
    Plane010: THREE.Mesh
    Plane012: THREE.Mesh
    Plane017: THREE.Mesh
    Cube: THREE.Mesh
    Mesh1166: THREE.Mesh
    Mesh1166_1: THREE.Mesh
    Mesh1166_2: THREE.Mesh
    Mesh1166_3: THREE.Mesh
    Mesh1166_4: THREE.Mesh
    Mesh1166_5: THREE.Mesh
    Mesh1166_6: THREE.Mesh
    Mesh1166_7: THREE.Mesh
    cirlcelamp_lambert1_0: THREE.Mesh
    ch_101: THREE.Mesh
    fish_200: THREE.Mesh
    Mesh022: THREE.Mesh
    Mesh022_1: THREE.Mesh
    Mesh022_2: THREE.Mesh
    nors_102: THREE.Mesh
    nos_202: THREE.Mesh
    nos_264: THREE.Mesh
    sos_102: THREE.Mesh
    turk_100: THREE.Mesh
    win_100: THREE.Mesh
    Mesh1161: THREE.Mesh
    Mesh1161_1: THREE.Mesh
    Mesh1161_2: THREE.Mesh
    SM_Fish1017: THREE.Mesh
    SM_StoreFreezer2_1: THREE.Mesh
    SM_StoreFreezer2_2: THREE.Mesh
    Plane002: THREE.Mesh
  }
  materials: {
    PRO: THREE.MeshStandardMaterial
    ['Material.005']: THREE.MeshStandardMaterial
    PaletteMaterial001: THREE.MeshStandardMaterial
    ['Material.002']: THREE.MeshStandardMaterial
    ['Material.010']: THREE.MeshStandardMaterial
    ['Material.011']: THREE.MeshStandardMaterial
    PaletteMaterial002: THREE.MeshStandardMaterial
    ['Material.008']: THREE.MeshStandardMaterial
    ['Material.006']: THREE.MeshStandardMaterial
    vray_Ref_Plane_Mat001: THREE.MeshStandardMaterial
    PaletteMaterial006: THREE.MeshStandardMaterial
    ['vray_METAL::Smooth::Chrome Satin']: THREE.MeshStandardMaterial
    ['vray_METAL::Smooth::Steel24']: THREE.MeshStandardMaterial
    ['vray_PLASTIC::PVC::Opaque Gr24ey']: THREE.MeshStandardMaterial
    ['vray_METAL::Smooth::Steel']: THREE.MeshStandardMaterial
    ['vray_PLASTIC::PVC::Opaque Grey247']: THREE.MeshStandardMaterial
    ['vray_PLASTIC::PVC::Opaque G2747rey']: THREE.MeshStandardMaterial
    lambert1: THREE.MeshStandardMaterial
    ch01: THREE.MeshStandardMaterial
    fis02: THREE.MeshStandardMaterial
    PaletteMaterial003: THREE.MeshStandardMaterial
    PaletteMaterial004: THREE.MeshStandardMaterial
    PaletteMaterial005: THREE.MeshStandardMaterial
    sal01: THREE.MeshStandardMaterial
    sal02: THREE.MeshStandardMaterial
    fis01: THREE.MeshStandardMaterial
    sos01: THREE.MeshStandardMaterial
    ['turk 01']: THREE.MeshStandardMaterial
    wi01: THREE.MeshStandardMaterial
    ['vray_Ref_Plane_Mat001.001']: THREE.MeshStandardMaterial
    ['vray_Ref_Plane_Mat001.002']: THREE.MeshStandardMaterial
    ['vray_Material #384248859']: THREE.MeshStandardMaterial
    M_Grocery2: THREE.MeshStandardMaterial
    M_Furniture1: THREE.MeshStandardMaterial
    PaletteMaterial007: THREE.MeshStandardMaterial
  }
  animations: any[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('VR/booth_thuysan-transformed.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_111.geometry} material={materials.PRO} position={[-4.976, 1.383, 0.936]} rotation={[0.021, 0, 0]} scale={0.637} />
      <group position={[-0.607, 0.033, -0.674]} rotation={[Math.PI / 2, 0, 0]} scale={[0.463, 0.463, 0.811]}>
        <mesh geometry={nodes.Plane004_1.geometry} material={materials['Material.005']} />
        <mesh geometry={nodes.Plane004_2.geometry} material={materials.PaletteMaterial001} />
      </group>
      <mesh geometry={nodes.Plane005.geometry} material={materials['Material.002']} position={[2.274, 0.033, -0.718]} rotation={[Math.PI / 2, 0, 0]} scale={[0.611, 0.611, 1.07]} />
      <mesh geometry={nodes.Plane008.geometry} material={materials['Material.010']} position={[3.489, 0.033, 2.246]} rotation={[Math.PI / 2, 0, 0]} scale={[0.463, 0.463, 0.811]} />
      <mesh geometry={nodes.Plane010.geometry} material={materials['Material.011']} position={[5.118, 0.033, -0.674]} rotation={[Math.PI / 2, 0, 0]} scale={[0.463, 0.463, 0.811]} />
      <mesh geometry={nodes.Plane012.geometry} material={materials.PaletteMaterial002} position={[-4.683, 0.033, -2.997]} rotation={[Math.PI / 2, 0, 0]} scale={[1.056, 0.738, 1.293]} />
      <mesh geometry={nodes.Plane017.geometry} material={materials['Material.008']} position={[0.91, 0.033, -3.198]} rotation={[Math.PI / 2, 0, 0]} scale={[0.463, 0.463, 0.811]} />
      <mesh geometry={nodes.Cube.geometry} material={materials['Material.006']} position={[5.818, 1.045, 1.935]} scale={[0.529, 1, 0.304]} />
      <group position={[2.291, 0.309, -0.489]} rotation={[0, Math.PI / 2, 0]} scale={0.586}>
        <mesh geometry={nodes.Mesh1166.geometry} material={materials.vray_Ref_Plane_Mat001} />
        <mesh geometry={nodes.Mesh1166_1.geometry} material={materials.PaletteMaterial006} />
        <mesh geometry={nodes.Mesh1166_2.geometry} material={materials['vray_METAL::Smooth::Chrome Satin']} />
        <mesh geometry={nodes.Mesh1166_3.geometry} material={materials['vray_METAL::Smooth::Steel24']} />
        <mesh geometry={nodes.Mesh1166_4.geometry} material={materials['vray_PLASTIC::PVC::Opaque Gr24ey']} />
        <mesh geometry={nodes.Mesh1166_5.geometry} material={materials['vray_METAL::Smooth::Steel']} />
        <mesh geometry={nodes.Mesh1166_6.geometry} material={materials['vray_PLASTIC::PVC::Opaque Grey247']} />
        <mesh geometry={nodes.Mesh1166_7.geometry} material={materials['vray_PLASTIC::PVC::Opaque G2747rey']} />
      </group>
      <mesh geometry={nodes.cirlcelamp_lambert1_0.geometry} material={materials.lambert1} position={[-4.144, 2.186, -1.65]} rotation={[0, Math.PI / 2, 0]} scale={0.005} />
      <mesh geometry={nodes.ch_101.geometry} material={materials.ch01} position={[-4.821, 0, 3.368]} scale={0.007} />
      <mesh geometry={nodes.fish_200.geometry} material={materials.fis02} position={[-4.821, 0, 3.368]} scale={0.007} />
      <group position={[-4.821, 0, 3.368]} scale={0.007}>
        <mesh geometry={nodes.Mesh022.geometry} material={materials.PaletteMaterial003} />
        <mesh geometry={nodes.Mesh022_1.geometry} material={materials.PaletteMaterial004} />
        <mesh geometry={nodes.Mesh022_2.geometry} material={materials.PaletteMaterial005} />
      </group>
      <mesh geometry={nodes.nors_102.geometry} material={materials.sal01} position={[-4.821, 0, 3.368]} scale={0.007} />
      <mesh geometry={nodes.nos_202.geometry} material={materials.sal02} position={[-4.821, 0, 3.368]} scale={0.007} />
      <mesh geometry={nodes.nos_264.geometry} material={materials.fis01} position={[-4.821, 0, 3.368]} scale={0.007} />
      <mesh geometry={nodes.sos_102.geometry} material={materials.sos01} position={[-4.821, 0, 3.368]} scale={0.007} />
      <mesh geometry={nodes.turk_100.geometry} material={materials['turk 01']} position={[-4.821, 0, 3.368]} scale={0.007} />
      <mesh geometry={nodes.win_100.geometry} material={materials.wi01} position={[-4.821, 0, 3.368]} scale={0.007} />
      <group position={[-5.891, 1.034, -3.043]} rotation={[Math.PI / 2, 0, 0.005]} scale={0.001}>
        <mesh geometry={nodes.Mesh1161.geometry} material={materials['vray_Ref_Plane_Mat001.001']} />
        <mesh geometry={nodes.Mesh1161_1.geometry} material={materials['vray_Ref_Plane_Mat001.002']} />
        <mesh geometry={nodes.Mesh1161_2.geometry} material={materials['vray_Material #384248859']} />
      </group>
      <mesh geometry={nodes.SM_Fish1017.geometry} material={materials.M_Grocery2} position={[-6.412, 0.452, 1.625]} rotation={[-Math.PI, -0.746, -Math.PI]} scale={0.819} />
      <group position={[-6.635, -0.004, 1.644]} rotation={[0, -1.571, 0]} scale={0.819}>
        <mesh geometry={nodes.SM_StoreFreezer2_1.geometry} material={materials.M_Furniture1} />
        <mesh geometry={nodes.SM_StoreFreezer2_2.geometry} material={materials.PaletteMaterial007} />
      </group>
      <mesh geometry={nodes.Plane002.geometry} material={nodes.Plane002.material} position={[-1.373, 1.045, 1.392]} />
    </group>
  )
}

useGLTF.preload('VR/booth_thuysan-transformed.glb')
