/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./detmay/detmay.gltf --transform --types 
Files: ./detmay/detmay.gltf [341.56KB] > C:\Users\zatag\3d-viewer\public\VR\detmay-transformed.glb [21.7MB] (-6254%)
*/

import * as THREE from 'three'
import React, { JSX } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Plane001: THREE.Mesh
    Circle003: THREE.Mesh
    Plane010: THREE.Mesh
    Plane041: THREE.Mesh
    Plane041_1: THREE.Mesh
    Plane041_2: THREE.Mesh
    Plane041_3: THREE.Mesh
    Plane041_4: THREE.Mesh
    SM_Theft_Protection02_1: THREE.Mesh
    SM_Theft_Protection02_2: THREE.Mesh
    SM_Mannequin_05: THREE.Mesh
    SM_Mannequin_05_1: THREE.Mesh
    Woman_shoes: THREE.Mesh
    Woman_hairs: THREE.Mesh
    Adidas_cloth_set_128: THREE.Mesh
    Adidas_cloth_set_128_1: THREE.Mesh
    SM_Shoe_Box_03001: THREE.Mesh
    SM_Clothes_09002: THREE.Mesh
    SM_Clothes_042001: THREE.Mesh
    SM_Clothes_040005: THREE.Mesh
    SM_Clothes_036010: THREE.Mesh
    SM_Clothes_028: THREE.Mesh
    SM_Clothes_027001: THREE.Mesh
    SM_Clothes_02003: THREE.Mesh
    SM_Clothes_017003: THREE.Mesh
    SM_Bag_09: THREE.Mesh
    SM_Bag_05: THREE.Mesh
    SM_Bag_015: THREE.Mesh
    SM_Bag_013: THREE.Mesh
    SM_Bag_012: THREE.Mesh
    BP_Rack_Clothes_22: THREE.Mesh
    SM_Merged_Clothes10001: THREE.Mesh
    SM_Fitting_Room_01_1: THREE.Mesh
    SM_Fitting_Room_01_2: THREE.Mesh
    SM_Fitting_Room_01_3: THREE.Mesh
    SM_Clothes_052003: THREE.Mesh
    SM_Clothes_052002: THREE.Mesh
    SM_Merged_RackBag: THREE.Mesh
    Device05: THREE.Mesh
    Device03: THREE.Mesh
    Device02: THREE.Mesh
    Chair: THREE.Mesh
    BP_Table_01: THREE.Mesh
    SM_Lamp_06: THREE.Mesh
    SM_Lamp_06_1: THREE.Mesh
    SM_Lamp_4: THREE.Mesh
    SM_Potted_Plant: THREE.Mesh
    SM_Plant_01: THREE.Mesh
    Cube: THREE.Mesh
    Cube001: THREE.Mesh
    Cube002: THREE.Mesh
  }
  materials: {
    ['Material.007']: THREE.MeshStandardMaterial
    ['Material.001']: THREE.MeshStandardMaterial
    ['Material.008']: THREE.MeshStandardMaterial
    ['Material.002']: THREE.MeshStandardMaterial
    ['Material.003']: THREE.MeshStandardMaterial
    ['Material.004']: THREE.MeshStandardMaterial
    ['Material.005']: THREE.MeshStandardMaterial
    ['Material.006']: THREE.MeshStandardMaterial
    Inst_Bench_02: THREE.MeshStandardMaterial
    ['Material.009']: THREE.MeshStandardMaterial
    Inst_Plastic_03: THREE.MeshStandardMaterial
    Inst_Clothes_10: THREE.MeshStandardMaterial
    PaletteMaterial001: THREE.MeshStandardMaterial
    PaletteMaterial002: THREE.MeshStandardMaterial
    PaletteMaterial003: THREE.MeshStandardMaterial
    PaletteMaterial004: THREE.MeshStandardMaterial
    Inst_Boots_01: THREE.MeshStandardMaterial
    Inst_Clothes_03: THREE.MeshStandardMaterial
    Inst_Clothes_04: THREE.MeshStandardMaterial
    Inst_Clothes_05: THREE.MeshStandardMaterial
    Inst_Clothes_12: THREE.MeshStandardMaterial
    Inst_Clothes_07: THREE.MeshStandardMaterial
    Inst_Clothes_06: THREE.MeshStandardMaterial
    Inst_Clothes_02: THREE.MeshStandardMaterial
    Inst_Clothes_01: THREE.MeshStandardMaterial
    Inst_Boots_03: THREE.MeshStandardMaterial
    Inst_Boots_02: THREE.MeshStandardMaterial
    Inst_Hats_02: THREE.MeshStandardMaterial
    Inst_Hats_01: THREE.MeshStandardMaterial
    Inst_Hats_03: THREE.MeshStandardMaterial
    Inst_Rack_01: THREE.MeshStandardMaterial
    Inst_Rack_02: THREE.MeshStandardMaterial
    Inst_Fitting_Room: THREE.MeshStandardMaterial
    PaletteMaterial005: THREE.MeshStandardMaterial
    Inst_Bulb_03: THREE.MeshStandardMaterial
    Inst_Clothes_09: THREE.MeshStandardMaterial
    Inst_Clothes_08: THREE.MeshStandardMaterial
    Inst_Hats_04: THREE.MeshStandardMaterial
    Inst_Cash_Register_01: THREE.MeshStandardMaterial
    Inst_Keyboard_01: THREE.MeshStandardMaterial
    Inst_Cash_Register_Screen: THREE.MeshStandardMaterial
    Inst_Shopping_Counter_01: THREE.MeshStandardMaterial
    Inst_Pedestal_01: THREE.MeshStandardMaterial
    Inst_Lamp_01: THREE.MeshStandardMaterial
    PaletteMaterial006: THREE.MeshStandardMaterial
    Inst_Bulb_02: THREE.MeshStandardMaterial
    Inst_Flowerpot_01: THREE.MeshStandardMaterial
    Inst_Plant_01_SM_Plant_01: THREE.MeshStandardMaterial
    ['mood(2)']: THREE.MeshStandardMaterial
    ['mood(2).002']: THREE.MeshStandardMaterial
    ['mood(2).001']: THREE.MeshStandardMaterial
  }
  animations: any[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/VR/detmay-transformed.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Plane001.geometry} material={materials['Material.007']} position={[3.45, 1.492, 0]} rotation={[Math.PI, 0, Math.PI / 2]} scale={1.492} />
      <mesh geometry={nodes.Circle003.geometry} material={materials['Material.001']} position={[4.334, 0.346, 1.703]} rotation={[0, 0, -Math.PI / 2]} scale={[0.312, 0.265, 0.386]} />
      <mesh geometry={nodes.Plane010.geometry} material={materials['Material.008']} />
      <group position={[1.963, 2.336, 5.597]} rotation={[-Math.PI, -Math.PI / 2, 0]} scale={[0.081, 1.536, 2.334]}>
        <mesh geometry={nodes.Plane041.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.Plane041_1.geometry} material={materials['Material.003']} />
        <mesh geometry={nodes.Plane041_2.geometry} material={materials['Material.004']} />
        <mesh geometry={nodes.Plane041_3.geometry} material={materials['Material.005']} />
        <mesh geometry={nodes.Plane041_4.geometry} material={materials['Material.006']} />
      </group>
      <group position={[-4.704, 0, -3.258]} rotation={[0, 1.571, 0]} scale={[1.644, 0.647, 0.647]}>
        <mesh geometry={nodes.SM_Theft_Protection02_1.geometry} material={materials.Inst_Bench_02} />
        <mesh geometry={nodes.SM_Theft_Protection02_2.geometry} material={materials['Material.009']} />
      </group>
      <group position={[1.945, 0, -6.31]} rotation={[-Math.PI, 1.493, -Math.PI]}>
        <mesh geometry={nodes.SM_Mannequin_05.geometry} material={materials.Inst_Plastic_03} />
        <mesh geometry={nodes.SM_Mannequin_05_1.geometry} material={materials.Inst_Clothes_10} />
      </group>
      <mesh geometry={nodes.Woman_shoes.geometry} material={materials.PaletteMaterial001} position={[-4.236, 0, -4.607]} rotation={[0, -1.564, 0]} />
      <mesh geometry={nodes.Woman_hairs.geometry} material={materials.PaletteMaterial002} position={[-4.236, 0, -4.607]} rotation={[0, -1.564, 0]} />
      <group position={[-4.236, 0, -4.607]} rotation={[0, -1.564, 0]}>
        <mesh geometry={nodes.Adidas_cloth_set_128.geometry} material={materials.PaletteMaterial003} />
        <mesh geometry={nodes.Adidas_cloth_set_128_1.geometry} material={materials.PaletteMaterial004} />
      </group>
      <mesh geometry={nodes.SM_Shoe_Box_03001.geometry} material={materials.Inst_Boots_01} position={[-2.633, 0.316, -3.675]} rotation={[-Math.PI, 1.535, -Math.PI]} scale={[0.664, 0.76, 0.76]} />
      <mesh geometry={nodes.SM_Clothes_09002.geometry} material={materials.Inst_Clothes_03} position={[-2.643, 2.084, -3.708]} rotation={[-Math.PI, 1.437, -Math.PI]} scale={0.892} />
      <mesh geometry={nodes.SM_Clothes_042001.geometry} material={materials.Inst_Clothes_04} position={[-3.403, 1.294, -3.728]} rotation={[0, -0.375, 0]} scale={[0.892, 0.872, 0.892]} />
      <mesh geometry={nodes.SM_Clothes_040005.geometry} material={materials.Inst_Clothes_05} position={[-3.403, 1.294, -3.906]} rotation={[0, -0.623, 0]} scale={[0.892, 0.872, 0.892]} />
      <mesh geometry={nodes.SM_Clothes_036010.geometry} material={materials.Inst_Clothes_12} position={[-3.403, 1.294, -4.133]} rotation={[0, 0.332, 0]} scale={[0.892, 0.872, 0.892]} />
      <mesh geometry={nodes.SM_Clothes_028.geometry} material={materials.Inst_Clothes_07} position={[-2.514, 1.928, -5.313]} rotation={[-Math.PI, 1.521, -Math.PI]} scale={0.759} />
      <mesh geometry={nodes.SM_Clothes_027001.geometry} material={materials.Inst_Clothes_06} position={[-2.314, 1.928, -5.325]} rotation={[-Math.PI, 1.521, -Math.PI]} scale={0.759} />
      <mesh geometry={nodes.SM_Clothes_02003.geometry} material={materials.Inst_Clothes_02} position={[-2.343, 2.084, -3.709]} rotation={[-Math.PI, 1.521, -Math.PI]} scale={0.892} />
      <mesh geometry={nodes.SM_Clothes_017003.geometry} material={materials.Inst_Clothes_01} position={[-2.534, 2.085, -4.248]} rotation={[0, 1.561, 0]} scale={0.919} />
      <mesh geometry={nodes.SM_Bag_09.geometry} material={materials.Inst_Boots_03} position={[-3.279, 1.058, -5.155]} rotation={[0, -1.433, 0]} scale={[0.892, 0.872, 0.892]} />
      <mesh geometry={nodes.SM_Bag_05.geometry} material={materials.Inst_Boots_02} position={[-3.28, 0.444, -4.873]} rotation={[0, 1.167, -Math.PI]} scale={[-0.847, -0.771, -0.795]} />
      <mesh geometry={nodes.SM_Bag_015.geometry} material={materials.Inst_Hats_02} position={[-3.28, 1.682, -3.766]} rotation={[0, 1.551, -Math.PI]} scale={[-0.884, -0.872, -0.892]} />
      <mesh geometry={nodes.SM_Bag_013.geometry} material={materials.Inst_Hats_01} position={[-3.28, 1.682, -4.811]} rotation={[0, 1.551, -Math.PI]} scale={[-0.884, -0.872, -0.892]} />
      <mesh geometry={nodes.SM_Bag_012.geometry} material={materials.Inst_Hats_03} position={[-3.28, 1.682, -5.291]} rotation={[0, 1.551, -Math.PI]} scale={[-0.884, -0.872, -0.892]} />
      <mesh geometry={nodes.BP_Rack_Clothes_22.geometry} material={materials.Inst_Rack_01} position={[-2.998, 0.004, -6.723]} rotation={[0, -Math.PI / 2, 0]} scale={0.892} />
      <mesh geometry={nodes.SM_Merged_Clothes10001.geometry} material={materials.Inst_Rack_02} position={[-0.849, 0.012, -3.651]} />
      <group position={[0.565, 0, -3.728]} rotation={[-Math.PI, 0, -Math.PI]}>
        <mesh geometry={nodes.SM_Fitting_Room_01_1.geometry} material={materials.Inst_Fitting_Room} />
        <mesh geometry={nodes.SM_Fitting_Room_01_2.geometry} material={materials.PaletteMaterial005} />
        <mesh geometry={nodes.SM_Fitting_Room_01_3.geometry} material={materials.Inst_Bulb_03} />
      </group>
      <mesh geometry={nodes.SM_Clothes_052003.geometry} material={materials.Inst_Clothes_09} position={[3.468, 1.633, 2.216]} rotation={[-Math.PI, 1.551, -Math.PI]} />
      <mesh geometry={nodes.SM_Clothes_052002.geometry} material={materials.Inst_Clothes_08} position={[0.841, 1.635, 2.182]} rotation={[-Math.PI, 1.551, -Math.PI]} />
      <mesh geometry={nodes.SM_Merged_RackBag.geometry} material={materials.Inst_Hats_04} position={[-3.8, -0.018, 2.984]} rotation={[0, 1.571, 0]} />
      <mesh geometry={nodes.Device05.geometry} material={materials.Inst_Cash_Register_01} position={[-2.608, 0.882, -0.168]} rotation={[-Math.PI, 0.882, -Math.PI]} />
      <mesh geometry={nodes.Device03.geometry} material={materials.Inst_Keyboard_01} position={[-2.756, 0.882, 0.127]} rotation={[0, 1.561, 0]} />
      <mesh geometry={nodes.Device02.geometry} material={materials.Inst_Cash_Register_Screen} position={[-2.535, 0.882, 0.144]} rotation={[0, 1.561, 0]} />
      <mesh geometry={nodes.Chair.geometry} material={materials.Inst_Shopping_Counter_01} position={[-3.391, -0.016, -0.234]} rotation={[-Math.PI, 0.533, -Math.PI]} />
      <mesh geometry={nodes.BP_Table_01.geometry} material={materials.Inst_Pedestal_01} position={[-2.612, -0.016, -0.127]} rotation={[-Math.PI, 0.01, -Math.PI]} />
      <group position={[-2.909, 5.326, -4.792]}>
        <mesh geometry={nodes.SM_Lamp_06.geometry} material={materials.Inst_Lamp_01} />
        <mesh geometry={nodes.SM_Lamp_06_1.geometry} material={materials.PaletteMaterial006} />
      </group>
      <mesh geometry={nodes.SM_Lamp_4.geometry} material={materials.Inst_Bulb_02} position={[-2.405, 5.105, 4.512]} />
      <mesh geometry={nodes.SM_Potted_Plant.geometry} material={materials.Inst_Flowerpot_01} position={[-3.854, 1.691, 2.646]} scale={0.252} />
      <mesh geometry={nodes.SM_Plant_01.geometry} material={materials.Inst_Plant_01_SM_Plant_01} position={[-3.829, 1.826, 2.653]} scale={0.252} />
      <mesh geometry={nodes.Cube.geometry} material={materials['mood(2)']} position={[-5.002, 1.657, 0]} scale={[0.03, 0.374, 0.718]} />
      <mesh geometry={nodes.Cube001.geometry} material={materials['mood(2).002']} position={[-5.002, 1.657, 1.599]} scale={[0.03, 0.374, 0.718]} />
      <mesh geometry={nodes.Cube002.geometry} material={materials['mood(2).001']} position={[-5.002, 1.686, -1.63]} scale={[0.03, 0.374, 0.718]} />
    </group>
  )
}

useGLTF.preload('/VR/detmay-transformed.glb')
