/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\Food_v3.gltf --transform --types 
Files: .\Food_v3.gltf [328.22KB] > C:\Users\zatag\assets\Food_v3-transformed.glb [13.08MB] (-3884%)
*/

import * as THREE from 'three'
import React, { JSX } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    bamboo: THREE.Mesh
    banana_006002: THREE.Mesh
    carrot_001002: THREE.Mesh
    Circle: THREE.Mesh
    Circle004: THREE.Mesh
    Circle004_1: THREE.Mesh
    Circle008: THREE.Mesh
    Mesh948: THREE.Mesh
    Mesh948_1: THREE.Mesh
    Cube006: THREE.Mesh
    cucumber_017002: THREE.Mesh
    eggplant_011: THREE.Mesh
    Mesh1161: THREE.Mesh
    Mesh1161_1: THREE.Mesh
    Mesh1161_2: THREE.Mesh
    Mesh1161_3: THREE.Mesh
    Mesh1161_4: THREE.Mesh
    Mesh1161_5: THREE.Mesh
    Mesh1161_6: THREE.Mesh
    Mesh1161_7: THREE.Mesh
    Mesh1161_8: THREE.Mesh
    Mesh1161_9: THREE.Mesh
    garnet_034003: THREE.Mesh
    Ground_midle: THREE.Mesh
    ['Mis-vf']: THREE.Mesh
    papaya_011003: THREE.Mesh
    pear_041003: THREE.Mesh
    pear_120003: THREE.Mesh
    ['Pots_Pot-83_A_spring-summer-autumn-winter007']: THREE.Mesh
    ['Pots_Pot-83_A_spring-summer-autumn-winter007_1']: THREE.Mesh
    ['Pots_Pot-83_A_spring-summer-autumn-winter007_2']: THREE.Mesh
    ['Pots_Pot-83_A_spring-summer-autumn-winter007_3']: THREE.Mesh
    ['Pots_Pot-83_A_spring-summer-autumn-winter007_4']: THREE.Mesh
    ['Pots_Pot-83_A_spring-summer-autumn-winter007_5']: THREE.Mesh
    ['Pots_Pot-83_A_spring-summer-autumn-winter007_6']: THREE.Mesh
    ['Pots_Pot-83_A_spring-summer-autumn-winter007_7']: THREE.Mesh
    potatoes_057002: THREE.Mesh
    ['C-shelf_wood_1#8']: THREE.Mesh
    ['C-shelf_wood_1#8_1']: THREE.Mesh
    shelf001: THREE.Mesh
    shelf002: THREE.Mesh
    shelf003: THREE.Mesh
    shelf004: THREE.Mesh
    shelf005: THREE.Mesh
    shelf006: THREE.Mesh
    Object015002: THREE.Mesh
    Object015002_1: THREE.Mesh
    cgaxis_models_64_14_10: THREE.Mesh
    cgaxis_models_64_14_10_1: THREE.Mesh
    showcase03001: THREE.Mesh
    showcase03002: THREE.Mesh
    showcase03003: THREE.Mesh
    showcase03004: THREE.Mesh
    showcase03005: THREE.Mesh
    showcase03006: THREE.Mesh
    Text: THREE.Mesh
    tomato034002: THREE.Mesh
    Plane: THREE.Mesh
    Cube: THREE.Mesh
    Box001: THREE.Mesh
    price_tag006_1: THREE.Mesh
    price_tag006_2: THREE.Mesh
    ['1cucumber091003']: THREE.Mesh
    carrot157003: THREE.Mesh
    celery015003: THREE.Mesh
    garlic230003: THREE.Mesh
    ginger031003: THREE.Mesh
    lzucchini010003: THREE.Mesh
    mushroom096003: THREE.Mesh
    new_potato119003: THREE.Mesh
    onion083003: THREE.Mesh
    Plane005: THREE.Mesh
    Vegetable001: THREE.Mesh
  }
  materials: {
    bamboo: THREE.MeshStandardMaterial
    ['Material #2143578923']: THREE.MeshStandardMaterial
    carrot: THREE.MeshStandardMaterial
    PaletteMaterial001: THREE.MeshStandardMaterial
    PaletteMaterial002: THREE.MeshStandardMaterial
    PaletteMaterial003: THREE.MeshStandardMaterial
    S1: THREE.MeshStandardMaterial
    corn_green: THREE.MeshStandardMaterial
    PaletteMaterial004: THREE.MeshStandardMaterial
    Bamboo: THREE.MeshStandardMaterial
    cucumber: THREE.MeshStandardMaterial
    eggplant: THREE.MeshStandardMaterial
    ['vray_Ref_Plane_Mat001.001']: THREE.MeshStandardMaterial
    vray_Ref_Plane_Mat001: THREE.MeshStandardMaterial
    ['vray_Ref_Plane_Mat001.002']: THREE.MeshStandardMaterial
    ['vray_Material #384248859']: THREE.MeshStandardMaterial
    ['vray_METAL::Smooth::Chrome Satin']: THREE.MeshStandardMaterial
    ['vray_METAL::Smooth::Steel24']: THREE.MeshStandardMaterial
    ['vray_PLASTIC::PVC::Opaque Gr24ey']: THREE.MeshStandardMaterial
    ['vray_METAL::Smooth::Steel']: THREE.MeshStandardMaterial
    ['vray_PLASTIC::PVC::Opaque Grey247']: THREE.MeshStandardMaterial
    ['vray_PLASTIC::PVC::Opaque G2747rey']: THREE.MeshStandardMaterial
    garnet: THREE.MeshStandardMaterial
    PaletteMaterial005: THREE.MeshStandardMaterial
    wood_light: THREE.MeshStandardMaterial
    papaya: THREE.MeshStandardMaterial
    pear_yellow: THREE.MeshStandardMaterial
    pear_green: THREE.MeshStandardMaterial
    PaletteMaterial006: THREE.MeshStandardMaterial
    PaletteMaterial007: THREE.MeshStandardMaterial
    Branch_1: THREE.MeshStandardMaterial
    Branch_2: THREE.MeshStandardMaterial
    Branch_3: THREE.MeshStandardMaterial
    Leaf_1: THREE.MeshStandardMaterial
    Leaf_2: THREE.MeshStandardMaterial
    Leaf_3: THREE.MeshStandardMaterial
    potatoes: THREE.MeshStandardMaterial
    Plywood_C_50cm: THREE.MeshStandardMaterial
    ['storage basket']: THREE.MeshStandardMaterial
    ['pexels-photo-1313267']: THREE.MeshStandardMaterial
    ee14c22e9800997a474536eadc93a1a8: THREE.MeshStandardMaterial
    ['cabbage-soup-diet-1']: THREE.MeshStandardMaterial
    ['photo tomato skin']: THREE.MeshStandardMaterial
    ['photo {3d75f229-7087-b44d-b407-5d2c7250592e}']: THREE.MeshStandardMaterial
    ['photo corn bits']: THREE.MeshStandardMaterial
    PaletteMaterial008: THREE.MeshStandardMaterial
    ['Material #1762816531']: THREE.MeshStandardMaterial
    PaletteMaterial009: THREE.MeshStandardMaterial
    cgaxis_models_64_14_01: THREE.MeshStandardMaterial
    cgaxis_models_64_14_04: THREE.MeshStandardMaterial
    cgaxis_models_64_14_06: THREE.MeshStandardMaterial
    cgaxis_models_64_14_03: THREE.MeshStandardMaterial
    cgaxis_models_64_14_02: THREE.MeshStandardMaterial
    cgaxis_models_64_14_05: THREE.MeshStandardMaterial
    cgaxis_models_64_14_07: THREE.MeshStandardMaterial
    tomato: THREE.MeshStandardMaterial
    ['Material.004']: THREE.MeshStandardMaterial
    ['Material.003']: THREE.MeshStandardMaterial
    wood: THREE.MeshStandardMaterial
    Price05: THREE.MeshStandardMaterial
    Price03: THREE.MeshStandardMaterial
    ['1cucumber']: THREE.MeshStandardMaterial
    ['carrot.001']: THREE.MeshStandardMaterial
    celery: THREE.MeshStandardMaterial
    garlic: THREE.MeshStandardMaterial
    ginger: THREE.MeshStandardMaterial
    light_zucchini: THREE.MeshStandardMaterial
    mushroom: THREE.MeshStandardMaterial
    new_potato: THREE.MeshStandardMaterial
    onion: THREE.MeshStandardMaterial
    LCD03: THREE.MeshStandardMaterial
    ['vray 01 - Default']: THREE.MeshStandardMaterial
  }
  animations: any[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/VR/food-transformed.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.bamboo.geometry} material={materials.bamboo} />
      <mesh geometry={nodes.banana_006002.geometry} material={materials['Material #2143578923']} position={[0.645, 0.919, 8.103]} rotation={[0, 1.571, 0]} scale={0.001} />
      <mesh geometry={nodes.carrot_001002.geometry} material={materials.carrot} position={[-0.478, 0.997, 8.024]} rotation={[0, 1.571, 0]} scale={0.001} />
      <mesh geometry={nodes.Circle.geometry} material={materials.PaletteMaterial001} rotation={[0, 0.161, 0]} />
      <group position={[0, 12.591, 0]}>
        <mesh geometry={nodes.Circle004.geometry} material={materials.PaletteMaterial002} />
        <mesh geometry={nodes.Circle004_1.geometry} material={materials.PaletteMaterial003} />
      </group>
      <mesh geometry={nodes.Circle008.geometry} material={materials.S1} position={[0, 9.572, 0]} scale={6.431} />
      <group position={[0.771, 0.86, 7.65]} rotation={[0, 1.571, 0]} scale={0.001}>
        <mesh geometry={nodes.Mesh948.geometry} material={materials.corn_green} />
        <mesh geometry={nodes.Mesh948_1.geometry} material={materials.PaletteMaterial004} />
      </group>
      <mesh geometry={nodes.Cube006.geometry} material={materials.Bamboo} position={[4.218, 0, 4.555]} />
      <mesh geometry={nodes.cucumber_017002.geometry} material={materials.cucumber} position={[-0.233, 0.964, 8.389]} rotation={[0, 1.571, 0]} scale={0.001} />
      <mesh geometry={nodes.eggplant_011.geometry} material={materials.eggplant} position={[-0.539, 0.919, -3.67]} rotation={[0, 1.571, 0]} scale={0.001} />
      <group position={[2.445, -0.093, -0.47]}>
        <mesh geometry={nodes.Mesh1161.geometry} material={materials['vray_Ref_Plane_Mat001.001']} />
        <mesh geometry={nodes.Mesh1161_1.geometry} material={materials.vray_Ref_Plane_Mat001} />
        <mesh geometry={nodes.Mesh1161_2.geometry} material={materials['vray_Ref_Plane_Mat001.002']} />
        <mesh geometry={nodes.Mesh1161_3.geometry} material={materials['vray_Material #384248859']} />
        <mesh geometry={nodes.Mesh1161_4.geometry} material={materials['vray_METAL::Smooth::Chrome Satin']} />
        <mesh geometry={nodes.Mesh1161_5.geometry} material={materials['vray_METAL::Smooth::Steel24']} />
        <mesh geometry={nodes.Mesh1161_6.geometry} material={materials['vray_PLASTIC::PVC::Opaque Gr24ey']} />
        <mesh geometry={nodes.Mesh1161_7.geometry} material={materials['vray_METAL::Smooth::Steel']} />
        <mesh geometry={nodes.Mesh1161_8.geometry} material={materials['vray_PLASTIC::PVC::Opaque Grey247']} />
        <mesh geometry={nodes.Mesh1161_9.geometry} material={materials['vray_PLASTIC::PVC::Opaque G2747rey']} />
      </group>
      <mesh geometry={nodes.garnet_034003.geometry} material={materials.garnet} position={[0.781, 0.924, 7.135]} rotation={[0, 1.571, 0]} scale={0.001} />
      <mesh geometry={nodes.Ground_midle.geometry} material={materials.PaletteMaterial005} position={[0, 0.147, 0]} />
      <mesh geometry={nodes['Mis-vf'].geometry} material={materials.wood_light} position={[0.162, 0, -2.823]} rotation={[0, 1.571, 0]} />
      <mesh geometry={nodes.papaya_011003.geometry} material={materials.papaya} position={[0.531, 0.94, 7.284]} rotation={[0, 1.571, 0]} scale={0.001} />
      <mesh geometry={nodes.pear_041003.geometry} material={materials.pear_yellow} position={[-0.391, 0.962, 6.817]} rotation={[0, 1.571, 0]} scale={0.001} />
      <mesh geometry={nodes.pear_120003.geometry} material={materials.pear_green} position={[-0.127, 0.994, 7.017]} rotation={[0, 1.571, 0]} scale={0.001} />
      <group position={[4.198, 0, 5.248]} rotation={[0, -0.205, 0]}>
        <mesh geometry={nodes['Pots_Pot-83_A_spring-summer-autumn-winter007'].geometry} material={materials.PaletteMaterial006} />
        <mesh geometry={nodes['Pots_Pot-83_A_spring-summer-autumn-winter007_1'].geometry} material={materials.PaletteMaterial007} />
        <mesh geometry={nodes['Pots_Pot-83_A_spring-summer-autumn-winter007_2'].geometry} material={materials.Branch_1} />
        <mesh geometry={nodes['Pots_Pot-83_A_spring-summer-autumn-winter007_3'].geometry} material={materials.Branch_2} />
        <mesh geometry={nodes['Pots_Pot-83_A_spring-summer-autumn-winter007_4'].geometry} material={materials.Branch_3} />
        <mesh geometry={nodes['Pots_Pot-83_A_spring-summer-autumn-winter007_5'].geometry} material={materials.Leaf_1} />
        <mesh geometry={nodes['Pots_Pot-83_A_spring-summer-autumn-winter007_6'].geometry} material={materials.Leaf_2} />
        <mesh geometry={nodes['Pots_Pot-83_A_spring-summer-autumn-winter007_7'].geometry} material={materials.Leaf_3} />
      </group>
      <mesh geometry={nodes.potatoes_057002.geometry} material={materials.potatoes} position={[-0.044, 0.906, 8.572]} rotation={[0, 1.571, 0]} scale={0.001} />
      <group position={[0.132, 0.001, 5.318]} scale={1.125}>
        <mesh geometry={nodes['C-shelf_wood_1#8'].geometry} material={materials.Plywood_C_50cm} />
        <mesh geometry={nodes['C-shelf_wood_1#8_1'].geometry} material={materials['storage basket']} />
      </group>
      <mesh geometry={nodes.shelf001.geometry} material={materials['pexels-photo-1313267']} position={[0.132, 0.001, 5.318]} scale={1.125} />
      <mesh geometry={nodes.shelf002.geometry} material={materials.ee14c22e9800997a474536eadc93a1a8} position={[0.132, 0.001, 5.318]} scale={1.125} />
      <mesh geometry={nodes.shelf003.geometry} material={materials['cabbage-soup-diet-1']} position={[0.132, 0.001, 5.318]} scale={1.125} />
      <mesh geometry={nodes.shelf004.geometry} material={materials['photo tomato skin']} position={[0.132, 0.001, 5.318]} scale={1.125} />
      <mesh geometry={nodes.shelf005.geometry} material={materials['photo {3d75f229-7087-b44d-b407-5d2c7250592e}']} position={[0.132, 0.001, 5.318]} scale={1.125} />
      <mesh geometry={nodes.shelf006.geometry} material={materials['photo corn bits']} position={[0.132, 0.001, 5.318]} scale={1.125} />
      <group position={[1.012, -0.031, 1.206]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object015002.geometry} material={materials.PaletteMaterial008} />
        <mesh geometry={nodes.Object015002_1.geometry} material={materials['Material #1762816531']} />
      </group>
      <group position={[5.678, 0.038, 0.397]} rotation={[0, Math.PI / 2, 0]} scale={0.029}>
        <mesh geometry={nodes.cgaxis_models_64_14_10.geometry} material={materials.PaletteMaterial009} />
        <mesh geometry={nodes.cgaxis_models_64_14_10_1.geometry} material={materials.cgaxis_models_64_14_01} />
      </group>
      <mesh geometry={nodes.showcase03001.geometry} material={materials.cgaxis_models_64_14_04} position={[5.678, 0.038, 0.397]} rotation={[0, Math.PI / 2, 0]} scale={0.029} />
      <mesh geometry={nodes.showcase03002.geometry} material={materials.cgaxis_models_64_14_06} position={[5.678, 0.038, 0.397]} rotation={[0, Math.PI / 2, 0]} scale={0.029} />
      <mesh geometry={nodes.showcase03003.geometry} material={materials.cgaxis_models_64_14_03} position={[5.678, 0.038, 0.397]} rotation={[0, Math.PI / 2, 0]} scale={0.029} />
      <mesh geometry={nodes.showcase03004.geometry} material={materials.cgaxis_models_64_14_02} position={[5.678, 0.038, 0.397]} rotation={[0, Math.PI / 2, 0]} scale={0.029} />
      <mesh geometry={nodes.showcase03005.geometry} material={materials.cgaxis_models_64_14_05} position={[5.678, 0.038, 0.397]} rotation={[0, Math.PI / 2, 0]} scale={0.029} />
      <mesh geometry={nodes.showcase03006.geometry} material={materials.cgaxis_models_64_14_07} position={[5.678, 0.038, 0.397]} rotation={[0, Math.PI / 2, 0]} scale={0.029} />
      <mesh geometry={nodes.Text.geometry} material={nodes.Text.material} position={[4.228, 4.568, 0.616]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.411} />
      <mesh geometry={nodes.tomato034002.geometry} material={materials.tomato} position={[0.41, 0.98, 8.286]} rotation={[0, 1.571, 0]} scale={0.001} />
      <mesh geometry={nodes.Plane.geometry} material={materials['Material.004']} position={[5.323, 1.656, 0.111]} rotation={[0, 0, -0.469]} />
      <mesh geometry={nodes.Cube.geometry} material={materials['Material.003']} />
      <mesh geometry={nodes.Box001.geometry} material={materials.wood} position={[4.3, 0.825, -8.233]} rotation={[0, Math.PI / 2, 0]} />
      <group position={[4.868, 1.179, -7.085]} rotation={[Math.PI / 2, 0, -Math.PI / 2]}>
        <mesh geometry={nodes.price_tag006_1.geometry} material={materials.Price05} />
        <mesh geometry={nodes.price_tag006_2.geometry} material={materials.Price03} />
      </group>
      <mesh geometry={nodes['1cucumber091003'].geometry} material={materials['1cucumber']} position={[4.389, 1.248, 8.226]} rotation={[-2.408, 0.189, -2.731]} />
      <mesh geometry={nodes.carrot157003.geometry} material={materials['carrot.001']} position={[4.803, 0.9, 8.306]} rotation={[-2.709, 1.482, 2.876]} />
      <mesh geometry={nodes.celery015003.geometry} material={materials.celery} position={[4.021, 1.505, 8.04]} rotation={[2.796, -0.471, 1.914]} />
      <mesh geometry={nodes.garlic230003.geometry} material={materials.garlic} position={[4.601, 1.103, 7.467]} rotation={[-0.369, -1.289, 2.043]} />
      <mesh geometry={nodes.ginger031003.geometry} material={materials.ginger} position={[4.928, 0.922, 7.361]} rotation={[0.968, 0.455, 2.305]} />
      <mesh geometry={nodes.lzucchini010003.geometry} material={materials.light_zucchini} position={[4.205, 1.477, 6.231]} rotation={[-1.505, -1.125, 1.676]} />
      <mesh geometry={nodes.mushroom096003.geometry} material={materials.mushroom} position={[4.913, 0.982, 6.131]} rotation={[0.133, 0.375, 0.892]} />
      <mesh geometry={nodes.new_potato119003.geometry} material={materials.new_potato} position={[4.562, 1.182, 6.602]} rotation={[1.091, 0.415, -1.738]} />
      <mesh geometry={nodes.onion083003.geometry} material={materials.onion} position={[4.079, 1.627, 7.276]} rotation={[0.874, 0.732, -1.182]} />
      <mesh geometry={nodes.Plane005.geometry} material={materials.LCD03} position={[-8.512, 0.619, -0.029]} rotation={[0, -Math.PI / 2, 0]} />
      <mesh geometry={nodes.Vegetable001.geometry} material={materials['vray 01 - Default']} position={[1.001, 0.968, 1.484]} rotation={[Math.PI / 2, 0, 0]} scale={0.001} />
    </group>
  )
}

useGLTF.preload('/VR/food-transformed.glb')
