/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./thucong/thucong.gltf --transform --types 
Files: ./thucong/thucong.gltf [418.3KB] > C:\Users\zatag\3d-viewer\public\VR\thucong-transformed.glb [12.7MB] (-2937%)
*/

import * as THREE from 'three'
import React, { JSX } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Plane: THREE.Mesh
    Plane030: THREE.Mesh
    Plane031: THREE.Mesh
    Plane054: THREE.Mesh
    Plane054_1: THREE.Mesh
    Cube009: THREE.Mesh
    Cube011: THREE.Mesh
    Cube013: THREE.Mesh
    Cube015: THREE.Mesh
    Mesh001: THREE.Mesh
    Mesh001_1: THREE.Mesh
    ['Coco_Republic_Markson_Dining_Chair_&_Flex_Dining_Table_001002']: THREE.Mesh
    Showcase03_049: THREE.Mesh
    Cube006: THREE.Mesh
    SM_Vase_4: THREE.Mesh
    SM_Vase_6: THREE.Mesh
    SM_Vase_1: THREE.Mesh
    SM_Vase_5: THREE.Mesh
    Plane063: THREE.Mesh
    Plane063_1: THREE.Mesh
    Plane063_2: THREE.Mesh
    Plane063_3: THREE.Mesh
    Plane063_4: THREE.Mesh
    Plane063_5: THREE.Mesh
    Plane063_6: THREE.Mesh
    Plane070: THREE.Mesh
    Plane070_1: THREE.Mesh
    Plane070_2: THREE.Mesh
    Plane070_3: THREE.Mesh
    Plane070_4: THREE.Mesh
    Plane070_5: THREE.Mesh
    Plane070_6: THREE.Mesh
    Plane036: THREE.Mesh
    Cone001: THREE.Mesh
    ['107984_BALI_PENDANT_1L_NATURE_001']: THREE.Mesh
    Helix001: THREE.Mesh
    Object_1: THREE.Mesh
    Object_1_1: THREE.Mesh
    defaultMaterial: THREE.Mesh
  }
  materials: {
    ['Material.001']: THREE.MeshStandardMaterial
    PaletteMaterial001: THREE.MeshStandardMaterial
    M_Kitchen_Decor_1_Wood: THREE.MeshStandardMaterial
    ['Material.007']: THREE.MeshStandardMaterial
    PaletteMaterial002: THREE.MeshStandardMaterial
    ['Material.026']: THREE.MeshStandardMaterial
    ['Material.025']: THREE.MeshStandardMaterial
    ['Material.024']: THREE.MeshStandardMaterial
    ['Material.005']: THREE.MeshStandardMaterial
    ['Material #21435675721712']: THREE.MeshStandardMaterial
    ['Material #2143574204']: THREE.MeshStandardMaterial
    ['Material #2143574355']: THREE.MeshStandardMaterial
    PaletteMaterial003: THREE.MeshStandardMaterial
    ['Material.006']: THREE.MeshStandardMaterial
    PaletteMaterial004: THREE.MeshStandardMaterial
    M_Decor_9: THREE.MeshStandardMaterial
    M_Vase_1: THREE.MeshStandardMaterial
    M_Vase_5: THREE.MeshStandardMaterial
    ['Material.009']: THREE.MeshStandardMaterial
    ['Material.010']: THREE.MeshStandardMaterial
    ['Material.011']: THREE.MeshStandardMaterial
    ['Material.012']: THREE.MeshStandardMaterial
    ['Material.013']: THREE.MeshStandardMaterial
    ['Material.015']: THREE.MeshStandardMaterial
    ['Material.016']: THREE.MeshStandardMaterial
    ['Material.023']: THREE.MeshStandardMaterial
    ['Material.019']: THREE.MeshStandardMaterial
    ['Material.021']: THREE.MeshStandardMaterial
    ['Material.020']: THREE.MeshStandardMaterial
    ['Material.022']: THREE.MeshStandardMaterial
    ['Material.018']: THREE.MeshStandardMaterial
    ['Material.017']: THREE.MeshStandardMaterial
    PaletteMaterial005: THREE.MeshPhysicalMaterial
    PaletteMaterial006: THREE.MeshStandardMaterial
    PaletteMaterial007: THREE.MeshStandardMaterial
    lambert3SG: THREE.MeshStandardMaterial
    lambert2SG: THREE.MeshStandardMaterial
    DefaultMaterial: THREE.MeshStandardMaterial
  }
  animations: any[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/VR/thucong-transformed.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Plane.geometry} material={materials['Material.001']} />
      <mesh geometry={nodes.Plane030.geometry} material={materials.PaletteMaterial001} />
      <mesh geometry={nodes.Plane031.geometry} material={materials.M_Kitchen_Decor_1_Wood} />
      <mesh geometry={nodes.Cube009.geometry} material={materials['Material.026']} />
      <mesh geometry={nodes.Cube011.geometry} material={materials['Material.025']} />
      <mesh geometry={nodes.Cube013.geometry} material={materials['Material.024']} />
      <mesh geometry={nodes.Cube015.geometry} material={materials['Material.005']} />
      <mesh geometry={nodes['Coco_Republic_Markson_Dining_Chair_&_Flex_Dining_Table_001002'].geometry} material={materials['Material #2143574355']} />
      <mesh geometry={nodes.Showcase03_049.geometry} material={materials.PaletteMaterial003} />
      <mesh geometry={nodes.Cube006.geometry} material={materials['Material.006']} />
      <mesh geometry={nodes.SM_Vase_4.geometry} material={materials.PaletteMaterial004} />
      <mesh geometry={nodes.SM_Vase_6.geometry} material={materials.M_Decor_9} />
      <mesh geometry={nodes.SM_Vase_1.geometry} material={materials.M_Vase_1} />
      <mesh geometry={nodes.SM_Vase_5.geometry} material={materials.M_Vase_5} />
      <mesh geometry={nodes.Plane036.geometry} material={nodes.Plane036.material} />
      <mesh geometry={nodes.Cone001.geometry} material={materials.PaletteMaterial005} />
      <mesh geometry={nodes['107984_BALI_PENDANT_1L_NATURE_001'].geometry} material={materials.PaletteMaterial006} />
      <mesh geometry={nodes.Helix001.geometry} material={materials.PaletteMaterial007} />
      <group position={[5.632, 0.125, 0.974]} rotation={[-Math.PI / 2, 0, 0]} scale={0.174}>
        <mesh geometry={nodes.Object_1.geometry} material={materials.lambert3SG} />
        <mesh geometry={nodes.Object_1_1.geometry} material={materials.lambert2SG} />
      </group>
      <mesh geometry={nodes.defaultMaterial.geometry} material={materials.DefaultMaterial} />
      <mesh geometry={nodes.Plane054.geometry} material={materials['Material.007']} />
      <mesh geometry={nodes.Plane054_1.geometry} material={materials.PaletteMaterial002} />
      <mesh geometry={nodes.Mesh001.geometry} material={materials['Material #21435675721712']} />
      <mesh geometry={nodes.Mesh001_1.geometry} material={materials['Material #2143574204']} />
      <mesh geometry={nodes.Plane063.geometry} material={materials['Material.009']} />
      <mesh geometry={nodes.Plane063_1.geometry} material={materials['Material.010']} />
      <mesh geometry={nodes.Plane063_2.geometry} material={materials['Material.011']} />
      <mesh geometry={nodes.Plane063_3.geometry} material={materials['Material.012']} />
      <mesh geometry={nodes.Plane063_4.geometry} material={materials['Material.013']} />
      <mesh geometry={nodes.Plane063_5.geometry} material={materials['Material.015']} />
      <mesh geometry={nodes.Plane063_6.geometry} material={materials['Material.016']} />
      <mesh geometry={nodes.Plane070.geometry} material={materials['Material.023']} />
      <mesh geometry={nodes.Plane070_1.geometry} material={materials['Material.019']} />
      <mesh geometry={nodes.Plane070_2.geometry} material={materials['Material.021']} />
      <mesh geometry={nodes.Plane070_3.geometry} material={materials['Material.020']} />
      <mesh geometry={nodes.Plane070_4.geometry} material={materials['Material.022']} />
      <mesh geometry={nodes.Plane070_5.geometry} material={materials['Material.018']} />
      <mesh geometry={nodes.Plane070_6.geometry} material={materials['Material.017']} />
    </group>
  )
}

useGLTF.preload('/VR/thucong-transformed.glb')
