/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\thucong_v2\thucong_v2.gltf --transform --types -s 
Files: .\thucong_v2\thucong_v2.gltf [145.33KB] > C:\Users\zatag\assets\thucong_v2-transformed.glb [4.96MB] (-3316%)
*/

import * as THREE from 'three'
import React, { JSX } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Mesh005: THREE.Mesh
    Mesh005_1: THREE.Mesh
    Mesh011: THREE.Mesh
    Mesh011_1: THREE.Mesh
    Cube: THREE.Mesh
    Cube006: THREE.Mesh
    Cube011: THREE.Mesh
    Cube013: THREE.Mesh
    Cube015: THREE.Mesh
    Cube002: THREE.Mesh
    Cube002_1: THREE.Mesh
    Cube002_2: THREE.Mesh
    Cube002_3: THREE.Mesh
    Cube002_4: THREE.Mesh
    Cube002_5: THREE.Mesh
    Mall_055: THREE.Mesh
    Plane: THREE.Mesh
    Plane032: THREE.Mesh
    Plane063: THREE.Mesh
    Plane063_1: THREE.Mesh
    Plane063_2: THREE.Mesh
    Plane063_3: THREE.Mesh
    Plane101: THREE.Mesh
    Plane101_1: THREE.Mesh
  }
  materials: {
    ['Material #2143574355']: THREE.MeshStandardMaterial
    PaletteMaterial001: THREE.MeshStandardMaterial
    ['Material #21435675721712']: THREE.MeshStandardMaterial
    ['Material #2143574204']: THREE.MeshStandardMaterial
    PaletteMaterial002: THREE.MeshStandardMaterial
    ['Material.006']: THREE.MeshStandardMaterial
    ['Material.025']: THREE.MeshStandardMaterial
    ['Material.024']: THREE.MeshStandardMaterial
    ['Material.005']: THREE.MeshStandardMaterial
    ['Material.020']: THREE.MeshStandardMaterial
    M_Kitchen_Decor_1_Wood: THREE.MeshStandardMaterial
    ['Material.010']: THREE.MeshStandardMaterial
    ['Material.011']: THREE.MeshStandardMaterial
    ['Material.012']: THREE.MeshStandardMaterial
    ['Material.018']: THREE.MeshStandardMaterial
    PaletteMaterial003: THREE.MeshStandardMaterial
    ['Material.001']: THREE.MeshStandardMaterial
    ['Material.007']: THREE.MeshStandardMaterial
    ['Material.009']: THREE.MeshStandardMaterial
    ['Material.013']: THREE.MeshStandardMaterial
    ['Material.015']: THREE.MeshStandardMaterial
    ['Material.016']: THREE.MeshStandardMaterial
    ['Material.023']: THREE.MeshStandardMaterial
    ['Material.019']: THREE.MeshStandardMaterial
  }
  animations: any[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/VR/thucong-transformed.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[-1.683, -0.002, 0.602]}>
        <mesh castShadow receiveShadow geometry={nodes.Mesh005.geometry} material={materials['Material #2143574355']} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh005_1.geometry} material={materials.PaletteMaterial001} />
      </group>
      <group position={[-2.722, 0.006, 0.471]} rotation={[0, 1.571, 0]}>
        <mesh castShadow receiveShadow geometry={nodes.Mesh011.geometry} material={materials['Material #21435675721712']} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh011_1.geometry} material={materials['Material #2143574204']} />
      </group>
      <mesh castShadow receiveShadow geometry={nodes.Cube.geometry} material={materials.PaletteMaterial002} position={[0, -0.061, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.Cube006.geometry} material={materials['Material.006']} />
      <mesh castShadow receiveShadow geometry={nodes.Cube011.geometry} material={materials['Material.025']} />
      <mesh castShadow receiveShadow geometry={nodes.Cube013.geometry} material={materials['Material.024']} />
      <mesh castShadow receiveShadow geometry={nodes.Cube015.geometry} material={materials['Material.005']} />
      <group position={[0.732, -0.022, 0.014]}>
        <mesh castShadow receiveShadow geometry={nodes.Cube002.geometry} material={materials['Material.020']} />
        <mesh castShadow receiveShadow geometry={nodes.Cube002_1.geometry} material={materials.M_Kitchen_Decor_1_Wood} />
        <mesh castShadow receiveShadow geometry={nodes.Cube002_2.geometry} material={materials['Material.010']} />
        <mesh castShadow receiveShadow geometry={nodes.Cube002_3.geometry} material={materials['Material.011']} />
        <mesh castShadow receiveShadow geometry={nodes.Cube002_4.geometry} material={materials['Material.012']} />
        <mesh castShadow receiveShadow geometry={nodes.Cube002_5.geometry} material={materials['Material.018']} />
      </group>
      <mesh castShadow receiveShadow geometry={nodes.Mall_055.geometry} material={materials.PaletteMaterial003} position={[3.196, 0.77, 4.343]} />
      <mesh castShadow receiveShadow geometry={nodes.Plane.geometry} material={materials['Material.001']} position={[1.893, -0.21, 4.285]} />
      <mesh castShadow receiveShadow geometry={nodes.Plane032.geometry} material={materials['Material.007']} />
      <group position={[-5.638, 0, 3.23]}>
        <mesh castShadow receiveShadow geometry={nodes.Plane063.geometry} material={materials['Material.009']} />
        <mesh castShadow receiveShadow geometry={nodes.Plane063_1.geometry} material={materials['Material.013']} />
        <mesh castShadow receiveShadow geometry={nodes.Plane063_2.geometry} material={materials['Material.015']} />
        <mesh castShadow receiveShadow geometry={nodes.Plane063_3.geometry} material={materials['Material.016']} />
      </group>
      <group position={[-0.295, 1.595, -1.542]}>
        <mesh castShadow receiveShadow geometry={nodes.Plane101.geometry} material={materials['Material.023']} />
        <mesh castShadow receiveShadow geometry={nodes.Plane101_1.geometry} material={materials['Material.019']} />
      </group>
    </group>
  )
}

