/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./way/way.gltf --transform --types 
Files: ./way/way.gltf [2.12KB] > C:\Users\zatag\3d-viewer\public\VR\way-transformed.glb [27.5KB] (-1197%)
*/

import * as THREE from 'three'
import React, { JSX } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    ['Asset_2@5x']: THREE.Mesh
  }
  materials: {
    ['Asset 2@5x.001']: THREE.MeshStandardMaterial
  }
  animations: any[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('VR/way-transformed.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['Asset_2@5x'].geometry} material={materials['Asset 2@5x.001']} position={[0, 0, 9.37]} scale={[80.129, 80.129, 83.196]} />
    </group>
  )
}

