/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/wood/wood.gltf --transform --types 
Files: ./public/wood/wood.gltf [323.98KB] > C:\Users\zatag\3d-viewer\wood-transformed.glb [24.86MB] (-7572%)
*/

import * as THREE from 'three'
import React, { JSX } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Plane: THREE.Mesh
    Cube008: THREE.Mesh
    Cube008_1: THREE.Mesh
    Cube008_2: THREE.Mesh
    Cylinder001: THREE.Mesh
    Mesh1166: THREE.Mesh
    Mesh1166_1: THREE.Mesh
    Mesh1166_2: THREE.Mesh
    Mesh1166_3: THREE.Mesh
    Mesh1166_4: THREE.Mesh
    Mesh1166_5: THREE.Mesh
    Mesh1167: THREE.Mesh
    Mesh1167_1: THREE.Mesh
    Mesh1167_2: THREE.Mesh
    Mesh1167_3: THREE.Mesh
    Sofa_leg_1: THREE.Mesh
    Sofa_leg_2: THREE.Mesh
    Mesh1169: THREE.Mesh
    Mesh1169_1: THREE.Mesh
    Plane9385_1: THREE.Mesh
    Plane9385_2: THREE.Mesh
    Plane006: THREE.Mesh
    Cube032: THREE.Mesh
    Cube032_1: THREE.Mesh
    Cube032_2: THREE.Mesh
    Plane036: THREE.Mesh
    Plane036_1: THREE.Mesh
    Line46253471: THREE.Mesh
    Box9787: THREE.Mesh
    Box9786: THREE.Mesh
    Box9785: THREE.Mesh
    Box9782: THREE.Mesh
    Box9779: THREE.Mesh
    Box9776: THREE.Mesh
    Box9773: THREE.Mesh
    Box9770: THREE.Mesh
    Box9766: THREE.Mesh
    Box9768: THREE.Mesh
    Box9646: THREE.Mesh
    Box9638: THREE.Mesh
    Box9635: THREE.Mesh
    Box9627: THREE.Mesh
    Box9625: THREE.Mesh
    Box9623: THREE.Mesh
    Box9621: THREE.Mesh
    Box9619: THREE.Mesh
    Box9633: THREE.Mesh
    Box9631: THREE.Mesh
    Box9493: THREE.Mesh
    Box9492: THREE.Mesh
    Box9489: THREE.Mesh
    Box9487: THREE.Mesh
    Box9483: THREE.Mesh
    Box9481: THREE.Mesh
    Box9477: THREE.Mesh
    Box9473: THREE.Mesh
    Box9465: THREE.Mesh
    Box9461: THREE.Mesh
    Box9457: THREE.Mesh
    Box9452: THREE.Mesh
    Box9450: THREE.Mesh
    Box9448: THREE.Mesh
    Box9447: THREE.Mesh
    Box9441: THREE.Mesh
    Box9433: THREE.Mesh
    Box9420: THREE.Mesh
    Cube037: THREE.Mesh
    Cube037_1: THREE.Mesh
    Mesh1171: THREE.Mesh
    Mesh1171_1: THREE.Mesh
    Plane007: THREE.Mesh
    leatherChair001: THREE.Mesh
  }
  materials: {
    concrete_floor_worn_001: THREE.MeshStandardMaterial
    plastered_wall_04: THREE.MeshStandardMaterial
    PaletteMaterial001: THREE.MeshStandardMaterial
    ['Material.011']: THREE.MeshStandardMaterial
    laminate_floor: THREE.MeshStandardMaterial
    PaletteMaterial002: THREE.MeshStandardMaterial
    ['leaf.004']: THREE.MeshStandardMaterial
    ['leaf.002']: THREE.MeshStandardMaterial
    ['leaf.003']: THREE.MeshStandardMaterial
    ['leaf.005']: THREE.MeshStandardMaterial
    ['leaf.006']: THREE.MeshStandardMaterial
    ['Material #2143574355']: THREE.MeshStandardMaterial
    PaletteMaterial003: THREE.MeshStandardMaterial
    ['Material #21435675721712']: THREE.MeshStandardMaterial
    ['Material #2143574204']: THREE.MeshStandardMaterial
    Admiral021: THREE.MeshStandardMaterial
    PaletteMaterial004: THREE.MeshStandardMaterial
    laminate_floor_02: THREE.MeshStandardMaterial
    ['soil PLANT15032020']: THREE.MeshStandardMaterial
    ['BUMBOO 07042020']: THREE.MeshStandardMaterial
    ['BUMBOO 1 07042020']: THREE.MeshStandardMaterial
    wood_floor: THREE.MeshStandardMaterial
    Door_Material: THREE.MeshStandardMaterial
    PaletteMaterial005: THREE.MeshPhysicalMaterial
    PaletteMaterial006: THREE.MeshPhysicalMaterial
    PaletteMaterial007: THREE.MeshStandardMaterial
    PaletteMaterial008: THREE.MeshStandardMaterial
    Podnoj: THREE.MeshStandardMaterial
    ['Atl Verh 5']: THREE.MeshStandardMaterial
    PaletteMaterial009: THREE.MeshStandardMaterial
    Atl3: THREE.MeshStandardMaterial
    Atl5: THREE.MeshStandardMaterial
    Atl6: THREE.MeshStandardMaterial
    Atl13: THREE.MeshStandardMaterial
    Atl8: THREE.MeshStandardMaterial
    Atl9: THREE.MeshStandardMaterial
    Atl10: THREE.MeshStandardMaterial
    ['Atl Logo']: THREE.MeshStandardMaterial
    ['Box.021']: THREE.MeshStandardMaterial
    NakleyCork: THREE.MeshStandardMaterial
    ['Box.030']: THREE.MeshStandardMaterial
    ['Box.026']: THREE.MeshStandardMaterial
    ['Box.025']: THREE.MeshStandardMaterial
    ['Box.024']: THREE.MeshStandardMaterial
    ['Box.023']: THREE.MeshStandardMaterial
    ['Box.022']: THREE.MeshStandardMaterial
    ['Box.029']: THREE.MeshStandardMaterial
    ['Box.028']: THREE.MeshStandardMaterial
    ['Box.004']: THREE.MeshStandardMaterial
    ['Eg-Nakl']: THREE.MeshStandardMaterial
    ['Box.002']: THREE.MeshStandardMaterial
    ['Box.016']: THREE.MeshStandardMaterial
    ['Box.014']: THREE.MeshStandardMaterial
    ['Box.013']: THREE.MeshStandardMaterial
    ['Box.011']: THREE.MeshStandardMaterial
    ['Box.009']: THREE.MeshStandardMaterial
    ['Box.005']: THREE.MeshStandardMaterial
    ['Box.003']: THREE.MeshStandardMaterial
    ['Box.001']: THREE.MeshStandardMaterial
    Box: THREE.MeshStandardMaterial
    ['Box.020']: THREE.MeshStandardMaterial
    NakleyWB: THREE.MeshStandardMaterial
    ['Material.019']: THREE.MeshStandardMaterial
    ['Material.022']: THREE.MeshStandardMaterial
    ['Material.026']: THREE.MeshStandardMaterial
    ['Material.028']: THREE.MeshStandardMaterial
    main: THREE.MeshStandardMaterial
    ['Material.029']: THREE.MeshStandardMaterial
    metal_Leg: THREE.MeshStandardMaterial
    leather_white: THREE.MeshStandardMaterial
    LCD05: THREE.MeshStandardMaterial
    leather_dark: THREE.MeshStandardMaterial
  }
  animations: any[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/VR/wood-transformed.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Plane.geometry} material={materials.concrete_floor_worn_001} scale={[5, 1, 7]} />
      <group position={[-5.031, 5.107, 7.007]} scale={0.342}>
        <mesh geometry={nodes.Cube008.geometry} material={materials.plastered_wall_04} />
        <mesh geometry={nodes.Cube008_1.geometry} material={materials.PaletteMaterial001} />
        <mesh geometry={nodes.Cube008_2.geometry} material={materials['Material.011']} />
      </group>
      <mesh geometry={nodes.Cylinder001.geometry} material={materials.laminate_floor} position={[-2.395, 5.752, 5.506]} scale={0.916} />
      <group position={[-4.445, 2.223, 0.107]} rotation={[0, Math.PI / 2, 0]} scale={[1.879, 2.061, 1.879]}>
        <mesh geometry={nodes.Mesh1166.geometry} material={materials.PaletteMaterial002} />
        <mesh geometry={nodes.Mesh1166_1.geometry} material={materials['leaf.004']} />
        <mesh geometry={nodes.Mesh1166_2.geometry} material={materials['leaf.002']} />
        <mesh geometry={nodes.Mesh1166_3.geometry} material={materials['leaf.003']} />
        <mesh geometry={nodes.Mesh1166_4.geometry} material={materials['leaf.005']} />
        <mesh geometry={nodes.Mesh1166_5.geometry} material={materials['leaf.006']} />
      </group>
      <group position={[2.746, 0, 2.633]} scale={0.001}>
        <mesh geometry={nodes.Mesh1167.geometry} material={materials['Material #2143574355']} />
        <mesh geometry={nodes.Mesh1167_1.geometry} material={materials.PaletteMaterial003} />
        <mesh geometry={nodes.Mesh1167_2.geometry} material={materials['Material #21435675721712']} />
        <mesh geometry={nodes.Mesh1167_3.geometry} material={materials['Material #2143574204']} />
      </group>
      <group position={[2.595, -0.004, 6.147]} rotation={[Math.PI, 0, Math.PI]} scale={1.38}>
        <mesh geometry={nodes.Sofa_leg_1.geometry} material={materials.Admiral021} />
        <mesh geometry={nodes.Sofa_leg_2.geometry} material={materials.PaletteMaterial004} />
      </group>
      <group position={[4.077, -0.66, 5.285]} rotation={[Math.PI, -1.57, 0]}>
        <mesh geometry={nodes.Mesh1169.geometry} material={materials.laminate_floor_02} />
        <mesh geometry={nodes.Mesh1169_1.geometry} material={materials['soil PLANT15032020']} />
      </group>
      <group position={[4.077, 0.828, 6.62]} rotation={[0, -0.035, 0]}>
        <mesh geometry={nodes.Plane9385_1.geometry} material={materials['BUMBOO 07042020']} />
        <mesh geometry={nodes.Plane9385_2.geometry} material={materials['BUMBOO 1 07042020']} />
      </group>
      <mesh geometry={nodes.Plane006.geometry} material={materials.wood_floor} scale={[5, 1, 7]} />
      <group position={[-3.981, 1.888, 5.685]} rotation={[0, 1.571, 0]}>
        <mesh geometry={nodes.Cube032.geometry} material={materials.Door_Material} />
        <mesh geometry={nodes.Cube032_1.geometry} material={materials.PaletteMaterial005} />
        <mesh geometry={nodes.Cube032_2.geometry} material={materials.PaletteMaterial006} />
      </group>
      <group position={[-3.905, 0.122, 6.116]} rotation={[-Math.PI / 2, 0, Math.PI / 2]}>
        <mesh geometry={nodes.Plane036.geometry} material={materials.PaletteMaterial007} />
        <mesh geometry={nodes.Plane036_1.geometry} material={materials.PaletteMaterial008} />
      </group>
      <mesh geometry={nodes.Line46253471.geometry} material={materials.Podnoj} position={[4.697, 0.042, -2.091]} rotation={[0, -1.509, 0]} scale={5.812} />
      <mesh geometry={nodes.Box9787.geometry} material={materials['Atl Verh 5']} position={[3.705, 0.815, -2.276]} rotation={[0, -1.509, 0]} scale={5.812} />
      <mesh geometry={nodes.Box9786.geometry} material={materials.PaletteMaterial009} position={[3.846, 0.395, -2.046]} rotation={[0, -1.509, 0]} scale={5.812} />
      <mesh geometry={nodes.Box9785.geometry} material={materials.Atl3} position={[3.56, 0.209, -2.01]} rotation={[0, -1.509, 0]} scale={5.812} />
      <mesh geometry={nodes.Box9782.geometry} material={materials.Atl5} position={[3.557, 0.215, -2.046]} rotation={[0, -1.509, 0]} scale={5.812} />
      <mesh geometry={nodes.Box9779.geometry} material={materials.Atl6} position={[3.555, 0.222, -2.082]} rotation={[0, -1.509, 0]} scale={5.812} />
      <mesh geometry={nodes.Box9776.geometry} material={materials.Atl13} position={[3.553, 0.228, -2.118]} rotation={[0, -1.509, 0]} scale={5.812} />
      <mesh geometry={nodes.Box9773.geometry} material={materials.Atl8} position={[3.551, 0.234, -2.154]} rotation={[0, -1.509, 0]} scale={5.812} />
      <mesh geometry={nodes.Box9770.geometry} material={materials.Atl9} position={[3.549, 0.24, -2.19]} rotation={[0, -1.509, 0]} scale={5.812} />
      <mesh geometry={nodes.Box9766.geometry} material={materials.Atl10} position={[3.546, 0.246, -2.226]} rotation={[0, -1.509, 0]} scale={5.812} />
      <mesh geometry={nodes.Box9768.geometry} material={materials['Atl Logo']} position={[3.576, 0.989, -2.268]} rotation={[0, -1.509, 0]} scale={5.812} />
      <mesh geometry={nodes.Box9646.geometry} material={materials['Box.021']} position={[4.912, 0.509, -2.35]} rotation={[0, -1.509, 0]} scale={5.812} />
      <mesh geometry={nodes.Box9638.geometry} material={materials.NakleyCork} position={[4.921, 0.509, -2.202]} rotation={[0, -1.509, 0]} scale={5.812} />
      <mesh geometry={nodes.Box9635.geometry} material={materials['Box.030']} position={[4.847, -0.015, -2.06]} rotation={[0, -1.509, 0]} scale={5.812} />
      <mesh geometry={nodes.Box9627.geometry} material={materials['Box.026']} position={[4.857, -0.015, -1.912]} rotation={[0, -1.509, 0]} scale={5.812} />
      <mesh geometry={nodes.Box9625.geometry} material={materials['Box.025']} position={[4.86, -0.015, -1.875]} rotation={[0, -1.509, 0]} scale={5.812} />
      <mesh geometry={nodes.Box9623.geometry} material={materials['Box.024']} position={[4.862, -0.015, -1.838]} rotation={[0, -1.509, 0]} scale={5.812} />
      <mesh geometry={nodes.Box9621.geometry} material={materials['Box.023']} position={[4.864, -0.015, -1.801]} rotation={[0, -1.509, 0]} scale={5.812} />
      <mesh geometry={nodes.Box9619.geometry} material={materials['Box.022']} position={[4.867, -0.015, -1.764]} rotation={[0, -1.509, 0]} scale={5.812} />
      <mesh geometry={nodes.Box9633.geometry} material={materials['Box.029']} position={[4.85, -0.015, -2.023]} rotation={[0, -1.509, 0]} scale={5.812} />
      <mesh geometry={nodes.Box9631.geometry} material={materials['Box.028']} position={[4.852, -0.015, -1.986]} rotation={[0, -1.509, 0]} scale={5.812} />
      <mesh geometry={nodes.Box9493.geometry} material={materials['Box.004']} position={[4.187, 0.164, -2.081]} rotation={[0, -1.509, 0]} scale={5.812} />
      <mesh geometry={nodes.Box9492.geometry} material={materials['Eg-Nakl']} position={[4.05, 0.135, -1.986]} rotation={[0, -1.509, 0]} scale={5.812} />
      <mesh geometry={nodes.Box9489.geometry} material={materials['Box.002']} position={[4.186, 0.254, -2.092]} rotation={[0, -1.509, 0]} scale={5.812} />
      <mesh geometry={nodes.Box9487.geometry} material={materials['Box.016']} position={[4.186, 0.299, -2.097]} rotation={[0, -1.509, 0]} scale={5.812} />
      <mesh geometry={nodes.Box9483.geometry} material={materials['Box.014']} position={[4.185, 0.389, -2.108]} rotation={[0, -1.509, 0]} scale={5.812} />
      <mesh geometry={nodes.Box9481.geometry} material={materials['Box.013']} position={[4.185, 0.434, -2.114]} rotation={[0, -1.509, 0]} scale={5.812} />
      <mesh geometry={nodes.Box9477.geometry} material={materials['Box.011']} position={[4.184, 0.524, -2.125]} rotation={[0, -1.509, 0]} scale={5.812} />
      <mesh geometry={nodes.Box9473.geometry} material={materials['Box.009']} position={[4.183, 0.614, -2.136]} rotation={[0, -1.509, 0]} scale={5.812} />
      <mesh geometry={nodes.Box9465.geometry} material={materials['Box.005']} position={[4.182, 0.794, -2.158]} rotation={[0, -1.509, 0]} scale={5.812} />
      <mesh geometry={nodes.Box9461.geometry} material={materials['Box.003']} position={[4.181, 0.884, -2.169]} rotation={[0, -1.509, 0]} scale={5.812} />
      <mesh geometry={nodes.Box9457.geometry} material={materials['Box.001']} position={[4.18, 0.974, -2.18]} rotation={[0, -1.509, 0]} scale={5.812} />
      <mesh geometry={nodes.Box9452.geometry} material={materials.Box} position={[4.18, 1.019, -2.186]} rotation={[0, -1.509, 0]} scale={5.812} />
      <mesh geometry={nodes.Box9450.geometry} material={materials['Box.020']} position={[4.181, 0.054, -2.167]} rotation={[0, -1.509, 0]} scale={5.812} />
      <mesh geometry={nodes.Box9448.geometry} material={materials.NakleyWB} position={[4.651, 0.525, -2.319]} rotation={[0, -1.509, 0]} scale={5.812} />
      <mesh geometry={nodes.Box9447.geometry} material={materials['Material.019']} position={[4.594, 0.03, -2.168]} rotation={[0, -1.509, 0]} scale={5.812} />
      <mesh geometry={nodes.Box9441.geometry} material={materials['Material.022']} position={[4.598, 0.018, -2.106]} rotation={[0, -1.509, 0]} scale={5.812} />
      <mesh geometry={nodes.Box9433.geometry} material={materials['Material.026']} position={[4.603, 0.004, -2.023]} rotation={[0, -1.509, 0]} scale={5.812} />
      <mesh geometry={nodes.Box9420.geometry} material={materials['Material.028']} position={[4.606, -0.002, -1.982]} rotation={[0, -1.509, 0]} scale={5.812} />
      <group position={[-2.031, 0.386, 4.531]} rotation={[0, -1.571, 0]} scale={1.169}>
        <mesh geometry={nodes.Cube037.geometry} material={materials.main} />
        <mesh geometry={nodes.Cube037_1.geometry} material={materials['Material.029']} />
      </group>
      <group position={[1.848, 0, 4.754]}>
        <mesh geometry={nodes.Mesh1171.geometry} material={materials.metal_Leg} />
        <mesh geometry={nodes.Mesh1171_1.geometry} material={materials.leather_white} />
      </group>
      <mesh geometry={nodes.Plane007.geometry} material={materials.LCD05} position={[-6.913, 0.619, -0.029]} rotation={[0, -Math.PI / 2, 0]} scale={[1.451, 1.296, 1.296]} />
      <mesh geometry={nodes.leatherChair001.geometry} material={materials.leather_dark} position={[-2.62, 0.027, 4.637]} rotation={[0, -0.626, 0]} scale={1.107} />
    </group>
  )
}

