/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\wood.gltf --transform --types -s 
Files: .\wood.gltf [429.21KB] > C:\Users\zatag\assets\wood-transformed.glb [11.66MB] (-2618%)
*/

import * as THREE from 'three'
import React, { JSX } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Floor_wood: THREE.Mesh
    Mesh002: THREE.Mesh
    Mesh002_1: THREE.Mesh
    Mesh002_2: THREE.Mesh
    Mesh002_3: THREE.Mesh
    Mesh002_4: THREE.Mesh
    Mesh002_5: THREE.Mesh
    Mesh371: THREE.Mesh
    Mesh371_1: THREE.Mesh
    Mesh371_2: THREE.Mesh
    Mesh371_3: THREE.Mesh
    Mesh371_4: THREE.Mesh
    Mesh371_5: THREE.Mesh
    Mesh371_6: THREE.Mesh
    Mesh371_7: THREE.Mesh
    Plane: THREE.Mesh
    Plane003: THREE.Mesh
    Plane003_1: THREE.Mesh
    Plane003_2: THREE.Mesh
    Plane011: THREE.Mesh
    Plane011_1: THREE.Mesh
    Plane011_2: THREE.Mesh
    Plane011_3: THREE.Mesh
    Sofa_leg_1: THREE.Mesh
    Sofa_leg_2: THREE.Mesh
    Sofa_leg_3: THREE.Mesh
    Sofa_leg_4: THREE.Mesh
    Box002001: THREE.Mesh
    Box002001_1: THREE.Mesh
    Box002001_2: THREE.Mesh
    Box002001_3: THREE.Mesh
    Box002001_4: THREE.Mesh
    Box002001_5: THREE.Mesh
    Box002001_6: THREE.Mesh
    Box002001_7: THREE.Mesh
    Box002001_8: THREE.Mesh
    Box002001_9: THREE.Mesh
    Box002001_10: THREE.Mesh
    Box002001_11: THREE.Mesh
    Box002001_12: THREE.Mesh
    Box002001_13: THREE.Mesh
    Cube001: THREE.Mesh
    Cube024: THREE.Mesh
    Line001_1: THREE.Mesh
    Line001_2: THREE.Mesh
    Line2132555006: THREE.Mesh
    Line2132555006_1: THREE.Mesh
    Line2132555006_2: THREE.Mesh
    Line2132555006_3: THREE.Mesh
    Line2132555006_4: THREE.Mesh
    Line2132555006_5: THREE.Mesh
    Line2132555006_6: THREE.Mesh
    Line2132555006_7: THREE.Mesh
    Line2132555006_8: THREE.Mesh
    Line2132555006_9: THREE.Mesh
    Line2132555006_10: THREE.Mesh
    Line2132555006_11: THREE.Mesh
    Line2132555006_12: THREE.Mesh
    Plane007: THREE.Mesh
    Bosch_HBG6764S6B_001: THREE.Mesh
    Bosch_HBG6764S6B_004: THREE.Mesh
    Bosch_HBG6764S6B_022: THREE.Mesh
    Box002: THREE.Mesh
    Box012: THREE.Mesh
    Plane001: THREE.Mesh
    Mat01_152003: THREE.Mesh
    Mat01_152003_1: THREE.Mesh
    Box9419_1: THREE.Mesh
    Box9419_2: THREE.Mesh
    Box9419_3: THREE.Mesh
    Box9419_4: THREE.Mesh
    Box9419_5: THREE.Mesh
    Box9419_6: THREE.Mesh
    Box9419_7: THREE.Mesh
    Box9419_8: THREE.Mesh
    Box9419_9: THREE.Mesh
    Box9419_10: THREE.Mesh
    Box9449_1: THREE.Mesh
    Box9449_2: THREE.Mesh
    Box9449_3: THREE.Mesh
    Box9449_4: THREE.Mesh
    Box9449_5: THREE.Mesh
    Box9449_6: THREE.Mesh
    Box9449_7: THREE.Mesh
    Box9449_8: THREE.Mesh
    Box9449_9: THREE.Mesh
    Box9449_10: THREE.Mesh
    Box9449_11: THREE.Mesh
    Box9616_1: THREE.Mesh
    Box9616_2: THREE.Mesh
    Box9616_3: THREE.Mesh
    Box9616_4: THREE.Mesh
    Box9616_5: THREE.Mesh
    Box9616_6: THREE.Mesh
    Box9616_7: THREE.Mesh
    Box9616_8: THREE.Mesh
    Box9647: THREE.Mesh
    Box9762_1: THREE.Mesh
    Box9762_2: THREE.Mesh
    Box9762_3: THREE.Mesh
    Box9762_4: THREE.Mesh
    Box9762_5: THREE.Mesh
    Box9762_6: THREE.Mesh
    Box9762_7: THREE.Mesh
    Box9768: THREE.Mesh
    Box9787: THREE.Mesh
    Object2111141009: THREE.Mesh
    Object2111141018_1: THREE.Mesh
    Object2111141018_2: THREE.Mesh
    Object2111141018_3: THREE.Mesh
    Object2111141018_4: THREE.Mesh
    Object2111141018_5: THREE.Mesh
    Object2111141018_6: THREE.Mesh
    Object2111141018_7: THREE.Mesh
    Object2111141533: THREE.Mesh
    Rectangle2133442562_1: THREE.Mesh
    Rectangle2133442562_2: THREE.Mesh
    Rectangle2133442562_3: THREE.Mesh
    Rectangle2133442562_4: THREE.Mesh
    Rectangle2133442562_5: THREE.Mesh
    Rectangle2133442562_6: THREE.Mesh
    Rectangle2133442562_7: THREE.Mesh
    Rectangle2133442562_8: THREE.Mesh
    Rectangle2133442562_9: THREE.Mesh
    Rectangle2133442562_10: THREE.Mesh
    Rectangle2133442562_11: THREE.Mesh
    Object2111140313_1: THREE.Mesh
    Object2111140313_2: THREE.Mesh
    Object2111140313_3: THREE.Mesh
    Object2111140313_4: THREE.Mesh
    Object2111140313_5: THREE.Mesh
    Object2111140313_6: THREE.Mesh
    Object2111140313_7: THREE.Mesh
    Rectangle2133442128_1: THREE.Mesh
    Rectangle2133442128_2: THREE.Mesh
    Rectangle2133442273: THREE.Mesh
  }
  materials: {
    wood_floor: THREE.MeshStandardMaterial
    PaletteMaterial003: THREE.MeshStandardMaterial
    ['leaf.004']: THREE.MeshStandardMaterial
    ['leaf.002']: THREE.MeshStandardMaterial
    ['leaf.003']: THREE.MeshStandardMaterial
    ['leaf.005']: THREE.MeshStandardMaterial
    ['leaf.006']: THREE.MeshStandardMaterial
    PaletteMaterial004: THREE.MeshStandardMaterial
    ['PhysicalMaterial.112']: THREE.MeshStandardMaterial
    ['PhysicalMaterial.115']: THREE.MeshStandardMaterial
    ['PhysicalMaterial.116']: THREE.MeshStandardMaterial
    ['PhysicalMaterial.117']: THREE.MeshStandardMaterial
    ['PhysicalMaterial.118']: THREE.MeshStandardMaterial
    ['PhysicalMaterial.119']: THREE.MeshStandardMaterial
    ['PhysicalMaterial.120']: THREE.MeshStandardMaterial
    concrete_floor_worn_001: THREE.MeshStandardMaterial
    PaletteMaterial005: THREE.MeshStandardMaterial
    laminate_floor: THREE.MeshStandardMaterial
    ['Material.002']: THREE.MeshStandardMaterial
    PaletteMaterial006: THREE.MeshStandardMaterial
    PaletteMaterial008: THREE.MeshStandardMaterial
    Door_Material: THREE.MeshStandardMaterial
    PaletteMaterial007: THREE.MeshPhysicalMaterial
    PaletteMaterial010: THREE.MeshStandardMaterial
    metal_Leg: THREE.MeshStandardMaterial
    PaletteMaterial009: THREE.MeshStandardMaterial
    PaletteMaterial011: THREE.MeshStandardMaterial
    PaletteMaterial017: THREE.MeshStandardMaterial
    PaletteMaterial018: THREE.MeshStandardMaterial
    ['Kafel1.001']: THREE.MeshStandardMaterial
    ['Kafel2.001']: THREE.MeshStandardMaterial
    ['Kafel3.001']: THREE.MeshStandardMaterial
    ['Kafel4.001']: THREE.MeshStandardMaterial
    ['Kafel5.001']: THREE.MeshStandardMaterial
    ['Kafel7.001']: THREE.MeshStandardMaterial
    ['Kafel8.001']: THREE.MeshStandardMaterial
    ['Kafel9.001']: THREE.MeshStandardMaterial
    ['Kafel10.001']: THREE.MeshStandardMaterial
    ['Kafel12.001']: THREE.MeshStandardMaterial
    ['Kafel13.001']: THREE.MeshStandardMaterial
    ['Kafel14.001']: THREE.MeshStandardMaterial
    plastered_wall_04: THREE.MeshStandardMaterial
    PaletteMaterial019: THREE.MeshPhysicalMaterial
    ['vray Material #36.001']: THREE.MeshStandardMaterial
    ['vray Material #136.001']: THREE.MeshStandardMaterial
    PaletteMaterial001: THREE.MeshStandardMaterial
    PaletteMaterial002: THREE.MeshStandardMaterial
    山东色板展示03: THREE.MeshStandardMaterial
    山东色板展示10: THREE.MeshStandardMaterial
    山东色板展示02: THREE.MeshStandardMaterial
    山东色板展示11: THREE.MeshStandardMaterial
    山东色板展示01: THREE.MeshStandardMaterial
    山东色板展示08: THREE.MeshStandardMaterial
    山东色板展示05: THREE.MeshStandardMaterial
    山东色板展示09: THREE.MeshStandardMaterial
    山东色板展示06: THREE.MeshStandardMaterial
    山东色板展示04: THREE.MeshStandardMaterial
    山东色板展示07: THREE.MeshStandardMaterial
    LCD05: THREE.MeshStandardMaterial
    PaletteMaterial012: THREE.MeshPhysicalMaterial
    wire_115115115: THREE.MeshPhysicalMaterial
    wire_086086086: THREE.MeshPhysicalMaterial
    wire_038032026: THREE.MeshPhysicalMaterial
    PaletteMaterial013: THREE.MeshPhysicalMaterial
    wire_005005005: THREE.MeshPhysicalMaterial
    wire_177028149: THREE.MeshPhysicalMaterial
    ['Material.003']: THREE.MeshStandardMaterial
    Podnoj: THREE.MeshStandardMaterial
    ['Material.019']: THREE.MeshStandardMaterial
    ['Material.017']: THREE.MeshStandardMaterial
    ['Material.013']: THREE.MeshStandardMaterial
    ['Material.018']: THREE.MeshStandardMaterial
    NakleyWB: THREE.MeshStandardMaterial
    ['Material.016']: THREE.MeshStandardMaterial
    ['Material.015']: THREE.MeshStandardMaterial
    ['Material.014']: THREE.MeshStandardMaterial
    ['Material.012']: THREE.MeshStandardMaterial
    ['Box.020']: THREE.MeshStandardMaterial
    Box: THREE.MeshStandardMaterial
    ['Eg-Nakl']: THREE.MeshStandardMaterial
    ['Box.001']: THREE.MeshStandardMaterial
    ['Box.002']: THREE.MeshStandardMaterial
    ['Box.003']: THREE.MeshStandardMaterial
    ['Box.004']: THREE.MeshStandardMaterial
    ['Box.005']: THREE.MeshStandardMaterial
    ['Box.009']: THREE.MeshStandardMaterial
    ['Box.011']: THREE.MeshStandardMaterial
    ['Box.013']: THREE.MeshStandardMaterial
    NakleyCork: THREE.MeshStandardMaterial
    ['Box.022']: THREE.MeshStandardMaterial
    ['Box.023']: THREE.MeshStandardMaterial
    ['Box.024']: THREE.MeshStandardMaterial
    ['Box.025']: THREE.MeshStandardMaterial
    ['Box.026']: THREE.MeshStandardMaterial
    ['Box.030']: THREE.MeshStandardMaterial
    ['Box.021']: THREE.MeshStandardMaterial
    PaletteMaterial014: THREE.MeshStandardMaterial
    Atl10: THREE.MeshStandardMaterial
    Atl9: THREE.MeshStandardMaterial
    Atl8: THREE.MeshStandardMaterial
    Atl13: THREE.MeshStandardMaterial
    Atl6: THREE.MeshStandardMaterial
    Atl5: THREE.MeshStandardMaterial
    Atl3: THREE.MeshStandardMaterial
    ['Atl Logo']: THREE.MeshStandardMaterial
    ['Atl Verh 5']: THREE.MeshStandardMaterial
    PaletteMaterial015: THREE.MeshStandardMaterial
    ['4dddddddddddd']: THREE.MeshStandardMaterial
    Mat3d6wewewe: THREE.MeshStandardMaterial
    Matsdfdsfsdfsdf: THREE.MeshStandardMaterial
    ['00401aghj']: THREE.MeshStandardMaterial
    山东色板展示06dfdfdf: THREE.MeshStandardMaterial
    ['00401asdfdsf']: THREE.MeshStandardMaterial
    ['4dddd878787878']: THREE.MeshStandardMaterial
    山东dddddddddddd: THREE.MeshStandardMaterial
    ['45sd4545454545']: THREE.MeshStandardMaterial
    山东dddddddddddddddd: THREE.MeshStandardMaterial
    ['4545sdsd']: THREE.MeshStandardMaterial
    ['Material #5dfdfffff']: THREE.MeshStandardMaterial
    山ededdddssssffggsdsd: THREE.MeshStandardMaterial
    山ededdddssssffgg: THREE.MeshStandardMaterial
    山ededd: THREE.MeshStandardMaterial
    PaletteMaterial016: THREE.MeshStandardMaterial
    ['45sd4545454545dfdf']: THREE.MeshStandardMaterial
    ['Material #-2147483648']: THREE.MeshStandardMaterial
    ['4dddd878787878dfdf']: THREE.MeshStandardMaterial
    PaletteMaterial020: THREE.MeshStandardMaterial
    ['7sssssssssssssssdsd']: THREE.MeshStandardMaterial
    ['Mat3d66-718222-10-8417']: THREE.MeshStandardMaterial
    PaletteMaterial021: THREE.MeshStandardMaterial
    ['Mat3d66-7dsfdsgdfg']: THREE.MeshStandardMaterial
    ['Mat3d66-718222-6-224']: THREE.MeshStandardMaterial
    ['Mat3d66-718222-8-704']: THREE.MeshStandardMaterial
    dddfdffgfgfg: THREE.MeshStandardMaterial
    dddfdffgdfdgfghjhjhjhjfgfgf: THREE.MeshStandardMaterial
    dddfdffgdfdgfghjhjhjhjfgfgdfdfdf: THREE.MeshStandardMaterial
  }
  animations: any[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/VR/wood-transformed.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.Floor_wood.geometry} material={materials.wood_floor} position={[0, 0.2, 0]} />
      <group position={[-4.445, 2.423, 0.107]} rotation={[0, Math.PI / 2, 0]} scale={[1.879, 2.061, 1.879]}>
        <mesh castShadow receiveShadow geometry={nodes.Mesh002.geometry} material={materials.PaletteMaterial003} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh002_1.geometry} material={materials['leaf.004']} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh002_2.geometry} material={materials['leaf.002']} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh002_3.geometry} material={materials['leaf.003']} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh002_4.geometry} material={materials['leaf.005']} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh002_5.geometry} material={materials['leaf.006']} />
      </group>
      <group position={[-0.431, 0.186, 6.374]} rotation={[Math.PI, 0, Math.PI]}>
        <mesh castShadow receiveShadow geometry={nodes.Mesh371.geometry} material={materials.PaletteMaterial004} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh371_1.geometry} material={materials['PhysicalMaterial.112']} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh371_2.geometry} material={materials['PhysicalMaterial.115']} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh371_3.geometry} material={materials['PhysicalMaterial.116']} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh371_4.geometry} material={materials['PhysicalMaterial.117']} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh371_5.geometry} material={materials['PhysicalMaterial.118']} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh371_6.geometry} material={materials['PhysicalMaterial.119']} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh371_7.geometry} material={materials['PhysicalMaterial.120']} />
      </group>
      <mesh castShadow receiveShadow geometry={nodes.Plane.geometry} material={materials.concrete_floor_worn_001} position={[0, 0.2, 0]} scale={[5, 1, 7]} />
      <group position={[0, 0.2, 0]} scale={1.004}>
        <mesh castShadow receiveShadow geometry={nodes.Plane003.geometry} material={materials.PaletteMaterial005} />
        <mesh castShadow receiveShadow geometry={nodes.Plane003_1.geometry} material={materials.laminate_floor} />
        <mesh castShadow receiveShadow geometry={nodes.Plane003_2.geometry} material={materials['Material.002']} />
      </group>
      <group position={[-3.905, 0.321, 6.116]} rotation={[-Math.PI / 2, 0, Math.PI / 2]}>
        <mesh castShadow receiveShadow geometry={nodes.Plane011.geometry} material={materials.PaletteMaterial006} />
        <mesh castShadow receiveShadow geometry={nodes.Plane011_1.geometry} material={materials.PaletteMaterial008} />
        <mesh castShadow receiveShadow geometry={nodes.Plane011_2.geometry} material={materials.Door_Material} />
        <mesh castShadow receiveShadow geometry={nodes.Plane011_3.geometry} material={materials.PaletteMaterial007} />
      </group>
      <group position={[2.789, 0.196, 6.147]} rotation={[Math.PI, 0, Math.PI]} scale={1.38}>
        <mesh castShadow receiveShadow geometry={nodes.Sofa_leg_1.geometry} material={materials.PaletteMaterial010} />
        <mesh castShadow receiveShadow geometry={nodes.Sofa_leg_2.geometry} material={materials.metal_Leg} />
        <mesh castShadow receiveShadow geometry={nodes.Sofa_leg_3.geometry} material={materials.PaletteMaterial009} />
        <mesh castShadow receiveShadow geometry={nodes.Sofa_leg_4.geometry} material={materials.PaletteMaterial011} />
      </group>
      <group position={[4.492, 0.2, -3.942]} rotation={[0, Math.PI / 2, 0]}>
        <mesh castShadow receiveShadow geometry={nodes.Box002001.geometry} material={materials.PaletteMaterial017} />
        <mesh castShadow receiveShadow geometry={nodes.Box002001_1.geometry} material={materials.PaletteMaterial018} />
        <mesh castShadow receiveShadow geometry={nodes.Box002001_2.geometry} material={materials['Kafel1.001']} />
        <mesh castShadow receiveShadow geometry={nodes.Box002001_3.geometry} material={materials['Kafel2.001']} />
        <mesh castShadow receiveShadow geometry={nodes.Box002001_4.geometry} material={materials['Kafel3.001']} />
        <mesh castShadow receiveShadow geometry={nodes.Box002001_5.geometry} material={materials['Kafel4.001']} />
        <mesh castShadow receiveShadow geometry={nodes.Box002001_6.geometry} material={materials['Kafel5.001']} />
        <mesh castShadow receiveShadow geometry={nodes.Box002001_7.geometry} material={materials['Kafel7.001']} />
        <mesh castShadow receiveShadow geometry={nodes.Box002001_8.geometry} material={materials['Kafel8.001']} />
        <mesh castShadow receiveShadow geometry={nodes.Box002001_9.geometry} material={materials['Kafel9.001']} />
        <mesh castShadow receiveShadow geometry={nodes.Box002001_10.geometry} material={materials['Kafel10.001']} />
        <mesh castShadow receiveShadow geometry={nodes.Box002001_11.geometry} material={materials['Kafel12.001']} />
        <mesh castShadow receiveShadow geometry={nodes.Box002001_12.geometry} material={materials['Kafel13.001']} />
        <mesh castShadow receiveShadow geometry={nodes.Box002001_13.geometry} material={materials['Kafel14.001']} />
      </group>
      <mesh castShadow receiveShadow geometry={nodes.Cube001.geometry} material={materials.plastered_wall_04} position={[-5.031, 5.306, 7.007]} scale={0.342} />
      <mesh castShadow receiveShadow geometry={nodes.Cube024.geometry} material={materials.PaletteMaterial019} position={[-3.981, 2.088, 5.685]} rotation={[0, 1.571, 0]} />
      <group position={[4.182, 0.341, 5.278]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh castShadow receiveShadow geometry={nodes.Line001_1.geometry} material={materials['vray Material #36.001']} />
        <mesh castShadow receiveShadow geometry={nodes.Line001_2.geometry} material={materials['vray Material #136.001']} />
      </group>
      <group position={[-2.57, 0.251, -6.434]} scale={0.263}>
        <mesh castShadow receiveShadow geometry={nodes.Line2132555006.geometry} material={materials.PaletteMaterial001} />
        <mesh castShadow receiveShadow geometry={nodes.Line2132555006_1.geometry} material={materials.PaletteMaterial002} />
        <mesh castShadow receiveShadow geometry={nodes.Line2132555006_2.geometry} material={materials.山东色板展示03} />
        <mesh castShadow receiveShadow geometry={nodes.Line2132555006_3.geometry} material={materials.山东色板展示10} />
        <mesh castShadow receiveShadow geometry={nodes.Line2132555006_4.geometry} material={materials.山东色板展示02} />
        <mesh castShadow receiveShadow geometry={nodes.Line2132555006_5.geometry} material={materials.山东色板展示11} />
        <mesh castShadow receiveShadow geometry={nodes.Line2132555006_6.geometry} material={materials.山东色板展示01} />
        <mesh castShadow receiveShadow geometry={nodes.Line2132555006_7.geometry} material={materials.山东色板展示08} />
        <mesh castShadow receiveShadow geometry={nodes.Line2132555006_8.geometry} material={materials.山东色板展示05} />
        <mesh castShadow receiveShadow geometry={nodes.Line2132555006_9.geometry} material={materials.山东色板展示09} />
        <mesh castShadow receiveShadow geometry={nodes.Line2132555006_10.geometry} material={materials.山东色板展示06} />
        <mesh castShadow receiveShadow geometry={nodes.Line2132555006_11.geometry} material={materials.山东色板展示04} />
        <mesh castShadow receiveShadow geometry={nodes.Line2132555006_12.geometry} material={materials.山东色板展示07} />
      </group>
      <mesh castShadow receiveShadow geometry={nodes.Plane007.geometry} material={materials.LCD05} position={[-6.913, 0.819, -0.029]} rotation={[0, -Math.PI / 2, 0]} scale={[1.451, 1.296, 1.296]} />
      <mesh castShadow receiveShadow geometry={nodes.Bosch_HBG6764S6B_001.geometry} material={materials.PaletteMaterial012} position={[-0.526, 0.165, 0.498]} rotation={[Math.PI / 2, 0, Math.PI]} />
      <mesh castShadow receiveShadow geometry={nodes.Bosch_HBG6764S6B_004.geometry} material={materials.wire_115115115} position={[-0.526, 0.165, 0.498]} rotation={[Math.PI / 2, 0, Math.PI]} />
      <mesh castShadow receiveShadow geometry={nodes.Bosch_HBG6764S6B_022.geometry} material={materials.wire_086086086} position={[-0.526, 0.165, 0.498]} rotation={[Math.PI / 2, 0, Math.PI]} />
      <mesh castShadow receiveShadow geometry={nodes.Box002.geometry} material={materials.wire_038032026} position={[-0.526, 0.165, 0.498]} rotation={[Math.PI / 2, 0, Math.PI]} />
      <mesh castShadow receiveShadow geometry={nodes.Box012.geometry} material={materials.PaletteMaterial013} position={[-0.844, 0.165, 0.29]} rotation={[Math.PI / 2, 0, Math.PI]} />
      <mesh castShadow receiveShadow geometry={nodes.Plane001.geometry} material={materials.wire_005005005} position={[-0.844, 0.165, 0.29]} rotation={[Math.PI / 2, 0, Math.PI]} />
      <group position={[3.064, 0.201, 0.29]} rotation={[0, Math.PI / 2, 0]}>
        <mesh castShadow receiveShadow geometry={nodes.Mat01_152003.geometry} material={materials.wire_177028149} />
        <mesh castShadow receiveShadow geometry={nodes.Mat01_152003_1.geometry} material={materials['Material.003']} />
      </group>
      <group position={[4.441, 0.202, -6.394]} rotation={[0, 0.062, 0]}>
        <mesh castShadow receiveShadow geometry={nodes.Box9419_1.geometry} material={materials.Podnoj} />
        <mesh castShadow receiveShadow geometry={nodes.Box9419_2.geometry} material={materials['Material.019']} />
        <mesh castShadow receiveShadow geometry={nodes.Box9419_3.geometry} material={materials['Material.017']} />
        <mesh castShadow receiveShadow geometry={nodes.Box9419_4.geometry} material={materials['Material.013']} />
        <mesh castShadow receiveShadow geometry={nodes.Box9419_5.geometry} material={materials['Material.018']} />
        <mesh castShadow receiveShadow geometry={nodes.Box9419_6.geometry} material={materials.NakleyWB} />
        <mesh castShadow receiveShadow geometry={nodes.Box9419_7.geometry} material={materials['Material.016']} />
        <mesh castShadow receiveShadow geometry={nodes.Box9419_8.geometry} material={materials['Material.015']} />
        <mesh castShadow receiveShadow geometry={nodes.Box9419_9.geometry} material={materials['Material.014']} />
        <mesh castShadow receiveShadow geometry={nodes.Box9419_10.geometry} material={materials['Material.012']} />
      </group>
      <group position={[4.202, 0.202, -5.967]} rotation={[0, 0.062, 0]} scale={5.812}>
        <mesh castShadow receiveShadow geometry={nodes.Box9449_1.geometry} material={materials['Box.020']} />
        <mesh castShadow receiveShadow geometry={nodes.Box9449_2.geometry} material={materials.Box} />
        <mesh castShadow receiveShadow geometry={nodes.Box9449_3.geometry} material={materials['Eg-Nakl']} />
        <mesh castShadow receiveShadow geometry={nodes.Box9449_4.geometry} material={materials['Box.001']} />
        <mesh castShadow receiveShadow geometry={nodes.Box9449_5.geometry} material={materials['Box.002']} />
        <mesh castShadow receiveShadow geometry={nodes.Box9449_6.geometry} material={materials['Box.003']} />
        <mesh castShadow receiveShadow geometry={nodes.Box9449_7.geometry} material={materials['Box.004']} />
        <mesh castShadow receiveShadow geometry={nodes.Box9449_8.geometry} material={materials['Box.005']} />
        <mesh castShadow receiveShadow geometry={nodes.Box9449_9.geometry} material={materials['Box.009']} />
        <mesh castShadow receiveShadow geometry={nodes.Box9449_10.geometry} material={materials['Box.011']} />
        <mesh castShadow receiveShadow geometry={nodes.Box9449_11.geometry} material={materials['Box.013']} />
      </group>
      <group position={[4.548, 0.201, -6.665]} rotation={[0, 0.062, 0]}>
        <mesh castShadow receiveShadow geometry={nodes.Box9616_1.geometry} material={materials.NakleyCork} />
        <mesh castShadow receiveShadow geometry={nodes.Box9616_2.geometry} material={materials['Box.022']} />
        <mesh castShadow receiveShadow geometry={nodes.Box9616_3.geometry} material={materials['Box.023']} />
        <mesh castShadow receiveShadow geometry={nodes.Box9616_4.geometry} material={materials['Box.024']} />
        <mesh castShadow receiveShadow geometry={nodes.Box9616_5.geometry} material={materials['Box.025']} />
        <mesh castShadow receiveShadow geometry={nodes.Box9616_6.geometry} material={materials['Box.026']} />
        <mesh castShadow receiveShadow geometry={nodes.Box9616_7.geometry} material={materials['Box.030']} />
        <mesh castShadow receiveShadow geometry={nodes.Box9616_8.geometry} material={materials['Box.021']} />
      </group>
      <mesh castShadow receiveShadow geometry={nodes.Box9647.geometry} material={materials.PaletteMaterial014} position={[4.828, 0.22, -6.682]} rotation={[0, 0.062, 0]} scale={5.812} />
      <group position={[4.42, 0.213, -5.511]} rotation={[0, 0.061, 0]}>
        <mesh castShadow receiveShadow geometry={nodes.Box9762_1.geometry} material={materials.Atl10} />
        <mesh castShadow receiveShadow geometry={nodes.Box9762_2.geometry} material={materials.Atl9} />
        <mesh castShadow receiveShadow geometry={nodes.Box9762_3.geometry} material={materials.Atl8} />
        <mesh castShadow receiveShadow geometry={nodes.Box9762_4.geometry} material={materials.Atl13} />
        <mesh castShadow receiveShadow geometry={nodes.Box9762_5.geometry} material={materials.Atl6} />
        <mesh castShadow receiveShadow geometry={nodes.Box9762_6.geometry} material={materials.Atl5} />
        <mesh castShadow receiveShadow geometry={nodes.Box9762_7.geometry} material={materials.Atl3} />
      </group>
      <mesh castShadow receiveShadow geometry={nodes.Box9768.geometry} material={materials['Atl Logo']} position={[4.26, 1.208, -5.371]} rotation={[0, 0.062, 0]} scale={5.812} />
      <mesh castShadow receiveShadow geometry={nodes.Box9787.geometry} material={materials['Atl Verh 5']} position={[4.252, 1.033, -5.5]} rotation={[0, 0.062, 0]} scale={5.812} />
      <mesh castShadow receiveShadow geometry={nodes.Object2111141009.geometry} material={materials.PaletteMaterial015} position={[1.005, 0.336, -6.456]} scale={0.248} />
      <group position={[0.494, 0.6, -6.443]} scale={0.248}>
        <mesh castShadow receiveShadow geometry={nodes.Object2111141018_1.geometry} material={materials['4dddddddddddd']} />
        <mesh castShadow receiveShadow geometry={nodes.Object2111141018_2.geometry} material={materials.Mat3d6wewewe} />
        <mesh castShadow receiveShadow geometry={nodes.Object2111141018_3.geometry} material={materials.Matsdfdsfsdfsdf} />
        <mesh castShadow receiveShadow geometry={nodes.Object2111141018_4.geometry} material={materials['00401aghj']} />
        <mesh castShadow receiveShadow geometry={nodes.Object2111141018_5.geometry} material={materials.山东色板展示06dfdfdf} />
        <mesh castShadow receiveShadow geometry={nodes.Object2111141018_6.geometry} material={materials['00401asdfdsf']} />
        <mesh castShadow receiveShadow geometry={nodes.Object2111141018_7.geometry} material={materials['4dddd878787878']} />
      </group>
      <mesh castShadow receiveShadow geometry={nodes.Object2111141533.geometry} material={materials.山东dddddddddddd} position={[0.524, 0.861, -6.443]} scale={0.248} />
      <group position={[0.91, 1.118, -6.417]} scale={0.248}>
        <mesh castShadow receiveShadow geometry={nodes.Rectangle2133442562_1.geometry} material={materials['45sd4545454545']} />
        <mesh castShadow receiveShadow geometry={nodes.Rectangle2133442562_2.geometry} material={materials.山东dddddddddddddddd} />
        <mesh castShadow receiveShadow geometry={nodes.Rectangle2133442562_3.geometry} material={materials['4545sdsd']} />
        <mesh castShadow receiveShadow geometry={nodes.Rectangle2133442562_4.geometry} material={materials['Material #5dfdfffff']} />
        <mesh castShadow receiveShadow geometry={nodes.Rectangle2133442562_5.geometry} material={materials.山ededdddssssffggsdsd} />
        <mesh castShadow receiveShadow geometry={nodes.Rectangle2133442562_6.geometry} material={materials.山ededdddssssffgg} />
        <mesh castShadow receiveShadow geometry={nodes.Rectangle2133442562_7.geometry} material={materials.山ededd} />
        <mesh castShadow receiveShadow geometry={nodes.Rectangle2133442562_8.geometry} material={materials.PaletteMaterial016} />
        <mesh castShadow receiveShadow geometry={nodes.Rectangle2133442562_9.geometry} material={materials['45sd4545454545dfdf']} />
        <mesh castShadow receiveShadow geometry={nodes.Rectangle2133442562_10.geometry} material={materials['Material #-2147483648']} />
        <mesh castShadow receiveShadow geometry={nodes.Rectangle2133442562_11.geometry} material={materials['4dddd878787878dfdf']} />
      </group>
      <group position={[-3.049, 0.269, -2.398]} rotation={[0, Math.PI / 2, 0]} scale={[0.222, 0.266, 0.266]}>
        <mesh castShadow receiveShadow geometry={nodes.Object2111140313_1.geometry} material={materials.PaletteMaterial020} />
        <mesh castShadow receiveShadow geometry={nodes.Object2111140313_2.geometry} material={materials['7sssssssssssssssdsd']} />
        <mesh castShadow receiveShadow geometry={nodes.Object2111140313_3.geometry} material={materials['Mat3d66-718222-10-8417']} />
        <mesh castShadow receiveShadow geometry={nodes.Object2111140313_4.geometry} material={materials.PaletteMaterial021} />
        <mesh castShadow receiveShadow geometry={nodes.Object2111140313_5.geometry} material={materials['Mat3d66-7dsfdsgdfg']} />
        <mesh castShadow receiveShadow geometry={nodes.Object2111140313_6.geometry} material={materials['Mat3d66-718222-6-224']} />
        <mesh castShadow receiveShadow geometry={nodes.Object2111140313_7.geometry} material={materials['Mat3d66-718222-8-704']} />
      </group>
      <group position={[-3.042, 0.673, -5.33]} rotation={[0, Math.PI / 2, 0]} scale={[0.222, 0.266, 0.266]}>
        <mesh castShadow receiveShadow geometry={nodes.Rectangle2133442128_1.geometry} material={materials.dddfdffgfgfg} />
        <mesh castShadow receiveShadow geometry={nodes.Rectangle2133442128_2.geometry} material={materials.dddfdffgdfdgfghjhjhjhjfgfgf} />
      </group>
      <mesh castShadow receiveShadow geometry={nodes.Rectangle2133442273.geometry} material={materials.dddfdffgdfdgfghjhjhjhjfgfgdfdfdf} position={[-3.04, 1.088, -4.974]} rotation={[0, Math.PI / 2, 0]} scale={[0.222, 0.266, 0.266]} />
    </group>
  )
}